In [1]:
import pandas as pd

In [2]:
fed_prison_df = pd.read_csv("total_fed_prison_deaths.csv")

In [3]:
##Federal prison deaths raw numbers for 2015-18
fed_prison_df.head()

,Year,Total deaths,Illness,AIDS-related,Suicide,Accident,Homicide,Other/unknown
0,2015,464,407,1,21,16,16,3
1,2016,395,343,1,19,14,15,3
2,2017,388,323,6,24,8,10,17
3,2018,383,292,0,29,14,12,36

In [4]:
fed_prison_df["Illness"].value_counts()

407    1
343    1
323    1
292    1
Name: Illness, dtype: int64

In [5]:
fed_prison_df["Illness"].sum()

1365

In [6]:
fed_prison_df["Illness"].median()

333.0

In [7]:
fed_prison_df["Illness"].min()

292

In [8]:
##Reading in death rates by state and disease
rate_state_dc_df = pd.read_csv("state_death_cause_rate.csv")

In [9]:
rate_state_dc_df.head()

,Jurisdiction,All causes,Heart disease,Cancer,Liver disease,AIDS-related,Respiratory,All other illnesses,Suicide,Drug/alcohol intoxication,Accident,Homicide
0,Alabama,352,81,89,30,8,24,63,9,3,4,10
1,Alaska,194,46,31,19,1,4,26,37,11,10,4
2,Arizona,237,56,62,30,5,13,30,17,11,2,8
3,Arkansas,363,122,97,26,10,18,37,21,17,6,6
4,California,244,42,60,24,4,17,50,21,12,2,10

In [10]:
##Importing death rates by disease and state
rate_state_dc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Jurisdiction               50 non-null     object
 1   All causes                 50 non-null     int64
 2   Heart disease              50 non-null     int64
 3   Cancer                     50 non-null     int64
 4   Liver disease              50 non-null     int64
 5   AIDS-related               50 non-null     int64
 6   Respiratory                50 non-null     int64
 7   All other illnesses        50 non-null     int64
 8   Suicide                    50 non-null     int64
 9   Drug/alcohol intoxication  50 non-null     int64
 10  Accident                   50 non-null     int64
 11  Homicide                   50 non-null     int64
dtypes: int64(11), object(1)
memory usage: 4.8+ KB

In [11]:
##Median rate of heart disease
rate_state_dc_df["Heart disease"].median()

66.0

In [12]:
##Median rate of liver disease
rate_state_dc_df["Liver disease"].median()

23.5

In [13]:
##Full dataset
rate_state_dc_df

,Jurisdiction,All causes,Heart disease,Cancer,Liver disease,AIDS-related,Respiratory,All other illnesses,Suicide,Drug/alcohol intoxication,Accident,Homicide
0,Alabama,352,81,89,30,8,24,63,9,3,4,10
1,Alaska,194,46,31,19,1,4,26,37,11,10,4
2,Arizona,237,56,62,30,5,13,30,17,11,2,8
3,Arkansas,363,122,97,26,10,18,37,21,17,6,6
4,California,244,42,60,24,4,17,50,21,12,2,10
5,Colorado,217,42,44,35,0,16,39,20,9,4,8
6,Connecticut,151,37,21,21,4,9,31,24,1,2,2
7,Delaware,230,58,53,21,17,12,28,27,5,1,2
8,Florida,313,67,92,24,18,21,55,10,10,4,8
9,Georgia,237,79,60,13,9,19,30,13,1,2,8
10,Hawaii,169,31,44,18,4,7,24,29,4,1,5
11,Idaho,215,56,53,19,3,11,31,28,4,4,3
12,Illinois,195,56,62,10,8,11,26,16,2,2,2
13,Indiana,255,68,69,22,5,17,37,17,9,4,6
14,Iowa,183,40,63,11,3,18,22,20,2,1,1
15,Kansas,264,73,76,30,1,18,39,16,4,5,2
16,Kentucky,373,125,118,27,13,19,55,9,1,2,3
17,Louisiana,535,165,162,41,32,25,68,12,1,6,3
18,Maine,198,62,48,16,3,16,21,11,5,0,13
19,Maryland,260,65,55,21,27,11,29,20,16,2,12
20,Massachusetts,336,92,92,34,5,15,49,31,5,5,2
21,Michigan,265,79,90,21,5,15,27,16,4,3,3
22,Minnesota,148,30,44,20,1,6,27,16,3,1,1
23,Mississippi,359,131,90,17,9,18,49,17,1,5,10
24,Missouri,266,73,81,29,5,15,39,13,4,1,4
25,Montana,292,56,80,45,4,18,45,33,5,2,4
26,Nebraska,234,53,53,30,5,11,26,22,6,4,7
27,Nevada,282,68,64,19,4,12,58,18,3,2,5
28,New Hampshire,255,56,99,24,6,9,26,26,11,0,0
29,New Jersey,234,74,55,14,20,14,31,12,5,2,3
30,New Mexico,268,60,69,48,3,14,32,24,6,1,9
31,New York,250,66,72,19,21,11,22,22,5,3,3
32,North Carolina,242,66,79,20,11,16,32,10,1,4,2
33,North Dakota,79,16,20,8,4,0,12,16,4,0,0
34,Ohio,245,70,84,13,4,18,34,14,2,1,3
35,Oklahoma,336,88,85,38,7,19,45,20,9,7,14
36,Oregon,248,53,76,36,3,12,33,15,5,3,4
37,Pennsylvania,330,94,95,29,5,21,60,18,3,2,2
38,Rhode Island,192,46,36,5,9,9,15,45,9,5,2
39,South Carolina,315,119,68,21,9,13,49,17,3,2,13
40,South Dakota,209,49,46,29,2,21,21,28,2,7,5
41,Tennessee,408,124,112,42,12,20,55,19,8,4,9
42,Texas,272,68,68,29,6,21,55,18,1,3,3
43,Utah,273,66,58,22,0,11,48,44,6,3,9
44,Vermont,205,50,39,33,9,3,33,30,9,0,0
45,Virginia,286,76,98,28,10,15,37,11,3,2,3
46,Washington,209,49,60,23,3,18,32,14,3,4,3
47,West Virginia,412,156,110,28,7,19,65,11,3,2,7
48,Wisconsin,200,56,66,12,3,16,21,21,2,1,0
49,Wyoming,283,103,46,38,3,22,41,22,5,3,0

In [14]:
##States with higher rates of heart disease
rate_state_dc_df.sort_values(by=["Heart disease"], ascending = False).head(15)

,Jurisdiction,All causes,Heart disease,Cancer,Liver disease,AIDS-related,Respiratory,All other illnesses,Suicide,Drug/alcohol intoxication,Accident,Homicide
17,Louisiana,535,165,162,41,32,25,68,12,1,6,3
47,West Virginia,412,156,110,28,7,19,65,11,3,2,7
23,Mississippi,359,131,90,17,9,18,49,17,1,5,10
16,Kentucky,373,125,118,27,13,19,55,9,1,2,3
41,Tennessee,408,124,112,42,12,20,55,19,8,4,9
3,Arkansas,363,122,97,26,10,18,37,21,17,6,6
39,South Carolina,315,119,68,21,9,13,49,17,3,2,13
49,Wyoming,283,103,46,38,3,22,41,22,5,3,0
37,Pennsylvania,330,94,95,29,5,21,60,18,3,2,2
20,Massachusetts,336,92,92,34,5,15,49,31,5,5,2
35,Oklahoma,336,88,85,38,7,19,45,20,9,7,14
0,Alabama,352,81,89,30,8,24,63,9,3,4,10
9,Georgia,237,79,60,13,9,19,30,13,1,2,8
21,Michigan,265,79,90,21,5,15,27,16,4,3,3
45,Virginia,286,76,98,28,10,15,37,11,3,2,3

In [15]:
## States with highest rates of all causes of death. Louisiana is a leader in poor prison health.
rate_state_dc_df.sort_values(by=["All causes"], ascending = False)

,Jurisdiction,All causes,Heart disease,Cancer,Liver disease,AIDS-related,Respiratory,All other illnesses,Suicide,Drug/alcohol intoxication,Accident,Homicide
17,Louisiana,535,165,162,41,32,25,68,12,1,6,3
47,West Virginia,412,156,110,28,7,19,65,11,3,2,7
41,Tennessee,408,124,112,42,12,20,55,19,8,4,9
16,Kentucky,373,125,118,27,13,19,55,9,1,2,3
3,Arkansas,363,122,97,26,10,18,37,21,17,6,6
23,Mississippi,359,131,90,17,9,18,49,17,1,5,10
0,Alabama,352,81,89,30,8,24,63,9,3,4,10
35,Oklahoma,336,88,85,38,7,19,45,20,9,7,14
20,Massachusetts,336,92,92,34,5,15,49,31,5,5,2
37,Pennsylvania,330,94,95,29,5,21,60,18,3,2,2
39,South Carolina,315,119,68,21,9,13,49,17,3,2,13
8,Florida,313,67,92,24,18,21,55,10,10,4,8
25,Montana,292,56,80,45,4,18,45,33,5,2,4
45,Virginia,286,76,98,28,10,15,37,11,3,2,3
49,Wyoming,283,103,46,38,3,22,41,22,5,3,0
27,Nevada,282,68,64,19,4,12,58,18,3,2,5
43,Utah,273,66,58,22,0,11,48,44,6,3,9
42,Texas,272,68,68,29,6,21,55,18,1,3,3
30,New Mexico,268,60,69,48,3,14,32,24,6,1,9
24,Missouri,266,73,81,29,5,15,39,13,4,1,4
21,Michigan,265,79,90,21,5,15,27,16,4,3,3
15,Kansas,264,73,76,30,1,18,39,16,4,5,2
19,Maryland,260,65,55,21,27,11,29,20,16,2,12
28,New Hampshire,255,56,99,24,6,9,26,26,11,0,0
13,Indiana,255,68,69,22,5,17,37,17,9,4,6
31,New York,250,66,72,19,21,11,22,22,5,3,3
36,Oregon,248,53,76,36,3,12,33,15,5,3,4
34,Ohio,245,70,84,13,4,18,34,14,2,1,3
4,California,244,42,60,24,4,17,50,21,12,2,10
32,North Carolina,242,66,79,20,11,16,32,10,1,4,2
2,Arizona,237,56,62,30,5,13,30,17,11,2,8
9,Georgia,237,79,60,13,9,19,30,13,1,2,8
29,New Jersey,234,74,55,14,20,14,31,12,5,2,3
26,Nebraska,234,53,53,30,5,11,26,22,6,4,7
7,Delaware,230,58,53,21,17,12,28,27,5,1,2
5,Colorado,217,42,44,35,0,16,39,20,9,4,8
11,Idaho,215,56,53,19,3,11,31,28,4,4,3
46,Washington,209,49,60,23,3,18,32,14,3,4,3
40,South Dakota,209,49,46,29,2,21,21,28,2,7,5
44,Vermont,205,50,39,33,9,3,33,30,9,0,0
48,Wisconsin,200,56,66,12,3,16,21,21,2,1,0
18,Maine,198,62,48,16,3,16,21,11,5,0,13
12,Illinois,195,56,62,10,8,11,26,16,2,2,2
1,Alaska,194,46,31,19,1,4,26,37,11,10,4
38,Rhode Island,192,46,36,5,9,9,15,45,9,5,2
14,Iowa,183,40,63,11,3,18,22,20,2,1,1
10,Hawaii,169,31,44,18,4,7,24,29,4,1,5
6,Connecticut,151,37,21,21,4,9,31,24,1,2,2
22,Minnesota,148,30,44,20,1,6,27,16,3,1,1
33,North Dakota,79,16,20,8,4,0,12,16,4,0,0

In [16]:
state_fed_deaths_df = pd.read_csv("state_fed_deaths.csv")

In [17]:
state_fed_deaths_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    18 non-null     int64
 1   state mortality rate    18 non-null     int64
 2   federal mortality rate  18 non-null     int64
dtypes: int64(3)
memory usage: 560.0 bytes

In [18]:
##Mortality rates for states vs. prisons. States prisons tend to fare a little worse.
state_fed_deaths_df.head()

   Year  state mortality rate  federal mortality rate
0  2001                   242                     220
1  2002                   243                     233
2  2003                   257                     228
3  2004                   251                     210
4  2005                   251                     244

In [19]:
##The gap between state and federal prisons has grown significantly
state_fed_deaths_df

    Year  state mortality rate  federal mortality rate
0   2001                   242                     220
1   2002                   243                     233
2   2003                   257                     228
3   2004                   251                     210
4   2005                   251                     244
5   2006                   249                     201
6   2007                   258                     222
7   2008                   261                     241
8   2009                   259                     220
9   2010                   246                     224
10  2011                   260                     220
11  2012                   265                     198
12  2013                   274                     230
13  2014                   274                     262
14  2015                   296                     283
15  2016                   303                     252
16  2017                   323                     246
17  2018                   344                     250

In [20]:
##the last four years of data are the highest death reates for state prisons
state_fed_deaths_df.sort_values(by=["state mortality rate"], ascending = False)

    Year  state mortality rate  federal mortality rate
17  2018                   344                     250
16  2017                   323                     246
15  2016                   303                     252
14  2015                   296                     283
12  2013                   274                     230
13  2014                   274                     262
11  2012                   265                     198
7   2008                   261                     241
10  2011                   260                     220
8   2009                   259                     220
6   2007                   258                     222
2   2003                   257                     228
3   2004                   251                     210
4   2005                   251                     244
5   2006                   249                     201
9   2010                   246                     224
1   2002                   243                     233
0   2001                   242                     220

In [21]:
##More recent years haven't been as bad for feds, but still some of the worst years.
state_fed_deaths_df.sort_values(by=["federal mortality rate"], ascending = False)

    Year  state mortality rate  federal mortality rate
14  2015                   296                     283
13  2014                   274                     262
15  2016                   303                     252
17  2018                   344                     250
16  2017                   323                     246
4   2005                   251                     244
7   2008                   261                     241
1   2002                   243                     233
12  2013                   274                     230
2   2003                   257                     228
9   2010                   246                     224
6   2007                   258                     222
10  2011                   260                     220
8   2009                   259                     220
0   2001                   242                     220
3   2004                   251                     210
5   2006                   249                     201
11  2012                   265                     198

In [22]:
state_death_dem_df = pd.read_csv("state_death_dem.csv")

In [23]:
state_death_dem_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 15 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Year                                                            12 non-null     int64
 1   Total deaths                                                    12 non-null     object
 2   Male                                                            12 non-null     object
 3   Female                                                          12 non-null     int64
 4   White                                                           12 non-null     object
 5   Black                                                           12 non-null     object
 6   Hispanic                                                        12 non-null     int64
 7   American Indian/Alaska Native                                   12 non-null     int64
 8   Asian/Native Hawaiian/Other Pacific Islander/two or more races  12 non-null     int64
 9   17 or younger                                                   12 non-null     int64
 10  18 to 24                                                        12 non-null     int64
 11  25 to 34                                                        12 non-null     int64
 12  35 to 44                                                        12 non-null     int64
 13  45 to 54                                                        12 non-null     object
 14  55 or older                                                     12 non-null     object
dtypes: int64(9), object(6)
memory usage: 1.5+ KB

In [24]:
##Sorting state demographic data. More than 4,100 total deaths in state prisons in 2018. Was 2,869 in 2001. Female deaths are much less.
state_death_dem_df.sort_values(by=["Total deaths"], ascending = False)

,Year,Total deaths,Male,Female,White,Black,Hispanic,American Indian/Alaska Native,Asian/Native Hawaiian/Other Pacific Islander/two or more races,17 or younger,18 to 24,25 to 34,35 to 44,45 to 54,55 or older
11,2018,"4,135","3,954",180,"2,198","1,352",503,48,30,0,66,328,421,776,"2,543"
10,2017,"3,943","3,811",131,"2,156","1,268",437,47,27,1,60,308,405,697,"2,472"
9,2016,"3,729","3,586",143,"2,063","1,201",382,51,29,1,72,246,379,721,"2,298"
8,2015,"3,682","3,533",149,"2,040","1,189",367,52,33,0,68,226,342,795,"2,250"
7,2014,"3,484","3,330",154,"1,921","1,108",368,43,44,2,56,221,335,821,"2,049"
6,2013,"3,478","3,337",141,"1,901","1,104",402,37,33,0,69,221,334,861,"1,993"
1,2008,"3,452","3,289",163,"1,822","1,157",400,36,37,3,67,222,468,"1,063","1,629"
2,2009,"3,417","3,267",150,"1,774","1,199",372,31,27,0,69,210,467,"1,039","1,631"
5,2012,"3,357","3,244",113,"1,789","1,113",379,40,30,0,69,190,360,876,"1,862"
4,2011,"3,351","3,208",143,"1,912","1,037",329,36,25,2,50,200,397,930,"1,771"
3,2010,"3,233","3,116",117,"1,680","1,121",359,36,25,3,69,217,382,956,"1,606"
0,2001,"2,869","2,769",100,"1,340","1,161",322,25,16,2,86,256,656,893,972

In [25]:
state_death_dem_df.sort_values(by=["White"], ascending = False)

,Year,Total deaths,Male,Female,White,Black,Hispanic,American Indian/Alaska Native,Asian/Native Hawaiian/Other Pacific Islander/two or more races,17 or younger,18 to 24,25 to 34,35 to 44,45 to 54,55 or older
11,2018,"4,135","3,954",180,"2,198","1,352",503,48,30,0,66,328,421,776,"2,543"
10,2017,"3,943","3,811",131,"2,156","1,268",437,47,27,1,60,308,405,697,"2,472"
9,2016,"3,729","3,586",143,"2,063","1,201",382,51,29,1,72,246,379,721,"2,298"
8,2015,"3,682","3,533",149,"2,040","1,189",367,52,33,0,68,226,342,795,"2,250"
7,2014,"3,484","3,330",154,"1,921","1,108",368,43,44,2,56,221,335,821,"2,049"
4,2011,"3,351","3,208",143,"1,912","1,037",329,36,25,2,50,200,397,930,"1,771"
6,2013,"3,478","3,337",141,"1,901","1,104",402,37,33,0,69,221,334,861,"1,993"
1,2008,"3,452","3,289",163,"1,822","1,157",400,36,37,3,67,222,468,"1,063","1,629"
5,2012,"3,357","3,244",113,"1,789","1,113",379,40,30,0,69,190,360,876,"1,862"
2,2009,"3,417","3,267",150,"1,774","1,199",372,31,27,0,69,210,467,"1,039","1,631"
3,2010,"3,233","3,116",117,"1,680","1,121",359,36,25,3,69,217,382,956,"1,606"
0,2001,"2,869","2,769",100,"1,340","1,161",322,25,16,2,86,256,656,893,972

In [26]:
percent_state_deaths_dem_df = pd.read_csv("percent_state_deaths_dem.csv")

In [27]:
##Share of deaths by demographic.
percent_state_deaths_dem_df

,Year,Male,Female,White,Black,Hispanic,American Indian/Alaska Native,Asian/Native Hawaiian/Other Pacific Islander/two or more races,18 to 24,25 to 34,35 to 44,45 to 54,55 or older
0,2001,96.5,3.5,46.7,40.5,11.2,0.9,0.6,3.0,8.9,22.9,31.1,33.9
1,2008,95.3,4.7,52.8,33.5,11.6,1.0,1.1,1.9,6.4,13.6,30.8,47.2
2,2009,95.6,4.4,51.9,35.1,10.9,0.9,0.8,2.0,6.2,13.7,30.4,47.7
3,2010,96.4,3.6,52.0,34.7,11.1,1.1,0.8,2.1,6.7,11.8,29.6,49.7
4,2011,95.7,4.3,57.1,31.0,9.8,1.1,0.8,1.5,6.0,11.9,27.8,52.9
5,2012,96.6,3.4,53.3,33.2,11.3,1.2,0.9,2.1,5.7,10.7,26.1,55.5
6,2013,96.0,4.1,54.7,31.7,11.6,1.1,1.0,2.0,6.4,9.6,24.8,57.3
7,2014,95.6,4.4,55.1,31.8,10.6,1.2,1.3,1.6,6.3,9.6,23.6,58.8
8,2015,96.0,4.1,55.4,32.3,10.0,1.4,0.9,1.9,6.1,9.3,21.6,61.1
9,2016,96.2,3.8,55.3,32.2,10.2,1.4,0.8,1.9,6.6,10.2,19.3,61.6
10,2017,96.7,3.3,54.7,32.2,11.1,1.2,0.7,1.5,7.8,10.3,17.7,62.7
11,2018,95.6,4.4,53.2,32.7,12.2,1.2,0.7,1.6,7.9,10.2,18.8,61.5

In [28]:
state_death_df = pd.read_csv("raw_death_state.csv")

In [29]:
state_death_df.head()

,Jurisdiction,All causes,Heart disease,Cancer,Liver disease,AIDS-related,Respiratory disease,All other illnesses,Suicide,Drug/alcohol intoxication,Accident,Homicide
0,Alabama,"1,730",404,433,137,38,113,306,46,27,17,63
1,Alaska,179,42,29,17,1,4,24,36,10,9,4
2,Arizona,"1,721",419,455,211,35,96,210,123,87,15,55
3,Arkansas,976,319,264,65,25,48,100,63,52,14,16
4,California,"7,026","1,183","1,728",656,116,512,"1,429",596,402,54,304

In [30]:
state_death_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Jurisdiction               50 non-null     object
 1   All causes                 50 non-null     object
 2   Heart disease              50 non-null     object
 3   Cancer                     50 non-null     object
 4   Liver disease              50 non-null     int64
 5   AIDS-related               50 non-null     int64
 6   Respiratory disease        50 non-null     int64
 7   All other illnesses        50 non-null     object
 8   Suicide                    50 non-null     int64
 9   Drug/alcohol intoxication  50 non-null     int64
 10  Accident                   50 non-null     int64
 11  Homicide                   50 non-null     int64
dtypes: int64(7), object(5)
memory usage: 4.8+ KB

In [144]:
##Big states lead the way in raw death numbers, but Lousiana and Alabama are high up here for their populations.
state_death_df.sort_values(by=["All causes"], ascending = False)

,Jurisdiction,All causes,Heart disease,Cancer,Liver disease,AIDS-related,Respiratory disease,All other illnesses,Suicide,Drug/alcohol intoxication,Accident,Homicide
42,Texas,8050,2015,2039,816,173,632,1619,527,39,79,83
4,California,7026,1183,1728,656,116,512,1429,596,402,54,304
8,Florida,5660,1247,1654,419,310,366,994,197,186,69,158
37,Pennsylvania,2887,802,848,244,38,182,531,169,23,16,21
31,New York,2711,726,784,197,221,127,246,247,61,34,30
9,Georgia,2369,780,597,125,83,187,300,145,12,22,89
34,Ohio,2311,654,801,120,34,177,316,134,24,8,33
21,Michigan,2296,681,783,170,39,132,245,134,42,25,27
17,Louisiana,1953,611,564,152,110,98,269,42,10,23,9
0,Alabama,1730,404,433,137,38,113,306,46,27,17,63
32,North Carolina,1724,476,571,131,75,114,220,68,13,26,19
2,Arizona,1721,419,455,211,35,96,210,123,87,15,55
12,Illinois,1684,487,530,83,65,96,222,137,15,16,18
45,Virginia,1676,450,565,157,55,87,223,65,28,10,15
35,Oklahoma,1575,424,400,169,30,89,204,92,46,32,65
24,Missouri,1555,422,476,159,26,91,227,72,37,9,24
41,Tennessee,1554,470,426,158,43,77,201,77,38,13,39
39,South Carolina,1316,499,281,81,36,54,198,79,17,7,61
13,Indiana,1258,336,336,106,23,84,180,87,50,18,32
19,Maryland,1100,278,232,83,109,48,122,82,66,9,51
23,Mississippi,1073,390,265,48,24,52,151,58,5,13,33
29,New Jersey,1029,329,244,60,83,62,137,53,25,10,14
3,Arkansas,976,319,264,65,25,48,100,63,52,14,16
16,Kentucky,950,323,307,67,30,46,133,25,3,5,6
48,Wisconsin,857,244,275,52,11,69,93,88,13,6,1
5,Colorado,854,164,178,136,1,61,151,79,39,15,29
46,Washington,674,153,196,72,9,59,104,48,11,11,8
27,Nevada,657,154,159,46,9,32,131,40,6,4,12
20,Massachusetts,656,186,180,61,10,29,92,61,11,11,4
36,Oregon,642,136,189,87,7,29,81,37,14,7,10
6,Connecticut,491,117,69,69,11,27,99,80,5,6,7
15,Kansas,471,131,136,51,2,29,67,31,9,8,3
47,West Virginia,394,156,104,26,6,17,59,11,3,2,7
30,New Mexico,336,78,89,56,4,18,41,29,7,1,12
14,Iowa,306,67,104,16,5,31,40,34,3,1,2
11,Idaho,290,76,73,24,4,13,44,39,5,5,4
7,Delaware,287,74,65,25,21,14,36,33,6,1,2
43,Utah,266,63,59,20,0,11,48,41,5,4,9
22,Minnesota,245,51,72,33,1,10,45,27,4,1,1
26,Nebraska,212,47,50,27,4,11,22,20,6,3,7
1,Alaska,179,42,29,17,1,4,24,36,10,9,4
10,Hawaii,176,33,46,17,4,8,25,28,4,2,7
25,Montana,169,34,46,26,2,10,26,19,3,1,2
40,South Dakota,140,35,34,18,1,14,13,17,1,4,3
28,New Hampshire,127,27,47,12,3,7,14,12,5,0,0
38,Rhode Island,115,27,21,3,5,5,11,27,5,3,1
49,Wyoming,113,42,18,15,1,9,16,9,2,1,0
18,Maine,82,24,24,6,1,6,8,4,2,1,5
44,Vermont,74,19,15,11,3,1,11,11,3,0,0
33,North Dakota,21,4,5,2,1,0,4,4,1,0,0

In [32]:
state_death_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Jurisdiction               50 non-null     object
 1   All causes                 50 non-null     object
 2   Heart disease              50 non-null     object
 3   Cancer                     50 non-null     object
 4   Liver disease              50 non-null     int64
 5   AIDS-related               50 non-null     int64
 6   Respiratory disease        50 non-null     int64
 7   All other illnesses        50 non-null     object
 8   Suicide                    50 non-null     int64
 9   Drug/alcohol intoxication  50 non-null     int64
 10  Accident                   50 non-null     int64
 11  Homicide                   50 non-null     int64
dtypes: int64(7), object(5)
memory usage: 4.8+ KB

In [143]:
##Need to fix errors because of commas.
state_death_df.sort_values(by=["All causes"], ascending = False)

,Jurisdiction,All causes,Heart disease,Cancer,Liver disease,AIDS-related,Respiratory disease,All other illnesses,Suicide,Drug/alcohol intoxication,Accident,Homicide
42,Texas,8050,2015,2039,816,173,632,1619,527,39,79,83
4,California,7026,1183,1728,656,116,512,1429,596,402,54,304
8,Florida,5660,1247,1654,419,310,366,994,197,186,69,158
37,Pennsylvania,2887,802,848,244,38,182,531,169,23,16,21
31,New York,2711,726,784,197,221,127,246,247,61,34,30
9,Georgia,2369,780,597,125,83,187,300,145,12,22,89
34,Ohio,2311,654,801,120,34,177,316,134,24,8,33
21,Michigan,2296,681,783,170,39,132,245,134,42,25,27
17,Louisiana,1953,611,564,152,110,98,269,42,10,23,9
0,Alabama,1730,404,433,137,38,113,306,46,27,17,63
32,North Carolina,1724,476,571,131,75,114,220,68,13,26,19
2,Arizona,1721,419,455,211,35,96,210,123,87,15,55
12,Illinois,1684,487,530,83,65,96,222,137,15,16,18
45,Virginia,1676,450,565,157,55,87,223,65,28,10,15
35,Oklahoma,1575,424,400,169,30,89,204,92,46,32,65
24,Missouri,1555,422,476,159,26,91,227,72,37,9,24
41,Tennessee,1554,470,426,158,43,77,201,77,38,13,39
39,South Carolina,1316,499,281,81,36,54,198,79,17,7,61
13,Indiana,1258,336,336,106,23,84,180,87,50,18,32
19,Maryland,1100,278,232,83,109,48,122,82,66,9,51
23,Mississippi,1073,390,265,48,24,52,151,58,5,13,33
29,New Jersey,1029,329,244,60,83,62,137,53,25,10,14
3,Arkansas,976,319,264,65,25,48,100,63,52,14,16
16,Kentucky,950,323,307,67,30,46,133,25,3,5,6
48,Wisconsin,857,244,275,52,11,69,93,88,13,6,1
5,Colorado,854,164,178,136,1,61,151,79,39,15,29
46,Washington,674,153,196,72,9,59,104,48,11,11,8
27,Nevada,657,154,159,46,9,32,131,40,6,4,12
20,Massachusetts,656,186,180,61,10,29,92,61,11,11,4
36,Oregon,642,136,189,87,7,29,81,37,14,7,10
6,Connecticut,491,117,69,69,11,27,99,80,5,6,7
15,Kansas,471,131,136,51,2,29,67,31,9,8,3
47,West Virginia,394,156,104,26,6,17,59,11,3,2,7
30,New Mexico,336,78,89,56,4,18,41,29,7,1,12
14,Iowa,306,67,104,16,5,31,40,34,3,1,2
11,Idaho,290,76,73,24,4,13,44,39,5,5,4
7,Delaware,287,74,65,25,21,14,36,33,6,1,2
43,Utah,266,63,59,20,0,11,48,41,5,4,9
22,Minnesota,245,51,72,33,1,10,45,27,4,1,1
26,Nebraska,212,47,50,27,4,11,22,20,6,3,7
1,Alaska,179,42,29,17,1,4,24,36,10,9,4
10,Hawaii,176,33,46,17,4,8,25,28,4,2,7
25,Montana,169,34,46,26,2,10,26,19,3,1,2
40,South Dakota,140,35,34,18,1,14,13,17,1,4,3
28,New Hampshire,127,27,47,12,3,7,14,12,5,0,0
38,Rhode Island,115,27,21,3,5,5,11,27,5,3,1
49,Wyoming,113,42,18,15,1,9,16,9,2,1,0
18,Maine,82,24,24,6,1,6,8,4,2,1,5
44,Vermont,74,19,15,11,3,1,11,11,3,0,0
33,North Dakota,21,4,5,2,1,0,4,4,1,0,0

In [34]:
##Fixing errors becuase of commas. Object instead of number.
state_death_df["Cancer"] = state_death_df["Cancer"].str.replace(',','')

In [35]:
state_death_df["Cancer"] = state_death_df["Cancer"].str.replace('.','')

/var/folders/c9/rtw0m_911vd7rr0_d4ym2mfc0000gn/T/ipykernel_81878/262411292.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  state_death_df["Cancer"] = state_death_df["Cancer"].str.replace('.','')

In [36]:
state_death_df["All causes"] = state_death_df["All causes"].str.replace(',','')

In [37]:
state_death_df["Heart disease"] = state_death_df["Heart disease"].str.replace(',','')

In [38]:
state_death_df["All other illnesses"] = state_death_df["All other illnesses"].str.replace(',','')

In [39]:
state_death_df[list(state_death_df.columns)[1]] = \
state_death_df[list(state_death_df.columns)[1]].apply(pd.to_numeric, errors="coerce")

In [40]:
state_death_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Jurisdiction               50 non-null     object
 1   All causes                 50 non-null     int64
 2   Heart disease              50 non-null     object
 3   Cancer                     50 non-null     object
 4   Liver disease              50 non-null     int64
 5   AIDS-related               50 non-null     int64
 6   Respiratory disease        50 non-null     int64
 7   All other illnesses        50 non-null     object
 8   Suicide                    50 non-null     int64
 9   Drug/alcohol intoxication  50 non-null     int64
 10  Accident                   50 non-null     int64
 11  Homicide                   50 non-null     int64
dtypes: int64(8), object(4)
memory usage: 4.8+ KB

In [41]:
##Fixing errors
state_death_df[list(state_death_df.columns)[2]] = \
state_death_df[list(state_death_df.columns)[2]].apply(pd.to_numeric, errors="coerce")

In [42]:
state_death_df[list(state_death_df.columns)[3]] = \
state_death_df[list(state_death_df.columns)[3]].apply(pd.to_numeric, errors="coerce")

In [43]:
state_death_df[list(state_death_df.columns)[7]] = \
state_death_df[list(state_death_df.columns)[7]].apply(pd.to_numeric, errors="coerce")

In [44]:
state_death_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Jurisdiction               50 non-null     object
 1   All causes                 50 non-null     int64
 2   Heart disease              50 non-null     int64
 3   Cancer                     50 non-null     int64
 4   Liver disease              50 non-null     int64
 5   AIDS-related               50 non-null     int64
 6   Respiratory disease        50 non-null     int64
 7   All other illnesses        50 non-null     int64
 8   Suicide                    50 non-null     int64
 9   Drug/alcohol intoxication  50 non-null     int64
 10  Accident                   50 non-null     int64
 11  Homicide                   50 non-null     int64
dtypes: int64(11), object(1)
memory usage: 4.8+ KB

In [45]:
##Errors fixed
state_death_df.sort_values(by=["All causes"], ascending = False)

,Jurisdiction,All causes,Heart disease,Cancer,Liver disease,AIDS-related,Respiratory disease,All other illnesses,Suicide,Drug/alcohol intoxication,Accident,Homicide
42,Texas,8050,2015,2039,816,173,632,1619,527,39,79,83
4,California,7026,1183,1728,656,116,512,1429,596,402,54,304
8,Florida,5660,1247,1654,419,310,366,994,197,186,69,158
37,Pennsylvania,2887,802,848,244,38,182,531,169,23,16,21
31,New York,2711,726,784,197,221,127,246,247,61,34,30
9,Georgia,2369,780,597,125,83,187,300,145,12,22,89
34,Ohio,2311,654,801,120,34,177,316,134,24,8,33
21,Michigan,2296,681,783,170,39,132,245,134,42,25,27
17,Louisiana,1953,611,564,152,110,98,269,42,10,23,9
0,Alabama,1730,404,433,137,38,113,306,46,27,17,63
32,North Carolina,1724,476,571,131,75,114,220,68,13,26,19
2,Arizona,1721,419,455,211,35,96,210,123,87,15,55
12,Illinois,1684,487,530,83,65,96,222,137,15,16,18
45,Virginia,1676,450,565,157,55,87,223,65,28,10,15
35,Oklahoma,1575,424,400,169,30,89,204,92,46,32,65
24,Missouri,1555,422,476,159,26,91,227,72,37,9,24
41,Tennessee,1554,470,426,158,43,77,201,77,38,13,39
39,South Carolina,1316,499,281,81,36,54,198,79,17,7,61
13,Indiana,1258,336,336,106,23,84,180,87,50,18,32
19,Maryland,1100,278,232,83,109,48,122,82,66,9,51
23,Mississippi,1073,390,265,48,24,52,151,58,5,13,33
29,New Jersey,1029,329,244,60,83,62,137,53,25,10,14
3,Arkansas,976,319,264,65,25,48,100,63,52,14,16
16,Kentucky,950,323,307,67,30,46,133,25,3,5,6
48,Wisconsin,857,244,275,52,11,69,93,88,13,6,1
5,Colorado,854,164,178,136,1,61,151,79,39,15,29
46,Washington,674,153,196,72,9,59,104,48,11,11,8
27,Nevada,657,154,159,46,9,32,131,40,6,4,12
20,Massachusetts,656,186,180,61,10,29,92,61,11,11,4
36,Oregon,642,136,189,87,7,29,81,37,14,7,10
6,Connecticut,491,117,69,69,11,27,99,80,5,6,7
15,Kansas,471,131,136,51,2,29,67,31,9,8,3
47,West Virginia,394,156,104,26,6,17,59,11,3,2,7
30,New Mexico,336,78,89,56,4,18,41,29,7,1,12
14,Iowa,306,67,104,16,5,31,40,34,3,1,2
11,Idaho,290,76,73,24,4,13,44,39,5,5,4
7,Delaware,287,74,65,25,21,14,36,33,6,1,2
43,Utah,266,63,59,20,0,11,48,41,5,4,9
22,Minnesota,245,51,72,33,1,10,45,27,4,1,1
26,Nebraska,212,47,50,27,4,11,22,20,6,3,7
1,Alaska,179,42,29,17,1,4,24,36,10,9,4
10,Hawaii,176,33,46,17,4,8,25,28,4,2,7
25,Montana,169,34,46,26,2,10,26,19,3,1,2
40,South Dakota,140,35,34,18,1,14,13,17,1,4,3
28,New Hampshire,127,27,47,12,3,7,14,12,5,0,0
38,Rhode Island,115,27,21,3,5,5,11,27,5,3,1
49,Wyoming,113,42,18,15,1,9,16,9,2,1,0
18,Maine,82,24,24,6,1,6,8,4,2,1,5
44,Vermont,74,19,15,11,3,1,11,11,3,0,0
33,North Dakota,21,4,5,2,1,0,4,4,1,0,0

In [46]:
##States with top raw cancer deaths
state_death_df.sort_values(by=["Cancer"], ascending = False)

,Jurisdiction,All causes,Heart disease,Cancer,Liver disease,AIDS-related,Respiratory disease,All other illnesses,Suicide,Drug/alcohol intoxication,Accident,Homicide
42,Texas,8050,2015,2039,816,173,632,1619,527,39,79,83
4,California,7026,1183,1728,656,116,512,1429,596,402,54,304
8,Florida,5660,1247,1654,419,310,366,994,197,186,69,158
37,Pennsylvania,2887,802,848,244,38,182,531,169,23,16,21
34,Ohio,2311,654,801,120,34,177,316,134,24,8,33
31,New York,2711,726,784,197,221,127,246,247,61,34,30
21,Michigan,2296,681,783,170,39,132,245,134,42,25,27
9,Georgia,2369,780,597,125,83,187,300,145,12,22,89
32,North Carolina,1724,476,571,131,75,114,220,68,13,26,19
45,Virginia,1676,450,565,157,55,87,223,65,28,10,15
17,Louisiana,1953,611,564,152,110,98,269,42,10,23,9
12,Illinois,1684,487,530,83,65,96,222,137,15,16,18
24,Missouri,1555,422,476,159,26,91,227,72,37,9,24
2,Arizona,1721,419,455,211,35,96,210,123,87,15,55
0,Alabama,1730,404,433,137,38,113,306,46,27,17,63
41,Tennessee,1554,470,426,158,43,77,201,77,38,13,39
35,Oklahoma,1575,424,400,169,30,89,204,92,46,32,65
13,Indiana,1258,336,336,106,23,84,180,87,50,18,32
16,Kentucky,950,323,307,67,30,46,133,25,3,5,6
39,South Carolina,1316,499,281,81,36,54,198,79,17,7,61
48,Wisconsin,857,244,275,52,11,69,93,88,13,6,1
23,Mississippi,1073,390,265,48,24,52,151,58,5,13,33
3,Arkansas,976,319,264,65,25,48,100,63,52,14,16
29,New Jersey,1029,329,244,60,83,62,137,53,25,10,14
19,Maryland,1100,278,232,83,109,48,122,82,66,9,51
46,Washington,674,153,196,72,9,59,104,48,11,11,8
36,Oregon,642,136,189,87,7,29,81,37,14,7,10
20,Massachusetts,656,186,180,61,10,29,92,61,11,11,4
5,Colorado,854,164,178,136,1,61,151,79,39,15,29
27,Nevada,657,154,159,46,9,32,131,40,6,4,12
15,Kansas,471,131,136,51,2,29,67,31,9,8,3
47,West Virginia,394,156,104,26,6,17,59,11,3,2,7
14,Iowa,306,67,104,16,5,31,40,34,3,1,2
30,New Mexico,336,78,89,56,4,18,41,29,7,1,12
11,Idaho,290,76,73,24,4,13,44,39,5,5,4
22,Minnesota,245,51,72,33,1,10,45,27,4,1,1
6,Connecticut,491,117,69,69,11,27,99,80,5,6,7
7,Delaware,287,74,65,25,21,14,36,33,6,1,2
43,Utah,266,63,59,20,0,11,48,41,5,4,9
26,Nebraska,212,47,50,27,4,11,22,20,6,3,7
28,New Hampshire,127,27,47,12,3,7,14,12,5,0,0
25,Montana,169,34,46,26,2,10,26,19,3,1,2
10,Hawaii,176,33,46,17,4,8,25,28,4,2,7
40,South Dakota,140,35,34,18,1,14,13,17,1,4,3
1,Alaska,179,42,29,17,1,4,24,36,10,9,4
18,Maine,82,24,24,6,1,6,8,4,2,1,5
38,Rhode Island,115,27,21,3,5,5,11,27,5,3,1
49,Wyoming,113,42,18,15,1,9,16,9,2,1,0
44,Vermont,74,19,15,11,3,1,11,11,3,0,0
33,North Dakota,21,4,5,2,1,0,4,4,1,0,0

In [47]:
##States with top liver disease deaths, raw numbers.
state_death_df.sort_values(by=["Liver disease"], ascending = False)

,Jurisdiction,All causes,Heart disease,Cancer,Liver disease,AIDS-related,Respiratory disease,All other illnesses,Suicide,Drug/alcohol intoxication,Accident,Homicide
42,Texas,8050,2015,2039,816,173,632,1619,527,39,79,83
4,California,7026,1183,1728,656,116,512,1429,596,402,54,304
8,Florida,5660,1247,1654,419,310,366,994,197,186,69,158
37,Pennsylvania,2887,802,848,244,38,182,531,169,23,16,21
2,Arizona,1721,419,455,211,35,96,210,123,87,15,55
31,New York,2711,726,784,197,221,127,246,247,61,34,30
21,Michigan,2296,681,783,170,39,132,245,134,42,25,27
35,Oklahoma,1575,424,400,169,30,89,204,92,46,32,65
24,Missouri,1555,422,476,159,26,91,227,72,37,9,24
41,Tennessee,1554,470,426,158,43,77,201,77,38,13,39
45,Virginia,1676,450,565,157,55,87,223,65,28,10,15
17,Louisiana,1953,611,564,152,110,98,269,42,10,23,9
0,Alabama,1730,404,433,137,38,113,306,46,27,17,63
5,Colorado,854,164,178,136,1,61,151,79,39,15,29
32,North Carolina,1724,476,571,131,75,114,220,68,13,26,19
9,Georgia,2369,780,597,125,83,187,300,145,12,22,89
34,Ohio,2311,654,801,120,34,177,316,134,24,8,33
13,Indiana,1258,336,336,106,23,84,180,87,50,18,32
36,Oregon,642,136,189,87,7,29,81,37,14,7,10
19,Maryland,1100,278,232,83,109,48,122,82,66,9,51
12,Illinois,1684,487,530,83,65,96,222,137,15,16,18
39,South Carolina,1316,499,281,81,36,54,198,79,17,7,61
46,Washington,674,153,196,72,9,59,104,48,11,11,8
6,Connecticut,491,117,69,69,11,27,99,80,5,6,7
16,Kentucky,950,323,307,67,30,46,133,25,3,5,6
3,Arkansas,976,319,264,65,25,48,100,63,52,14,16
20,Massachusetts,656,186,180,61,10,29,92,61,11,11,4
29,New Jersey,1029,329,244,60,83,62,137,53,25,10,14
30,New Mexico,336,78,89,56,4,18,41,29,7,1,12
48,Wisconsin,857,244,275,52,11,69,93,88,13,6,1
15,Kansas,471,131,136,51,2,29,67,31,9,8,3
23,Mississippi,1073,390,265,48,24,52,151,58,5,13,33
27,Nevada,657,154,159,46,9,32,131,40,6,4,12
22,Minnesota,245,51,72,33,1,10,45,27,4,1,1
26,Nebraska,212,47,50,27,4,11,22,20,6,3,7
47,West Virginia,394,156,104,26,6,17,59,11,3,2,7
25,Montana,169,34,46,26,2,10,26,19,3,1,2
7,Delaware,287,74,65,25,21,14,36,33,6,1,2
11,Idaho,290,76,73,24,4,13,44,39,5,5,4
43,Utah,266,63,59,20,0,11,48,41,5,4,9
40,South Dakota,140,35,34,18,1,14,13,17,1,4,3
1,Alaska,179,42,29,17,1,4,24,36,10,9,4
10,Hawaii,176,33,46,17,4,8,25,28,4,2,7
14,Iowa,306,67,104,16,5,31,40,34,3,1,2
49,Wyoming,113,42,18,15,1,9,16,9,2,1,0
28,New Hampshire,127,27,47,12,3,7,14,12,5,0,0
44,Vermont,74,19,15,11,3,1,11,11,3,0,0
18,Maine,82,24,24,6,1,6,8,4,2,1,5
38,Rhode Island,115,27,21,3,5,5,11,27,5,3,1
33,North Dakota,21,4,5,2,1,0,4,4,1,0,0

In [146]:
##death rates by state and year
death_rate_state_df = pd.read_csv("death_rate__state.csv")

In [147]:
death_rate_state_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    52 non-null     object
 1   2001    52 non-null     int64
 2   2008    52 non-null     int64
 3   2009    52 non-null     int64
 4   2010    52 non-null     int64
 5   2011    52 non-null     int64
 6   2012    52 non-null     int64
 7   2013    52 non-null     int64
 8   2014    52 non-null     int64
 9   2015    52 non-null     int64
 10  2016    52 non-null     int64
 11  2017    52 non-null     int64
 12  2018    52 non-null     int64
dtypes: int64(12), object(1)
memory usage: 5.4+ KB

In [149]:
##Highest death rates by state for 2018
death_rate_state_df.sort_values(by=["2018"], ascending = False)

,Year,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
19,Louisiana,361,561,543,526,573,624,628,631,613,817,759,766
43,Tennessee,292,382,346,369,298,424,395,399,475,474,436,619
2,Alabama,352,296,294,241,388,321,399,390,444,497,531,588
49,West Virginia,500,388,356,394,447,450,456,409,473,441,490,583
25,Mississippi,238,302,302,316,305,260,436,383,322,474,568,572
41,South Carolina,318,350,207,304,246,265,306,315,372,388,541,539
22,Massachusetts,284,260,260,349,288,377,367,431,358,376,418,497
5,Arkansas,366,312,375,380,355,306,392,374,342,448,510,488
10,Florida,251,291,274,269,294,325,302,343,356,363,443,460
37,Oklahoma,235,372,328,248,358,324,343,404,392,353,315,415
18,Kentucky,336,446,380,290,429,423,329,363,502,354,583,381
39,Pennsylvania,324,298,327,293,316,313,314,295,340,354,383,358
47,Virginia,226,264,281,291,324,289,273,300,296,301,312,358
6,California,183,217,234,254,263,277,272,236,276,258,295,352
26,Missouri,199,289,265,288,239,228,292,304,328,305,289,349
23,Michigan,233,203,325,211,277,284,284,279,277,258,267,348
1,State,242,261,259,246,260,265,274,274,296,303,323,344
44,Texas,275,295,269,234,261,298,282,265,274,266,311,337
34,North Carolina,205,293,214,215,179,211,218,252,244,353,284,336
20,Maine,358,98,193,154,253,101,145,318,228,212,170,336
32,New Mexico,194,459,319,240,239,211,251,345,267,229,250,332
17,Kansas,245,281,231,243,268,179,291,220,262,363,268,332
45,Utah,121,214,324,239,227,283,427,433,331,466,403,327
4,Arizona,231,195,210,212,215,217,232,235,249,298,317,312
30,New Hampshire,83,175,309,153,413,195,305,184,301,346,197,312
11,Georgia,202,243,233,212,229,187,227,230,252,249,323,306
36,Ohio,256,198,236,224,218,248,240,215,264,255,289,299
21,Maryland,295,298,254,175,178,211,267,202,296,242,286,297
33,New York,259,221,243,220,212,213,266,235,223,290,289,295
9,Delaware,234,216,182,361,229,149,206,267,264,221,163,287
7,Colorado,243,164,216,211,169,236,198,171,256,293,209,275
13,Idaho,323,256,181,180,174,117,139,307,249,222,196,273
3,Alaska,175,280,128,242,193,174,157,190,286,228,206,260
15,Indiana,234,265,340,253,270,210,232,215,320,278,264,252
0,Federal,220,241,220,224,220,198,230,262,283,252,246,250
51,Wyoming,336,528,402,96,139,183,175,507,292,468,331,245
38,Oregon,219,229,248,281,291,184,205,214,252,322,171,231
50,Wisconsin,231,197,189,113,214,205,192,257,201,285,183,221
29,Nevada,274,272,278,336,280,294,274,347,355,301,349,217
8,Connecticut,171,161,153,113,106,140,115,143,144,113,103,212
14,Illinois,194,156,166,194,200,172,160,182,260,206,253,208
48,Washington,190,204,255,206,123,195,220,221,244,163,226,207
16,Iowa,113,241,157,137,132,229,184,170,214,320,177,201
40,Rhode Island,89,160,205,222,330,197,126,223,168,69,298,194
28,Nebraska,179,134,245,260,365,233,319,249,331,174,308,187
31,New Jersey,265,266,241,229,279,208,207,234,256,252,203,173
42,South Dakota,143,179,118,236,309,250,166,200,198,133,308,156
27,Montana,215,309,97,64,192,355,224,609,409,500,409,130
12,Hawaii,137,257,227,227,110,227,271,148,74,174,78,120
46,Vermont,214,142,135,241,0,98,385,303,229,403,300,117
24,Minnesota,203,188,126,170,204,149,213,146,115,189,63,64
35,North Dakota,276,0,0,71,72,212,63,0,0,244,126,0

In [48]:
state_unnatural_death_rate_df = pd.read_csv("state_unnatural_death_rate.csv")

In [49]:
state_unnatural_death_rate_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           11 non-null     int64
 1   Total          11 non-null     int64
 2   Male           11 non-null     int64
 3   Female         11 non-null     int64
 4   White          11 non-null     int64
 5   Black          11 non-null     int64
 6   Hispanic       11 non-null     int64
 7   Other          11 non-null     int64
 8   17 or younger  11 non-null     int64
 9   18-24          11 non-null     int64
 10  25-34          11 non-null     int64
 11  35-44          11 non-null     int64
 12  45-54          11 non-null     int64
 13  55 or older    11 non-null     int64
dtypes: int64(14)
memory usage: 1.3 KB

In [50]:
##Death rates by demographic and year
state_unnatural_death_rate_df.sort_values(by=["55 or older"], ascending = False)

,Year,Total,Male,Female,White,Black,Hispanic,Other,17 or younger,18-24,25-34,35-44,45-54,55 or older
10,2018,50,53,22,82,44,38,13,0,41,44,51,56,65
9,2017,42,43,19,70,34,30,12,0,36,35,45,43,55
6,2014,31,31,20,53,20,25,10,29,22,26,30,35,51
8,2016,36,37,23,63,26,26,12,37,30,30,38,39,48
4,2012,28,29,18,49,18,21,11,38,19,23,30,33,46
5,2013,29,29,17,50,18,23,10,23,19,24,31,32,46
7,2015,32,33,22,57,22,25,11,33,24,29,33,36,46
0,2008,26,27,15,43,15,21,13,41,18,23,27,30,40
3,2011,27,27,18,47,16,20,11,31,18,23,29,32,39
2,2010,26,26,16,44,16,20,11,41,19,23,27,30,38
1,2009,25,26,15,44,15,19,10,40,19,22,26,30,36

In [51]:
percent_death_illness_df = pd.read_csv("percent_deaths_illness.csv")

In [52]:
percent_death_illness_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 3 non-null      int64
 1   Cancer               3 non-null      float64
 2   Heart disease        3 non-null      float64
 3   Liver disease        3 non-null      float64
 4   Respiratory disease  3 non-null      float64
 5   AIDS-related         3 non-null      float64
 6   All other illnesses  3 non-null      float64
dtypes: float64(6), int64(1)
memory usage: 296.0 bytes

In [53]:
##Percent of deaht by illness for only three years available. Cancer and heart disease are the big ones.
percent_death_illness_df.head()

,Year,Cancer,Heart disease,Liver disease,Respiratory disease,AIDS-related,All other illnesses
0,2001,24.1,25.9,10.8,5.0,9.6,14.1
1,2010,28.7,25.7,8.9,6.6,2.3,16.5
2,2018,27.5,25.4,5.2,6.9,0.5,13.5

In [54]:
percent_death_illness_df.sort_values(by=["Cancer"], ascending = False)

,Year,Cancer,Heart disease,Liver disease,Respiratory disease,AIDS-related,All other illnesses
1,2010,28.7,25.7,8.9,6.6,2.3,16.5
2,2018,27.5,25.4,5.2,6.9,0.5,13.5
0,2001,24.1,25.9,10.8,5.0,9.6,14.1

In [55]:
death_rate_demo_df = pd.read_csv("death_rate_dem.csv")

In [56]:
death_rate_demo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           12 non-null     int64
 1   Total          12 non-null     int64
 2   Male           12 non-null     int64
 3   Female         12 non-null     int64
 4   White          12 non-null     int64
 5   Black          12 non-null     int64
 6   Hispanic       12 non-null     int64
 7   Other          12 non-null     int64
 8   17 or younger  12 non-null     int64
 9   18 to 24       12 non-null     int64
 10  25 to 34       12 non-null     int64
 11  35 to 44       12 non-null     int64
 12  45 to 54       12 non-null     int64
 13  55 or older    12 non-null     int64
dtypes: int64(14)
memory usage: 1.4 KB

In [57]:
death_rate_demo_df.head()

,Year,Total,Male,Female,White,Black,Hispanic,Other,17 or younger,18 to 24,25 to 34,35 to 44,45 to 54,55 or older
0,2001,242,250,131,345,234,139,59,68,39,64,181,584,2032
1,2008,261,267,173,413,230,147,67,115,34,51,131,442,1859
2,2009,259,266,163,412,243,134,49,0,35,48,136,427,1737
3,2010,246,255,128,396,233,129,47,140,35,50,114,389,1580
4,2011,260,267,160,461,222,121,45,111,26,47,123,384,1632

In [58]:
death_rate_demo_df.sort_values(by=["Black"], ascending = False)

,Year,Total,Male,Female,White,Black,Hispanic,Other,17 or younger,18 to 24,25 to 34,35 to 44,45 to 54,55 or older
11,2018,344,356,203,580,344,191,47,0,58,85,128,363,1606
10,2017,323,337,148,561,316,164,44,126,48,78,124,317,1624
9,2016,303,315,161,535,293,144,48,120,53,61,117,321,1579
8,2015,296,306,167,515,282,142,50,0,47,55,106,347,1618
7,2014,274,282,171,473,254,141,53,206,35,53,104,349,1563
6,2013,274,282,159,468,246,153,45,0,40,53,104,364,1619
5,2012,265,275,131,439,245,145,49,0,38,46,113,368,1615
2,2009,259,266,163,412,243,134,49,0,35,48,136,427,1737
0,2001,242,250,131,345,234,139,59,68,39,64,181,584,2032
3,2010,246,255,128,396,233,129,47,140,35,50,114,389,1580
1,2008,261,267,173,413,230,147,67,115,34,51,131,442,1859
4,2011,260,267,160,461,222,121,45,111,26,47,123,384,1632

In [59]:
death_rate_demo_df.sort_values(by=["White"], ascending = False)

,Year,Total,Male,Female,White,Black,Hispanic,Other,17 or younger,18 to 24,25 to 34,35 to 44,45 to 54,55 or older
11,2018,344,356,203,580,344,191,47,0,58,85,128,363,1606
10,2017,323,337,148,561,316,164,44,126,48,78,124,317,1624
9,2016,303,315,161,535,293,144,48,120,53,61,117,321,1579
8,2015,296,306,167,515,282,142,50,0,47,55,106,347,1618
7,2014,274,282,171,473,254,141,53,206,35,53,104,349,1563
6,2013,274,282,159,468,246,153,45,0,40,53,104,364,1619
4,2011,260,267,160,461,222,121,45,111,26,47,123,384,1632
5,2012,265,275,131,439,245,145,49,0,38,46,113,368,1615
1,2008,261,267,173,413,230,147,67,115,34,51,131,442,1859
2,2009,259,266,163,412,243,134,49,0,35,48,136,427,1737
3,2010,246,255,128,396,233,129,47,140,35,50,114,389,1580
0,2001,242,250,131,345,234,139,59,68,39,64,181,584,2032

In [60]:
##Death rates have gone down for older people, but stull the highest cohort.
death_rate_demo_df.sort_values(by=["55 or older"], ascending = False)

,Year,Total,Male,Female,White,Black,Hispanic,Other,17 or younger,18 to 24,25 to 34,35 to 44,45 to 54,55 or older
0,2001,242,250,131,345,234,139,59,68,39,64,181,584,2032
1,2008,261,267,173,413,230,147,67,115,34,51,131,442,1859
2,2009,259,266,163,412,243,134,49,0,35,48,136,427,1737
4,2011,260,267,160,461,222,121,45,111,26,47,123,384,1632
10,2017,323,337,148,561,316,164,44,126,48,78,124,317,1624
6,2013,274,282,159,468,246,153,45,0,40,53,104,364,1619
8,2015,296,306,167,515,282,142,50,0,47,55,106,347,1618
5,2012,265,275,131,439,245,145,49,0,38,46,113,368,1615
11,2018,344,356,203,580,344,191,47,0,58,85,128,363,1606
3,2010,246,255,128,396,233,129,47,140,35,50,114,389,1580
9,2016,303,315,161,535,293,144,48,120,53,61,117,321,1579
7,2014,274,282,171,473,254,141,53,206,35,53,104,349,1563

In [61]:
average_yearly_mortality_rate_demo_df = pd.read_csv("average_yearly_mortality_rate_dem.csv")

In [62]:
average_yearly_mortality_rate_demo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     11 non-null     object
 1   Total          11 non-null     int64
 2   Male           11 non-null     int64
 3   Female         11 non-null     int64
 4   White          11 non-null     int64
 5   Black          11 non-null     int64
 6   Hispanic       11 non-null     int64
 7   Other          11 non-null     int64
 8   17 or younger  11 non-null     int64
 9   18 to 24       11 non-null     int64
 10  25 to 34       11 non-null     int64
 11  35 to 44       11 non-null     int64
 12  45 to 54       11 non-null     int64
 13  55 or older    11 non-null     object
dtypes: int64(12), object(2)
memory usage: 1.3+ KB

In [63]:
##Changing column name
average_yearly_mortality_rate_demo_df = average_yearly_mortality_rate_demo_df.rename(columns={"Unnamed: 0": "Cause"})
average_yearly_mortality_rate_demo_df

,Cause,Total,Male,Female,White,Black,Hispanic,Other,17 or younger,18 to 24,25 to 34,35 to 44,45 to 54,55 or older
0,All causes,269,278,156,432,252,142,53,67,37,58,138,419,"1,704"
1,Heart disease,70,73,33,114,70,26,11,6,4,10,32,99,509
2,Cancer,74,76,40,125,69,31,12,12,2,5,22,115,581
3,Liver disease,24,25,12,41,15,22,6,3,0,1,10,60,131
4,AIDS-related,9,9,6,6,15,4,1,0,1,3,12,17,15
5,Respiratory disease,17,17,12,30,14,8,2,3,2,3,6,20,133
6,All other illnesses,42,43,33,60,43,26,8,3,4,7,21,68,271
7,Suicide,17,17,13,31,10,13,8,33,15,17,18,18,18
8,Drug/alcohol,5,6,3,9,4,5,2,0,2,4,6,8,8
9,Accident,3,3,1,5,2,2,1,3,1,1,2,3,10
10,Homicide,6,6,0,8,5,5,2,3,4,5,5,6,10

In [64]:
##Cancer and heart disease tops for older prisoners. All other a big category. Resp and liver high, too.
average_yearly_mortality_rate_demo_df.sort_values(by=["55 or older"], ascending = False)

,Cause,Total,Male,Female,White,Black,Hispanic,Other,17 or younger,18 to 24,25 to 34,35 to 44,45 to 54,55 or older
8,Drug/alcohol,5,6,3,9,4,5,2,0,2,4,6,8,8
2,Cancer,74,76,40,125,69,31,12,12,2,5,22,115,581
1,Heart disease,70,73,33,114,70,26,11,6,4,10,32,99,509
6,All other illnesses,42,43,33,60,43,26,8,3,4,7,21,68,271
7,Suicide,17,17,13,31,10,13,8,33,15,17,18,18,18
4,AIDS-related,9,9,6,6,15,4,1,0,1,3,12,17,15
5,Respiratory disease,17,17,12,30,14,8,2,3,2,3,6,20,133
3,Liver disease,24,25,12,41,15,22,6,3,0,1,10,60,131
9,Accident,3,3,1,5,2,2,1,3,1,1,2,3,10
10,Homicide,6,6,0,8,5,5,2,3,4,5,5,6,10
0,All causes,269,278,156,432,252,142,53,67,37,58,138,419,"1,704"

In [65]:
average_yearly_mortality_rate_demo_df["55 or older"] = average_yearly_mortality_rate_demo_df["55 or older"].str.replace(',','')

In [66]:
average_yearly_mortality_rate_demo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Cause          11 non-null     object
 1   Total          11 non-null     int64
 2   Male           11 non-null     int64
 3   Female         11 non-null     int64
 4   White          11 non-null     int64
 5   Black          11 non-null     int64
 6   Hispanic       11 non-null     int64
 7   Other          11 non-null     int64
 8   17 or younger  11 non-null     int64
 9   18 to 24       11 non-null     int64
 10  25 to 34       11 non-null     int64
 11  35 to 44       11 non-null     int64
 12  45 to 54       11 non-null     int64
 13  55 or older    11 non-null     object
dtypes: int64(12), object(2)
memory usage: 1.3+ KB

In [67]:
average_yearly_mortality_rate_demo_df[list(average_yearly_mortality_rate_demo_df.columns)[13]] = \
average_yearly_mortality_rate_demo_df[list(average_yearly_mortality_rate_demo_df.columns)[13]].apply(pd.to_numeric, errors="coerce")

In [68]:
average_yearly_mortality_rate_demo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Cause          11 non-null     object
 1   Total          11 non-null     int64
 2   Male           11 non-null     int64
 3   Female         11 non-null     int64
 4   White          11 non-null     int64
 5   Black          11 non-null     int64
 6   Hispanic       11 non-null     int64
 7   Other          11 non-null     int64
 8   17 or younger  11 non-null     int64
 9   18 to 24       11 non-null     int64
 10  25 to 34       11 non-null     int64
 11  35 to 44       11 non-null     int64
 12  45 to 54       11 non-null     int64
 13  55 or older    11 non-null     int64
dtypes: int64(13), object(1)
memory usage: 1.3+ KB

In [69]:
average_yearly_mortality_rate_demo_df.sort_values(by=["55 or older"], ascending = False)

,Cause,Total,Male,Female,White,Black,Hispanic,Other,17 or younger,18 to 24,25 to 34,35 to 44,45 to 54,55 or older
0,All causes,269,278,156,432,252,142,53,67,37,58,138,419,1704
2,Cancer,74,76,40,125,69,31,12,12,2,5,22,115,581
1,Heart disease,70,73,33,114,70,26,11,6,4,10,32,99,509
6,All other illnesses,42,43,33,60,43,26,8,3,4,7,21,68,271
5,Respiratory disease,17,17,12,30,14,8,2,3,2,3,6,20,133
3,Liver disease,24,25,12,41,15,22,6,3,0,1,10,60,131
7,Suicide,17,17,13,31,10,13,8,33,15,17,18,18,18
4,AIDS-related,9,9,6,6,15,4,1,0,1,3,12,17,15
9,Accident,3,3,1,5,2,2,1,3,1,1,2,3,10
10,Homicide,6,6,0,8,5,5,2,3,4,5,5,6,10
8,Drug/alcohol,5,6,3,9,4,5,2,0,2,4,6,8,8

In [70]:
state_heart_deaths_demo_df = pd.read_csv("state_heart_deaths_demo.csv")

In [71]:
state_heart_deaths_demo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           11 non-null     int64
 1   Total          11 non-null     int64
 2   Male           11 non-null     int64
 3   Female         11 non-null     int64
 4   White          11 non-null     int64
 5   Black          11 non-null     int64
 6   Hispanic       11 non-null     int64
 7   Other          11 non-null     int64
 8   17 or younger  11 non-null     int64
 9   18 to 24       11 non-null     int64
 10  25 to 34       11 non-null     int64
 11  35 to 44       11 non-null     int64
 12  45to 54        11 non-null     int64
 13  55 or older    11 non-null     int64
dtypes: int64(14)
memory usage: 1.3 KB

In [72]:
##Heart disease death rates gotten better with time, but still high.
state_heart_deaths_demo_df.sort_values(by=["55 or older"], ascending = False)

,Year,Total,Male,Female,White,Black,Hispanic,Other,17 or younger,18 to 24,25 to 34,35 to 44,45to 54,55 or older
0,2008,64,67,33,99,62,30,12,0,4,8,31,106,550
1,2009,64,66,37,99,63,29,12,0,4,8,31,98,526
9,2017,84,88,39,147,92,27,9,0,4,10,26,85,490
2,2010,64,66,30,101,64,28,10,14,4,8,32,94,488
10,2018,87,91,37,151,95,31,10,0,5,11,26,85,484
8,2016,78,81,37,136,82,25,11,37,5,10,24,83,472
3,2011,65,67,30,107,65,25,8,16,4,8,33,90,468
7,2015,73,76,35,127,76,26,12,33,7,9,24,81,467
5,2013,67,69,31,114,67,24,11,0,5,7,28,82,455
6,2014,68,71,31,117,69,24,13,29,5,8,25,80,450
4,2012,64,67,27,107,66,23,9,19,3,7,30,86,448

In [73]:
raw_death_rate_demo_df = pd.read_csv("raw_death_rate_dem.csv", encoding = "unicode_escape")

In [74]:
raw_death_rate_demo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 15 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Unnamed: 0                                                      11 non-null     object
 1   Total                                                           11 non-null     int64
 2   Male                                                            11 non-null     int64
 3   Female                                                          11 non-null     int64
 4   White                                                           11 non-null     int64
 5   Black                                                           11 non-null     int64
 6   Hispanic                                                        11 non-null     int64
 7   American Indian/Alaska Native                                   11 non-null     int64
 8   Asian/Native Hawaiian/Other Pacific Islander/two or more races  11 non-null     int64
 9   17 or younger                                                   11 non-null     int64
 10  18 to 24                                                        11 non-null     int64
 11  25 to 34                                                        11 non-null     int64
 12  35 to 44                                                        11 non-null     int64
 13  45 to 54                                                        11 non-null     int64
 14  55 or older                                                     11 non-null     int64
dtypes: int64(14), object(1)
memory usage: 1.4+ KB

In [75]:
raw_death_rate_demo_df = raw_death_rate_demo_df.rename(columns={"Unnamed: 0": "Cause"})

In [76]:
##Raw death numbers by demo
raw_death_rate_demo_df.head()

,Cause,Total,Male,Female,White,Black,Hispanic,American Indian/Alaska Native,Asian/Native Hawaiian/Other Pacific Islander/two or more races,17 or younger,18 to 24,25 to 34,35 to 44,45 to 54,55 or older
0,All causes,61130,58651,2476,32102,21076,6703,646,504,22,1207,4344,8566,16380,30584
1,Heart disease,15855,15324,531,8473,5887,1242,142,94,2,143,716,1970,3875,9145
2,Cancer,16777,16143,634,9262,5784,1447,141,118,4,72,376,1384,4508,10429
3,Liver disease,5432,5242,190,3025,1219,1044,99,35,1,15,87,636,2345,2345
4,AIDS-related,1932,1834,98,437,1272,203,11,8,0,19,247,743,656,267

In [77]:
raw_death_rate_demo_df.sort_values(by=["55 or older"], ascending = False)

,Cause,Total,Male,Female,White,Black,Hispanic,American Indian/Alaska Native,Asian/Native Hawaiian/Other Pacific Islander/two or more races,17 or younger,18 to 24,25 to 34,35 to 44,45 to 54,55 or older
0,All causes,61130,58651,2476,32102,21076,6703,646,504,22,1207,4344,8566,16380,30584
2,Cancer,16777,16143,634,9262,5784,1447,141,118,4,72,376,1384,4508,10429
1,Heart disease,15855,15324,531,8473,5887,1242,142,94,2,143,716,1970,3875,9145
6,All other illnesses,9535,9016,518,4489,3641,1215,93,80,1,138,553,1313,2662,4864
5,Respiratory disease,3824,3631,193,2203,1211,356,27,21,1,62,203,400,768,2389
3,Liver disease,5432,5242,190,3025,1219,1044,99,35,1,15,87,636,2345,2345
7,Suicide,3870,3663,207,2268,809,615,67,96,11,486,1243,1098,705,325
4,AIDS-related,1932,1834,98,437,1272,203,11,8,0,19,247,743,656,267
9,Accident,618,599,19,351,170,79,11,5,1,41,106,151,131,187
10,Homicide,1258,1251,7,561,447,213,13,22,1,140,371,322,238,185
8,Drug/alcohol intoxication,1235,1191,44,639,306,237,35,17,0,67,323,394,305,146

In [78]:
raw_death_rate_demo_df.sort_values(by=["25 to 34"], ascending = False)

,Cause,Total,Male,Female,White,Black,Hispanic,American Indian/Alaska Native,Asian/Native Hawaiian/Other Pacific Islander/two or more races,17 or younger,18 to 24,25 to 34,35 to 44,45 to 54,55 or older
0,All causes,61130,58651,2476,32102,21076,6703,646,504,22,1207,4344,8566,16380,30584
7,Suicide,3870,3663,207,2268,809,615,67,96,11,486,1243,1098,705,325
1,Heart disease,15855,15324,531,8473,5887,1242,142,94,2,143,716,1970,3875,9145
6,All other illnesses,9535,9016,518,4489,3641,1215,93,80,1,138,553,1313,2662,4864
2,Cancer,16777,16143,634,9262,5784,1447,141,118,4,72,376,1384,4508,10429
10,Homicide,1258,1251,7,561,447,213,13,22,1,140,371,322,238,185
8,Drug/alcohol intoxication,1235,1191,44,639,306,237,35,17,0,67,323,394,305,146
4,AIDS-related,1932,1834,98,437,1272,203,11,8,0,19,247,743,656,267
5,Respiratory disease,3824,3631,193,2203,1211,356,27,21,1,62,203,400,768,2389
9,Accident,618,599,19,351,170,79,11,5,1,41,106,151,131,187
3,Liver disease,5432,5242,190,3025,1219,1044,99,35,1,15,87,636,2345,2345

In [79]:
death_rate_state_fed_df = pd.read_csv("deaths_state_fed_rate.csv")

In [80]:
death_rate_state_fed_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    52 non-null     object
 1   2001    52 non-null     int64
 2   2008    52 non-null     int64
 3   2009    52 non-null     int64
 4   2010    52 non-null     int64
 5   2011    52 non-null     int64
 6   2012    52 non-null     int64
 7   2013    52 non-null     int64
 8   2014    52 non-null     int64
 9   2015    52 non-null     int64
 10  2016    52 non-null     int64
 11  2017    52 non-null     int64
 12  2018    52 non-null     int64
dtypes: int64(12), object(1)
memory usage: 5.4+ KB

In [81]:
death_rate_state_fed_df.max()

Year    Wyoming
2001       2869
2008       3452
2009       3417
2010       3233
2011       3351
2012       3357
2013       3478
2014       3484
2015       3682
2016       3729
2017       3943
2018       4135
dtype: object

In [82]:
death_rate_state_fed_df = death_rate_state_fed_df.rename(columns={"Year": "Jurisdiction"})

In [83]:
##Death rate by state and year. NY with big decrease. Southern states with big increases.
death_rate_state_fed_df.sort_values(by=["2018"], ascending = False)

,Jurisdiction,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
1,State,2869,3452,3417,3233,3351,3357,3478,3484,3682,3729,3943,4135
44,Texas,408,469,426,375,417,462,438,409,418,403,469,505
6,California,287,371,395,414,388,368,365,317,353,334,384,449
10,Florida,182,291,278,275,297,324,305,346,354,356,428,440
0,Federal,301,399,376,387,387,350,400,444,455,388,381,378
39,Pennsylvania,122,145,165,141,157,157,157,145,166,171,181,166
11,Georgia,93,128,125,112,121,103,122,121,131,133,173,163
36,Ohio,115,101,120,116,111,126,124,111,138,133,149,151
33,New York,175,133,142,124,117,115,142,123,115,147,143,138
23,Michigan,114,99,148,93,119,124,124,121,118,106,106,135
4,Arizona,64,77,85,85,86,87,95,99,105,126,133,131
2,Alabama,87,75,80,66,104,86,107,102,112,118,116,125
43,Tennessee,51,74,69,74,59,84,82,83,94,102,96,121
34,North Carolina,66,117,86,87,71,79,81,94,90,127,104,118
19,Louisiana,71,117,108,100,108,116,118,118,113,123,115,114
37,Oklahoma,51,88,79,60,85,79,87,107,107,93,86,113
47,Virginia,71,86,87,93,99,86,82,90,90,90,93,106
26,Missouri,57,87,81,88,74,71,92,97,106,99,94,106
41,South Carolina,69,83,49,70,55,58,66,66,76,79,105,100
14,Illinois,86,71,75,94,97,85,78,88,120,90,104,83
5,Arkansas,42,41,50,54,50,43,56,57,54,71,81,76
25,Mississippi,36,54,52,52,47,41,68,50,45,65,77,76
15,Indiana,46,70,91,69,74,59,66,70,85,70,68,67
21,Maryland,70,69,56,40,41,46,58,43,62,49,57,57
7,Colorado,42,38,49,48,37,48,40,35,51,57,41,55
50,Wisconsin,48,44,42,25,48,46,43,58,46,66,43,52
18,Kentucky,36,68,57,42,60,55,40,44,60,42,70,50
22,Massachusetts,29,29,29,39,33,42,39,45,34,34,37,42
48,Washington,29,35,44,35,21,33,39,38,42,28,40,36
49,West Virginia,17,19,18,20,23,24,26,24,28,26,29,34
38,Oregon,24,31,34,39,40,26,30,31,37,47,25,34
17,Kansas,21,24,20,22,25,17,28,21,25,35,26,33
31,New Jersey,69,66,58,56,66,48,46,50,52,49,39,33
29,Nevada,27,35,35,41,34,37,35,44,47,42,47,29
8,Connecticut,30,32,29,21,19,24,20,24,23,17,14,28
32,New Mexico,11,29,21,16,16,14,17,24,19,16,18,22
13,Idaho,17,18,13,13,13,9,10,23,18,16,15,22
16,Iowa,9,21,14,13,12,20,16,15,19,29,16,19
45,Utah,5,11,17,13,12,15,23,23,16,21,20,17
9,Delaware,16,15,12,23,15,10,14,18,17,14,10,16
3,Alaska,8,14,7,13,12,11,8,12,15,10,9,11
28,Nebraska,7,6,11,12,17,11,16,13,17,9,16,10
30,New Hampshire,2,5,9,4,10,5,8,5,8,9,5,8
20,Maine,6,2,4,3,5,2,3,7,5,5,4,8
51,Wyoming,5,9,7,2,3,4,4,12,7,11,8,6
42,South Dakota,4,6,4,8,11,9,6,7,7,5,12,6
12,Hawaii,7,14,11,12,6,12,14,8,4,9,4,6
24,Minnesota,13,17,12,16,19,14,20,14,11,18,6,6
40,Rhode Island,3,6,7,7,10,6,4,7,5,2,8,5
27,Montana,6,9,3,2,6,11,7,19,13,16,13,5
46,Vermont,3,3,3,5,0,2,8,6,4,7,4,2
35,North Dakota,3,0,0,1,1,3,1,0,0,4,2,0

In [84]:
##Highest death rates in 2001.
death_rate_state_fed_df.sort_values(by=["2001"], ascending = False)

,Jurisdiction,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
1,State,2869,3452,3417,3233,3351,3357,3478,3484,3682,3729,3943,4135
44,Texas,408,469,426,375,417,462,438,409,418,403,469,505
0,Federal,301,399,376,387,387,350,400,444,455,388,381,378
6,California,287,371,395,414,388,368,365,317,353,334,384,449
10,Florida,182,291,278,275,297,324,305,346,354,356,428,440
33,New York,175,133,142,124,117,115,142,123,115,147,143,138
39,Pennsylvania,122,145,165,141,157,157,157,145,166,171,181,166
36,Ohio,115,101,120,116,111,126,124,111,138,133,149,151
23,Michigan,114,99,148,93,119,124,124,121,118,106,106,135
11,Georgia,93,128,125,112,121,103,122,121,131,133,173,163
2,Alabama,87,75,80,66,104,86,107,102,112,118,116,125
14,Illinois,86,71,75,94,97,85,78,88,120,90,104,83
19,Louisiana,71,117,108,100,108,116,118,118,113,123,115,114
47,Virginia,71,86,87,93,99,86,82,90,90,90,93,106
21,Maryland,70,69,56,40,41,46,58,43,62,49,57,57
41,South Carolina,69,83,49,70,55,58,66,66,76,79,105,100
31,New Jersey,69,66,58,56,66,48,46,50,52,49,39,33
34,North Carolina,66,117,86,87,71,79,81,94,90,127,104,118
4,Arizona,64,77,85,85,86,87,95,99,105,126,133,131
26,Missouri,57,87,81,88,74,71,92,97,106,99,94,106
37,Oklahoma,51,88,79,60,85,79,87,107,107,93,86,113
43,Tennessee,51,74,69,74,59,84,82,83,94,102,96,121
50,Wisconsin,48,44,42,25,48,46,43,58,46,66,43,52
15,Indiana,46,70,91,69,74,59,66,70,85,70,68,67
7,Colorado,42,38,49,48,37,48,40,35,51,57,41,55
5,Arkansas,42,41,50,54,50,43,56,57,54,71,81,76
25,Mississippi,36,54,52,52,47,41,68,50,45,65,77,76
18,Kentucky,36,68,57,42,60,55,40,44,60,42,70,50
8,Connecticut,30,32,29,21,19,24,20,24,23,17,14,28
22,Massachusetts,29,29,29,39,33,42,39,45,34,34,37,42
48,Washington,29,35,44,35,21,33,39,38,42,28,40,36
29,Nevada,27,35,35,41,34,37,35,44,47,42,47,29
38,Oregon,24,31,34,39,40,26,30,31,37,47,25,34
17,Kansas,21,24,20,22,25,17,28,21,25,35,26,33
49,West Virginia,17,19,18,20,23,24,26,24,28,26,29,34
13,Idaho,17,18,13,13,13,9,10,23,18,16,15,22
9,Delaware,16,15,12,23,15,10,14,18,17,14,10,16
24,Minnesota,13,17,12,16,19,14,20,14,11,18,6,6
32,New Mexico,11,29,21,16,16,14,17,24,19,16,18,22
16,Iowa,9,21,14,13,12,20,16,15,19,29,16,19
3,Alaska,8,14,7,13,12,11,8,12,15,10,9,11
28,Nebraska,7,6,11,12,17,11,16,13,17,9,16,10
12,Hawaii,7,14,11,12,6,12,14,8,4,9,4,6
20,Maine,6,2,4,3,5,2,3,7,5,5,4,8
27,Montana,6,9,3,2,6,11,7,19,13,16,13,5
45,Utah,5,11,17,13,12,15,23,23,16,21,20,17
51,Wyoming,5,9,7,2,3,4,4,12,7,11,8,6
42,South Dakota,4,6,4,8,11,9,6,7,7,5,12,6
46,Vermont,3,3,3,5,0,2,8,6,4,7,4,2
40,Rhode Island,3,6,7,7,10,6,4,7,5,2,8,5
35,North Dakota,3,0,0,1,1,3,1,0,0,4,2,0
30,New Hampshire,2,5,9,4,10,5,8,5,8,9,5,8

In [85]:
raw_total_deaths_state_fed_df = pd.read_csv("raw-deaths_state_fed.csv")

In [86]:
raw_total_deaths_state_fed_df = raw_total_deaths_state_fed_df.rename(columns={"Unnamed: 0": "Jurisdiction"})

In [87]:
raw_total_deaths_state_fed_df

,Jurisdiction,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Federal,301,399,376,387,387,350,400,444,455,388,381,378
1,State,2869,3452,3417,3233,3351,3357,3478,3484,3682,3729,3943,4135
2,Alabama,87,75,80,66,104,86,107,102,112,118,116,125
3,Alaska/c,8,14,7,13,12,11,8,12,15,10,9,11
4,Arizona,64,77,85,85,86,87,95,99,105,126,133,131
5,Arkansas,42,41,50,54,50,43,56,57,54,71,81,76
6,California,287,371,395,414,388,368,365,317,353,334,384,449
7,Colorado,42,38,49,48,37,48,40,35,51,57,41,55
8,Connecticut/d,30,32,29,21,19,24,20,24,23,17,14,28
9,Delaware/d,16,15,12,23,15,10,14,18,17,14,10,16
10,Florida,182,291,278,275,297,324,305,346,354,356,428,440
11,Georgia,93,128,125,112,121,103,122,121,131,133,173,163
12,Hawaii/d,7,14,11,12,6,12,14,8,4,9,4,6
13,Idaho,17,18,13,13,13,9,10,23,18,16,15,22
14,Illinois,86,71,75,94,97,85,78,88,120,90,104,83
15,Indiana,46,70,91,69,74,59,66,70,85,70,68,67
16,Iowa,9,21,14,13,12,20,16,15,19,29,16,19
17,Kansas,21,24,20,22,25,17,28,21,25,35,26,33
18,Kentucky,36,68,57,42,60,55,40,44,60,42,70,50
19,Louisiana,71,117,108,100,108,116,118,118,113,123,115,114
20,Maine,6,2,4,3,5,2,3,7,5,5,4,8
21,Maryland,70,69,56,40,41,46,58,43,62,49,57,57
22,Massachusetts,29,29,29,39,33,42,39,45,34,34,37,42
23,Michigan,114,99,148,93,119,124,124,121,118,106,106,135
24,Minnesota,13,17,12,16,19,14,20,14,11,18,6,6
25,Mississippi,36,54,52,52,47,41,68,50,45,65,77,76
26,Missouri,57,87,81,88,74,71,92,97,106,99,94,106
27,Montana,6,9,3,2,6,11,7,19,13,16,13,5
28,Nebraska,7,6,11,12,17,11,16,13,17,9,16,10
29,Nevada,27,35,35,41,34,37,35,44,47,42,47,29
30,New Hampshire,2,5,9,4,10,5,8,5,8,9,5,8
31,New Jersey,69,66,58,56,66,48,46,50,52,49,39,33
32,New Mexico,11,29,21,16,16,14,17,24,19,16,18,22
33,New York,175,133,142,124,117,115,142,123,115,147,143,138
34,North Carolina,66,117,86,87,71,79,81,94,90,127,104,118
35,North Dakota,3,0,0,1,1,3,1,0,0,4,2,0
36,Ohio,115,101,120,116,111,126,124,111,138,133,149,151
37,Oklahoma,51,88,79,60,85,79,87,107,107,93,86,113
38,Oregon,24,31,34,39,40,26,30,31,37,47,25,34
39,Pennsylvania,122,145,165,141,157,157,157,145,166,171,181,166
40,Rhode Island/d,3,6,7,7,10,6,4,7,5,2,8,5
41,South Carolina,69,83,49,70,55,58,66,66,76,79,105,100
42,South Dakota,4,6,4,8,11,9,6,7,7,5,12,6
43,Tennessee,51,74,69,74,59,84,82,83,94,102,96,121
44,Texas,408,469,426,375,417,462,438,409,418,403,469,505
45,Utah,5,11,17,13,12,15,23,23,16,21,20,17
46,Vermont/d,3,3,3,5,0,2,8,6,4,7,4,2
47,Virginia,71,86,87,93,99,86,82,90,90,90,93,106
48,Washington,29,35,44,35,21,33,39,38,42,28,40,36
49,West Virginia,17,19,18,20,23,24,26,24,28,26,29,34
50,Wisconsin,48,44,42,25,48,46,43,58,46,66,43,52
51,Wyoming,5,9,7,2,3,4,4,12,7,11,8,6

In [88]:
raw_total_deaths_state_fed_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Jurisdiction  52 non-null     object
 1   2001          52 non-null     int64
 2   2008          52 non-null     int64
 3   2009          52 non-null     int64
 4   2010          52 non-null     int64
 5   2011          52 non-null     int64
 6   2012          52 non-null     int64
 7   2013          52 non-null     int64
 8   2014          52 non-null     int64
 9   2015          52 non-null     int64
 10  2016          52 non-null     int64
 11  2017          52 non-null     int64
 12  2018          52 non-null     int64
dtypes: int64(12), object(1)
memory usage: 5.4+ KB

In [89]:
percent_state_death_cause_df = pd.read_csv("percent_state_cause_of_death.csv")

In [90]:
percent_state_death_cause_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    14 non-null     object
 1   2001    14 non-null     float64
 2   2002    14 non-null     float64
 3   2003    14 non-null     float64
 4   2004    14 non-null     float64
 5   2005    14 non-null     float64
 6   2006    14 non-null     float64
 7   2007    14 non-null     float64
 8   2008    14 non-null     float64
 9   2009    14 non-null     float64
 10  2010    14 non-null     float64
 11  2011    14 non-null     float64
 12  2012    14 non-null     float64
 13  2013    14 non-null     float64
 14  2014    14 non-null     float64
 15  2015    14 non-null     float64
 16  2016    14 non-null     float64
 17  2017    14 non-null     float64
 18  2018    14 non-null     float64
 19  2019    14 non-null     float64
dtypes: float64(19), object(1)
memory usage: 2.3+ KB

In [91]:
percent_state_death_cause_df = percent_state_death_cause_df.rename(columns={"Year": "Cause"})

In [92]:
##Percent of death causes by year. Suicide and drugs have gone up. AIDS down. Liver disease down.
percent_state_death_cause_df.sort_values(by=["2019"], ascending = False)

,Cause,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,All causes,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
1,Ilnesss,89.5,89.1,89.8,89.1,88.9,87.5,87.9,87.9,88.6,88.6,88.9,88.1,88.6,87.0,87.7,85.8,82.8,79.3,78.9
3,Cancer,24.1,23.2,25.7,23.5,25.4,24.9,22.8,26.3,28.6,28.7,30.7,30.5,30.6,30.1,30.3,30.3,28.1,27.5,28.1
2,Heart disease,25.9,27.4,25.4,27.0,26.4,26.4,24.8,24.5,24.9,25.7,25.5,23.9,25.8,25.7,26.8,27.6,27.8,25.5,26.9
7,All other illnesses,14.1,14.7,16.0,18.5,15.5,16.7,21.4,17.8,16.7,16.5,14.8,15.8,14.8,13.5,14.6,14.2,13.3,13.6,13.8
8,Suicide,5.9,5.7,6.3,6.4,6.7,6.8,6.3,5.7,5.9,6.7,5.5,6.1,5.5,7.1,5.9,6.8,6.6,7.5,8.1
9,Drug/alcohol intoxication,1.2,1.3,0.7,0.7,1.2,1.7,1.2,1.7,1.5,1.3,1.7,1.0,1.6,1.4,2.2,2.8,5.1,6.1,6.6
6,Respiratory disease,5.1,5.6,6.3,6.4,6.7,6.1,6.1,7.3,5.9,6.6,6.1,6.6,5.7,6.8,6.6,5.9,6.4,7.0,6.1
4,Liver disease,10.7,10.1,9.7,9.1,10.0,9.4,9.3,9.2,9.7,8.9,10.1,9.1,10.2,9.0,8.2,7.0,6.2,5.2,3.7
11,Homicide,1.4,1.6,1.6,1.6,1.8,1.7,1.7,1.2,1.6,2.2,2.1,2.5,2.6,2.4,2.2,2.6,2.9,3.0,3.7
13,Missing/unknown,1.3,1.3,0.0,0.0,0.0,0.0,1.5,0.0,1.0,0.1,0.3,0.3,0.2,0.6,0.4,0.3,0.8,2.1,1.1
10,Accident,0.8,1.0,0.8,1.1,0.9,1.0,0.8,0.8,0.9,1.0,1.1,1.5,1.0,1.1,1.1,1.1,1.1,1.0,0.8
12,Other causes,0.0,0.0,0.8,1.2,0.5,1.3,0.5,2.8,0.5,0.2,0.4,0.4,0.5,0.3,0.5,0.6,0.7,0.9,0.7
5,AIDS-related,9.6,8.2,6.6,4.7,4.9,4.1,3.5,2.9,2.9,2.3,1.7,2.2,1.5,1.8,1.2,0.8,0.9,0.5,0.4

In [93]:
state_illness_death_rate_demo_df = pd.read_csv("state_illness_death_rate_demo.csv", encoding = "unicode_escape")

In [94]:
state_illness_death_rate_demo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    13 non-null     object
 1   2008    13 non-null     int64
 2   2009    13 non-null     int64
 3   2010    13 non-null     int64
 4   2011    13 non-null     int64
 5   2012    13 non-null     int64
 6   2013    13 non-null     int64
 7   2014    13 non-null     int64
 8   2015    13 non-null     int64
 9   2016    13 non-null     int64
 10  2017    13 non-null     int64
 11  2018    13 non-null     int64
dtypes: int64(11), object(1)
memory usage: 1.3+ KB

In [95]:
state_illness_death_rate_demo_df = state_illness_death_rate_demo_df.rename(columns={"Year": "Demographic"})

In [96]:
##Death rate for white prisoners has gone up a lot.
state_illness_death_rate_demo_df.sort_values(by=["2018"], ascending = False)

,Demographic,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
12,55 or older,1777,1765,1658,1598,1558,1567,1538,1544,1530,1540,1517
3,White,337,353,356,372,381,403,404,425,439,460,466
1,Male,231,235,232,233,235,243,246,255,261,272,276
11,4554,416,397,382,364,346,338,324,315,298,281,271
0,Total,225,228,226,226,227,236,238,247,253,262,267
4,Black,213,218,216,215,213,217,225,236,248,259,266
2,Female,136,144,137,132,122,132,133,143,142,138,145
5,Hispanic,122,119,115,107,110,116,120,120,115,119,126
7,17 or younger,27,13,41,47,56,23,29,33,73,79,89
10,3544,110,106,98,94,85,81,75,71,70,69,68
6,Other,49,46,42,35,36,36,39,39,38,35,32
9,2534,29,26,25,25,24,24,23,24,24,27,27
8,1824,14,15,15,14,14,15,15,16,14,13,10

In [97]:
raw_state_fed_death_cause_df = pd.read_csv("raw_state_fed_cause_of_death.csv")

In [98]:
raw_state_fed_death_cause_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    16 non-null     object
 1   2001    16 non-null     float64
 2   2008    16 non-null     float64
 3   2009    16 non-null     float64
 4   2010    16 non-null     float64
 5   2011    16 non-null     float64
 6   2012    16 non-null     float64
 7   2013    16 non-null     float64
 8   2014    16 non-null     float64
 9   2015    16 non-null     float64
 10  2016    16 non-null     float64
 11  2017    16 non-null     float64
 12  2018    16 non-null     float64
dtypes: float64(12), object(1)
memory usage: 1.9+ KB

In [99]:
raw_state_fed_death_cause_df = raw_state_fed_death_cause_df.rename(columns={"Year": "Cause"})

In [100]:
##Death rates cause of death over time.
raw_state_fed_death_cause_df.sort_values(by=["2018"], ascending = False)

,Cause,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Total,3170.0,3851.0,3793.0,3620.0,3738.0,3707.0,3878.0,3928.0,4137.0,4117.0,4324.0,4513.0
2,State,2869.0,3452.0,3417.0,3233.0,3351.0,3357.0,3478.0,3484.0,3682.0,3729.0,3943.0,4135.0
3,Illness,2567.0,3036.0,3027.0,2865.0,2979.0,2959.0,3081.0,3032.0,3226.0,3197.0,3258.0,3272.0
5,Cancer,691.0,907.0,978.0,927.0,1028.0,1024.0,1065.0,1050.0,1122.0,1130.0,1110.0,1137.0
4,Heart disease,743.0,845.0,850.0,830.0,854.0,804.0,897.0,896.0,986.0,1028.0,1095.0,1052.0
9,All other illnesses/d,404.0,616.0,569.0,535.0,496.0,530.0,514.0,471.0,530.0,525.0,518.0,559.0
1,Federal,301.0,399.0,376.0,387.0,387.0,350.0,400.0,444.0,455.0,388.0,381.0,378.0
10,Suicide,168.0,197.0,202.0,215.0,185.0,205.0,192.0,249.0,219.0,255.0,259.0,311.0
8,Respiratory disease,144.0,250.0,195.0,212.0,204.0,220.0,196.0,233.0,241.0,220.0,252.0,287.0
11,Drug/alcohol intoxication,35.0,58.0,51.0,41.0,58.0,33.0,56.0,50.0,81.0,104.0,203.0,249.0
6,Liver disease,310.0,319.0,337.0,288.0,340.0,307.0,357.0,318.0,302.0,263.0,246.0,215.0
13,Homicide,39.0,40.0,54.0,70.0,70.0,85.0,90.0,83.0,84.0,96.0,113.0,120.0
15,Missing/unknown,38.0,0.0,34.0,3.0,9.0,11.0,7.0,21.0,13.0,13.0,38.0,103.0
12,Accident,22.0,26.0,32.0,32.0,38.0,50.0,34.0,39.0,39.0,41.0,45.0,43.0
14,Other causes,0.0,95.0,17.0,7.0,12.0,14.0,18.0,10.0,20.0,23.0,27.0,37.0
7,AIDS-related/c,275.0,99.0,98.0,73.0,57.0,74.0,52.0,64.0,45.0,31.0,37.0,22.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [101]:
raw_total_deaths_df = pd.read_csv("raw_total_deaths.csv")

In [102]:
raw_total_deaths_df

  Type of death  State  Federal
0         Total  61130     6744
1       Natural  53355     6051
2     Unnatural   6918      597

In [103]:
raw_state_cause_of_death_df = pd.read_csv("raw_state_cause_of_deaths.csv")

In [104]:
raw_state_cause_of_death_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Cause   5 non-null      object
 1   2010    5 non-null      int64
 2   2018    5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 248.0+ bytes

In [105]:
raw_state_cause_of_death_df

                       Cause  2010  2018
0                    Illness  2865  3272
1                    Suicide   215   311
2  Drug/alcohol intoxication    41   249
3                   Accident    32    43
4                 Homicide/a    70   120

In [106]:
state_liver_death_rate_df = pd.read_csv("state_liver_death_rate.csv")

In [107]:
state_liver_death_rate_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  13 non-null     object
 1   2008        13 non-null     int64
 2   2009        13 non-null     int64
 3   2010        13 non-null     int64
 4   2011        13 non-null     int64
 5   2012        13 non-null     int64
 6   2013        13 non-null     int64
 7   2014        13 non-null     int64
 8   2015        13 non-null     int64
 9   2016        13 non-null     int64
 10  2017        13 non-null     int64
 11  2018        13 non-null     int64
dtypes: int64(11), object(1)
memory usage: 1.3+ KB

In [108]:
state_liver_death_rate_df = state_liver_death_rate_df.rename(columns={"Unnamed: 0": "Demographic"})

In [109]:
##Liver diseases lower. Still very higher for older people.
state_liver_death_rate_df

,Demographic,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Total,24,25,24,25,24,26,26,26,24,22,20
1,Male,25,26,25,26,25,27,27,27,24,23,21
2,Female,10,10,10,9,9,13,14,16,13,11,11
3,White,37,40,42,44,44,47,46,46,45,41,38
4,Black,14,15,14,16,14,16,15,15,14,14,12
5,Hispanic,25,24,21,19,20,23,25,25,20,16,15
6,Other,8,8,5,5,5,6,5,5,5,5,4
7,17 or younger,0,0,14,16,19,0,0,0,0,0,0
8,18 to 24,1,1,1,1,0,0,1,1,1,1,1
9,25 to 34,1,1,1,1,1,1,1,1,1,1,1
10,35 to 44,11,11,9,10,7,7,5,5,5,5,5
11,45 to 54,69,67,63,59,54,54,50,47,41,33,26
12,55 or older,136,137,130,138,140,157,152,147,127,119,107

In [110]:
state_liver_death_rate_df.sort_values(by=["2018"], ascending = False)

,Demographic,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
12,55 or older,136,137,130,138,140,157,152,147,127,119,107
3,White,37,40,42,44,44,47,46,46,45,41,38
11,45 to 54,69,67,63,59,54,54,50,47,41,33,26
1,Male,25,26,25,26,25,27,27,27,24,23,21
0,Total,24,25,24,25,24,26,26,26,24,22,20
5,Hispanic,25,24,21,19,20,23,25,25,20,16,15
4,Black,14,15,14,16,14,16,15,15,14,14,12
2,Female,10,10,10,9,9,13,14,16,13,11,11
10,35 to 44,11,11,9,10,7,7,5,5,5,5,5
6,Other,8,8,5,5,5,6,5,5,5,5,4
8,18 to 24,1,1,1,1,0,0,1,1,1,1,1
9,25 to 34,1,1,1,1,1,1,1,1,1,1,1
7,17 or younger,0,0,14,16,19,0,0,0,0,0,0

In [111]:
state_cancer_death_rate_demo_df = pd.read_csv("state_cancer_death_rate-demo.csv")

In [112]:
state_cancer_death_rate_demo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    13 non-null     object
 1   2008    13 non-null     int64
 2   2009    13 non-null     int64
 3   2010    13 non-null     int64
 4   2011    13 non-null     int64
 5   2012    13 non-null     int64
 6   2013    13 non-null     int64
 7   2014    13 non-null     int64
 8   2015    13 non-null     int64
 9   2016    13 non-null     int64
 10  2017    13 non-null     int64
 11  2018    13 non-null     int64
dtypes: int64(11), object(1)
memory usage: 1.3+ KB

In [113]:
state_cancer_death_rate_demo_df = state_cancer_death_rate_demo_df.rename(columns={"Year": "Demographic"})

In [114]:
##Cancer rates really high for older people.
state_cancer_death_rate_demo_df

,Demographic,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Total,63,67,71,75,77,81,82,86,88,91,93
1,Male,65,70,73,77,79,84,85,88,91,94,96
2,Female,33,35,40,48,44,45,43,51,53,49,49
3,White,103,114,119,130,134,145,144,149,154,162,166
4,Black,58,62,66,68,71,75,79,84,89,89,91
5,Hispanic,24,23,28,30,31,32,34,36,38,40,41
6,Other,15,13,15,11,12,11,11,11,11,10,9
7,17 or younger,14,13,14,16,19,23,0,0,37,79,89
8,18 to 24,1,2,3,4,4,3,2,2,2,2,2
9,25 to 34,4,4,4,5,5,6,5,6,6,6,5
10,35 to 44,22,20,22,21,21,22,22,21,19,17,16
11,45 to 54,113,115,117,118,113,116,114,113,104,99,95
12,55 or older,577,592,584,584,573,572,553,550,558,558,554

In [115]:
state_cancer_death_rate_demo_df.sort_values(by=["2018"], ascending = False)

,Demographic,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
12,55 or older,577,592,584,584,573,572,553,550,558,558,554
3,White,103,114,119,130,134,145,144,149,154,162,166
1,Male,65,70,73,77,79,84,85,88,91,94,96
11,45 to 54,113,115,117,118,113,116,114,113,104,99,95
0,Total,63,67,71,75,77,81,82,86,88,91,93
4,Black,58,62,66,68,71,75,79,84,89,89,91
7,17 or younger,14,13,14,16,19,23,0,0,37,79,89
2,Female,33,35,40,48,44,45,43,51,53,49,49
5,Hispanic,24,23,28,30,31,32,34,36,38,40,41
10,35 to 44,22,20,22,21,21,22,22,21,19,17,16
6,Other,15,13,15,11,12,11,11,11,11,10,9
9,25 to 34,4,4,4,5,5,6,5,6,6,6,5
8,18 to 24,1,2,3,4,4,3,2,2,2,2,2

In [116]:
state_other_illness_demo_df = pd.read_csv("state_other_illness_deaths_demo.csv")

In [117]:
state_other_illness_demo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    13 non-null     object
 1   2008    13 non-null     int64
 2   2009    13 non-null     int64
 3   2010    13 non-null     int64
 4   2011    13 non-null     int64
 5   2012    13 non-null     int64
 6   2013    13 non-null     int64
 7   2014    13 non-null     int64
 8   2015    13 non-null     int64
 9   2016    13 non-null     int64
 10  2017    13 non-null     int64
 11  2018    13 non-null     int64
dtypes: int64(11), object(1)
memory usage: 1.3+ KB

In [118]:
state_other_illness_demo_df = state_other_illness_demo_df.rename(columns={"Year": "Demographic"})

In [119]:
state_other_illness_demo_df.head()

,Demographic,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Total,48,48,43,41,40,40,40,40,41,43,44
1,Male,49,49,44,41,41,41,40,41,42,44,45
2,Female,36,39,39,32,31,30,32,29,26,25,30
3,White,65,66,61,59,60,61,61,64,66,69,68
4,Black,48,50,45,43,41,39,40,39,41,43,46

In [120]:
state_other_illness_demo_df.max()

Demographic    White
2008             350
2009             351
2010             302
2011             273
2012             255
2013             250
2014             244
2015             244
2016             238
2017             236
2018             233
dtype: object

In [121]:
state_other_illness_demo_df.sort_values(by=["2018"], ascending = False)

,Demographic,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
12,55 or older,350,351,302,273,255,250,244,244,238,236,233
3,White,65,66,61,59,60,61,61,64,66,69,68
4,Black,48,50,45,43,41,39,40,39,41,43,46
11,45 to 54,84,78,72,65,64,58,55,50,47,45,46
1,Male,49,49,44,41,41,41,40,41,42,44,45
0,Total,48,48,43,41,40,40,40,40,41,43,44
2,Female,36,39,39,32,31,30,32,29,26,25,30
5,Hispanic,32,30,27,23,26,27,28,25,24,25,28
10,35 to 44,28,27,21,18,17,16,14,14,14,14,14
6,Other,12,11,10,9,7,6,6,6,8,8,8
9,25 to 34,9,9,7,7,6,6,5,5,5,7,7
8,18 to 24,4,5,4,4,5,4,4,4,4,3,3
7,17 or younger,0,0,0,0,0,0,0,0,0,0,0

In [122]:
state_mortality_rate_cause_df = pd.read_csv("state_mortality_rate_cause.csv")

In [123]:
state_mortality_rate_cause_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    14 non-null     object
 1   2001    14 non-null     int64
 2   2008    14 non-null     int64
 3   2009    14 non-null     int64
 4   2010    14 non-null     int64
 5   2011    14 non-null     int64
 6   2012    14 non-null     int64
 7   2013    14 non-null     int64
 8   2014    14 non-null     int64
 9   2015    14 non-null     int64
 10  2016    14 non-null     int64
 11  2017    14 non-null     int64
 12  2018    14 non-null     int64
dtypes: int64(12), object(1)
memory usage: 1.5+ KB

In [124]:
state_mortality_rate_cause_df.max()

Year    Suicide
2001        242
2008        261
2009        259
2010        246
2011        260
2012        265
2013        274
2014        274
2015        296
2016        303
2017        323
2018        344
dtype: object

In [125]:
state_mortality_rate_cause_df = state_mortality_rate_cause_df.rename(columns={"Year": "Cause"})

In [126]:
state_mortality_rate_cause_df.sort_values(by=["2018"], ascending = False)

,Cause,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,All causes,242,261,259,246,260,265,274,274,296,303,323,344
1,Illness,217,229,229,218,231,234,243,239,259,260,267,273
3,Cancer,58,68,74,71,80,81,84,83,90,92,91,95
2,Heart disease,63,64,64,63,66,63,71,71,79,84,90,88
7,All other illnesses,34,47,43,41,38,42,40,37,43,43,42,47
8,Suicide,14,15,15,16,14,16,15,20,18,21,21,26
6,Respiratory disease,12,19,15,16,16,17,15,18,19,18,21,24
9,Drug/alcohol intoxication,3,4,4,3,4,3,4,4,7,8,17,21
4,Liver disease,26,24,26,22,26,24,28,25,24,21,20,18
11,Homicide,3,3,4,5,5,7,7,7,7,8,9,10
13,Missing/unknown,3,0,3,0,1,1,1,2,1,1,3,9
10,Accident,2,2,2,2,3,4,3,3,3,3,4,4
12,Other causes,0,7,1,1,1,1,1,1,2,2,2,3
5,AIDS-related,23,7,7,6,4,6,4,5,4,3,3,2

In [127]:
state_cause_death_number_percent_df = pd.read_csv("state_death_cause_number_percent.csv")

In [128]:
##Suicide, drugs and homocide combine for nearly 18 percent of deaths.
state_cause_death_number_percent_df

              Cause of death  Number  Percent
0                 All causes    3293    100.0
1                    Illness    2429     73.8
2               AIDS-related      13      0.4
3                    Suicide     271      8.2
4  Drug/alcohol intoxication     204      6.2
5                   Accident      24      0.7
6                   Homicide     106      3.2
7               Other causes      46      1.4
8            Missing/unknown     200      6.1

In [129]:
state_fed_resp_deaths_df = pd.read_csv("state_fed_resp_deaths.csv")

In [130]:
state_fed_resp_deaths_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    13 non-null     object
 1   2008    13 non-null     int64
 2   2009    13 non-null     int64
 3   2010    13 non-null     int64
 4   2011    13 non-null     int64
 5   2012    13 non-null     int64
 6   2013    13 non-null     int64
 7   2014    13 non-null     int64
 8   2015    13 non-null     int64
 9   2016    13 non-null     int64
 10  2017    13 non-null     int64
 11  2018    13 non-null     int64
dtypes: int64(11), object(1)
memory usage: 1.3+ KB

In [131]:
state_fed_resp_deaths_df.max()

Year    White
2008      143
2009      139
2010      136
2011      121
2012      127
2013      119
2014      123
2015      124
2016      124
2017      127
2018      129
dtype: object

In [132]:
state_fed_resp_deaths_df = state_fed_resp_deaths_df.rename(columns={"Year": "Demographic"})

In [133]:
state_fed_resp_deaths_df.sort_values(by=["2018"], ascending = False)

,Demographic,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
12,55 or older,143,139,136,121,127,119,123,124,124,127,129
3,White,28,28,28,29,31,32,32,34,35,37,40
0,Total,17,16,17,16,16,16,17,18,19,19,21
1,Male,17,17,17,16,17,17,18,18,19,20,21
4,Black,14,14,14,12,13,12,14,15,16,16,18
2,Female,16,14,12,10,7,10,9,10,11,12,16
11,45 to 54,23,21,20,20,19,17,16,15,16,14,15
5,Hispanic,8,8,9,7,7,7,8,7,8,9,10
10,35 to 44,8,8,7,6,5,4,4,4,4,5,6
6,Other,1,1,1,1,2,3,3,3,3,2,2
9,25 to 34,3,3,3,2,3,3,3,2,2,1,2
7,17 or younger,14,0,0,0,0,0,0,0,0,0,0
8,18 to 24,3,2,2,1,2,2,2,2,1,1,0

In [134]:
raw_state_fed_death_cause_df

,Cause,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Total,3170.0,3851.0,3793.0,3620.0,3738.0,3707.0,3878.0,3928.0,4137.0,4117.0,4324.0,4513.0
1,Federal,301.0,399.0,376.0,387.0,387.0,350.0,400.0,444.0,455.0,388.0,381.0,378.0
2,State,2869.0,3452.0,3417.0,3233.0,3351.0,3357.0,3478.0,3484.0,3682.0,3729.0,3943.0,4135.0
3,Illness,2567.0,3036.0,3027.0,2865.0,2979.0,2959.0,3081.0,3032.0,3226.0,3197.0,3258.0,3272.0
4,Heart disease,743.0,845.0,850.0,830.0,854.0,804.0,897.0,896.0,986.0,1028.0,1095.0,1052.0
5,Cancer,691.0,907.0,978.0,927.0,1028.0,1024.0,1065.0,1050.0,1122.0,1130.0,1110.0,1137.0
6,Liver disease,310.0,319.0,337.0,288.0,340.0,307.0,357.0,318.0,302.0,263.0,246.0,215.0
7,AIDS-related/c,275.0,99.0,98.0,73.0,57.0,74.0,52.0,64.0,45.0,31.0,37.0,22.0
8,Respiratory disease,144.0,250.0,195.0,212.0,204.0,220.0,196.0,233.0,241.0,220.0,252.0,287.0
9,All other illnesses/d,404.0,616.0,569.0,535.0,496.0,530.0,514.0,471.0,530.0,525.0,518.0,559.0
10,Suicide,168.0,197.0,202.0,215.0,185.0,205.0,192.0,249.0,219.0,255.0,259.0,311.0
11,Drug/alcohol intoxication,35.0,58.0,51.0,41.0,58.0,33.0,56.0,50.0,81.0,104.0,203.0,249.0
12,Accident,22.0,26.0,32.0,32.0,38.0,50.0,34.0,39.0,39.0,41.0,45.0,43.0
13,Homicide,39.0,40.0,54.0,70.0,70.0,85.0,90.0,83.0,84.0,96.0,113.0,120.0
14,Other causes,0.0,95.0,17.0,7.0,12.0,14.0,18.0,10.0,20.0,23.0,27.0,37.0
15,Missing/unknown,38.0,0.0,34.0,3.0,9.0,11.0,7.0,21.0,13.0,13.0,38.0,103.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [135]:
raw_state_fed_death_cause_df["diff"] = raw_state_fed_death_cause_df.apply(lambda x: x["2018"] - x["2001"], axis = 1)
raw_state_fed_death_cause_df

,Cause,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,diff
0,Total,3170.0,3851.0,3793.0,3620.0,3738.0,3707.0,3878.0,3928.0,4137.0,4117.0,4324.0,4513.0,1343.0
1,Federal,301.0,399.0,376.0,387.0,387.0,350.0,400.0,444.0,455.0,388.0,381.0,378.0,77.0
2,State,2869.0,3452.0,3417.0,3233.0,3351.0,3357.0,3478.0,3484.0,3682.0,3729.0,3943.0,4135.0,1266.0
3,Illness,2567.0,3036.0,3027.0,2865.0,2979.0,2959.0,3081.0,3032.0,3226.0,3197.0,3258.0,3272.0,705.0
4,Heart disease,743.0,845.0,850.0,830.0,854.0,804.0,897.0,896.0,986.0,1028.0,1095.0,1052.0,309.0
5,Cancer,691.0,907.0,978.0,927.0,1028.0,1024.0,1065.0,1050.0,1122.0,1130.0,1110.0,1137.0,446.0
6,Liver disease,310.0,319.0,337.0,288.0,340.0,307.0,357.0,318.0,302.0,263.0,246.0,215.0,-95.0
7,AIDS-related/c,275.0,99.0,98.0,73.0,57.0,74.0,52.0,64.0,45.0,31.0,37.0,22.0,-253.0
8,Respiratory disease,144.0,250.0,195.0,212.0,204.0,220.0,196.0,233.0,241.0,220.0,252.0,287.0,143.0
9,All other illnesses/d,404.0,616.0,569.0,535.0,496.0,530.0,514.0,471.0,530.0,525.0,518.0,559.0,155.0
10,Suicide,168.0,197.0,202.0,215.0,185.0,205.0,192.0,249.0,219.0,255.0,259.0,311.0,143.0
11,Drug/alcohol intoxication,35.0,58.0,51.0,41.0,58.0,33.0,56.0,50.0,81.0,104.0,203.0,249.0,214.0
12,Accident,22.0,26.0,32.0,32.0,38.0,50.0,34.0,39.0,39.0,41.0,45.0,43.0,21.0
13,Homicide,39.0,40.0,54.0,70.0,70.0,85.0,90.0,83.0,84.0,96.0,113.0,120.0,81.0
14,Other causes,0.0,95.0,17.0,7.0,12.0,14.0,18.0,10.0,20.0,23.0,27.0,37.0,37.0
15,Missing/unknown,38.0,0.0,34.0,3.0,9.0,11.0,7.0,21.0,13.0,13.0,38.0,103.0,65.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [136]:
##See rises and drops in death. Everything has risen except for AIDS and accidents.
raw_state_fed_death_cause_df.sort_values(by="diff", ascending = False)

,Cause,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,diff
0,Total,3170.0,3851.0,3793.0,3620.0,3738.0,3707.0,3878.0,3928.0,4137.0,4117.0,4324.0,4513.0,1343.0
2,State,2869.0,3452.0,3417.0,3233.0,3351.0,3357.0,3478.0,3484.0,3682.0,3729.0,3943.0,4135.0,1266.0
3,Illness,2567.0,3036.0,3027.0,2865.0,2979.0,2959.0,3081.0,3032.0,3226.0,3197.0,3258.0,3272.0,705.0
5,Cancer,691.0,907.0,978.0,927.0,1028.0,1024.0,1065.0,1050.0,1122.0,1130.0,1110.0,1137.0,446.0
4,Heart disease,743.0,845.0,850.0,830.0,854.0,804.0,897.0,896.0,986.0,1028.0,1095.0,1052.0,309.0
11,Drug/alcohol intoxication,35.0,58.0,51.0,41.0,58.0,33.0,56.0,50.0,81.0,104.0,203.0,249.0,214.0
9,All other illnesses/d,404.0,616.0,569.0,535.0,496.0,530.0,514.0,471.0,530.0,525.0,518.0,559.0,155.0
8,Respiratory disease,144.0,250.0,195.0,212.0,204.0,220.0,196.0,233.0,241.0,220.0,252.0,287.0,143.0
10,Suicide,168.0,197.0,202.0,215.0,185.0,205.0,192.0,249.0,219.0,255.0,259.0,311.0,143.0
13,Homicide,39.0,40.0,54.0,70.0,70.0,85.0,90.0,83.0,84.0,96.0,113.0,120.0,81.0
1,Federal,301.0,399.0,376.0,387.0,387.0,350.0,400.0,444.0,455.0,388.0,381.0,378.0,77.0
15,Missing/unknown,38.0,0.0,34.0,3.0,9.0,11.0,7.0,21.0,13.0,13.0,38.0,103.0,65.0
14,Other causes,0.0,95.0,17.0,7.0,12.0,14.0,18.0,10.0,20.0,23.0,27.0,37.0,37.0
12,Accident,22.0,26.0,32.0,32.0,38.0,50.0,34.0,39.0,39.0,41.0,45.0,43.0,21.0
6,Liver disease,310.0,319.0,337.0,288.0,340.0,307.0,357.0,318.0,302.0,263.0,246.0,215.0,-95.0
7,AIDS-related/c,275.0,99.0,98.0,73.0,57.0,74.0,52.0,64.0,45.0,31.0,37.0,22.0,-253.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
state_mortality_rate_cause_df["diff"] = state_mortality_rate_cause_df.apply(lambda x: x["2018"] - x["2001"], axis = 1)
state_mortality_rate_cause_df

,Cause,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,diff
0,All causes,242,261,259,246,260,265,274,274,296,303,323,344,102
1,Illness,217,229,229,218,231,234,243,239,259,260,267,273,56
2,Heart disease,63,64,64,63,66,63,71,71,79,84,90,88,25
3,Cancer,58,68,74,71,80,81,84,83,90,92,91,95,37
4,Liver disease,26,24,26,22,26,24,28,25,24,21,20,18,-8
5,AIDS-related,23,7,7,6,4,6,4,5,4,3,3,2,-21
6,Respiratory disease,12,19,15,16,16,17,15,18,19,18,21,24,12
7,All other illnesses,34,47,43,41,38,42,40,37,43,43,42,47,13
8,Suicide,14,15,15,16,14,16,15,20,18,21,21,26,12
9,Drug/alcohol intoxication,3,4,4,3,4,3,4,4,7,8,17,21,18
10,Accident,2,2,2,2,3,4,3,3,3,3,4,4,2
11,Homicide,3,3,4,5,5,7,7,7,7,8,9,10,7
12,Other causes,0,7,1,1,1,1,1,1,2,2,2,3,3
13,Missing/unknown,3,0,3,0,1,1,1,2,1,1,3,9,6

In [138]:
##Numbers for rates
state_mortality_rate_cause_df.sort_values(by="diff", ascending = False)

,Cause,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,diff
0,All causes,242,261,259,246,260,265,274,274,296,303,323,344,102
1,Illness,217,229,229,218,231,234,243,239,259,260,267,273,56
3,Cancer,58,68,74,71,80,81,84,83,90,92,91,95,37
2,Heart disease,63,64,64,63,66,63,71,71,79,84,90,88,25
9,Drug/alcohol intoxication,3,4,4,3,4,3,4,4,7,8,17,21,18
7,All other illnesses,34,47,43,41,38,42,40,37,43,43,42,47,13
6,Respiratory disease,12,19,15,16,16,17,15,18,19,18,21,24,12
8,Suicide,14,15,15,16,14,16,15,20,18,21,21,26,12
11,Homicide,3,3,4,5,5,7,7,7,7,8,9,10,7
13,Missing/unknown,3,0,3,0,1,1,1,2,1,1,3,9,6
12,Other causes,0,7,1,1,1,1,1,1,2,2,2,3,3
10,Accident,2,2,2,2,3,4,3,3,3,3,4,4,2
4,Liver disease,26,24,26,22,26,24,28,25,24,21,20,18,-8
5,AIDS-related,23,7,7,6,4,6,4,5,4,3,3,2,-21

In [150]:
death_rate_state_df["diff"] = death_rate_state_df.apply(lambda x: x["2018"] - x["2001"], axis = 1)
death_rate_state_df

,Year,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,diff
0,Federal,220,241,220,224,220,198,230,262,283,252,246,250,30
1,State,242,261,259,246,260,265,274,274,296,303,323,344,102
2,Alabama,352,296,294,241,388,321,399,390,444,497,531,588,236
3,Alaska,175,280,128,242,193,174,157,190,286,228,206,260,85
4,Arizona,231,195,210,212,215,217,232,235,249,298,317,312,81
5,Arkansas,366,312,375,380,355,306,392,374,342,448,510,488,122
6,California,183,217,234,254,263,277,272,236,276,258,295,352,169
7,Colorado,243,164,216,211,169,236,198,171,256,293,209,275,32
8,Connecticut,171,161,153,113,106,140,115,143,144,113,103,212,41
9,Delaware,234,216,182,361,229,149,206,267,264,221,163,287,53
10,Florida,251,291,274,269,294,325,302,343,356,363,443,460,209
11,Georgia,202,243,233,212,229,187,227,230,252,249,323,306,104
12,Hawaii,137,257,227,227,110,227,271,148,74,174,78,120,-17
13,Idaho,323,256,181,180,174,117,139,307,249,222,196,273,-50
14,Illinois,194,156,166,194,200,172,160,182,260,206,253,208,14
15,Indiana,234,265,340,253,270,210,232,215,320,278,264,252,18
16,Iowa,113,241,157,137,132,229,184,170,214,320,177,201,88
17,Kansas,245,281,231,243,268,179,291,220,262,363,268,332,87
18,Kentucky,336,446,380,290,429,423,329,363,502,354,583,381,45
19,Louisiana,361,561,543,526,573,624,628,631,613,817,759,766,405
20,Maine,358,98,193,154,253,101,145,318,228,212,170,336,-22
21,Maryland,295,298,254,175,178,211,267,202,296,242,286,297,2
22,Massachusetts,284,260,260,349,288,377,367,431,358,376,418,497,213
23,Michigan,233,203,325,211,277,284,284,279,277,258,267,348,115
24,Minnesota,203,188,126,170,204,149,213,146,115,189,63,64,-139
25,Mississippi,238,302,302,316,305,260,436,383,322,474,568,572,334
26,Missouri,199,289,265,288,239,228,292,304,328,305,289,349,150
27,Montana,215,309,97,64,192,355,224,609,409,500,409,130,-85
28,Nebraska,179,134,245,260,365,233,319,249,331,174,308,187,8
29,Nevada,274,272,278,336,280,294,274,347,355,301,349,217,-57
30,New Hampshire,83,175,309,153,413,195,305,184,301,346,197,312,229
31,New Jersey,265,266,241,229,279,208,207,234,256,252,203,173,-92
32,New Mexico,194,459,319,240,239,211,251,345,267,229,250,332,138
33,New York,259,221,243,220,212,213,266,235,223,290,289,295,36
34,North Carolina,205,293,214,215,179,211,218,252,244,353,284,336,131
35,North Dakota,276,0,0,71,72,212,63,0,0,244,126,0,-276
36,Ohio,256,198,236,224,218,248,240,215,264,255,289,299,43
37,Oklahoma,235,372,328,248,358,324,343,404,392,353,315,415,180
38,Oregon,219,229,248,281,291,184,205,214,252,322,171,231,12
39,Pennsylvania,324,298,327,293,316,313,314,295,340,354,383,358,34
40,Rhode Island,89,160,205,222,330,197,126,223,168,69,298,194,105
41,South Carolina,318,350,207,304,246,265,306,315,372,388,541,539,221
42,South Dakota,143,179,118,236,309,250,166,200,198,133,308,156,13
43,Tennessee,292,382,346,369,298,424,395,399,475,474,436,619,327
44,Texas,275,295,269,234,261,298,282,265,274,266,311,337,62
45,Utah,121,214,324,239,227,283,427,433,331,466,403,327,206
46,Vermont,214,142,135,241,0,98,385,303,229,403,300,117,-97
47,Virginia,226,264,281,291,324,289,273,300,296,301,312,358,132
48,Washington,190,204,255,206,123,195,220,221,244,163,226,207,17
49,West Virginia,500,388,356,394,447,450,456,409,473,441,490,583,83
50,Wisconsin,231,197,189,113,214,205,192,257,201,285,183,221,-10
51,Wyoming,336,528,402,96,139,183,175,507,292,468,331,245,-91

In [151]:
##Southern states with bigges increases, but New Hampshire high up. Same with Mass, Utah, OK.
death_rate_state_df.sort_values(by="diff", ascending = False)

,Year,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,diff
19,Louisiana,361,561,543,526,573,624,628,631,613,817,759,766,405
25,Mississippi,238,302,302,316,305,260,436,383,322,474,568,572,334
43,Tennessee,292,382,346,369,298,424,395,399,475,474,436,619,327
2,Alabama,352,296,294,241,388,321,399,390,444,497,531,588,236
30,New Hampshire,83,175,309,153,413,195,305,184,301,346,197,312,229
41,South Carolina,318,350,207,304,246,265,306,315,372,388,541,539,221
22,Massachusetts,284,260,260,349,288,377,367,431,358,376,418,497,213
10,Florida,251,291,274,269,294,325,302,343,356,363,443,460,209
45,Utah,121,214,324,239,227,283,427,433,331,466,403,327,206
37,Oklahoma,235,372,328,248,358,324,343,404,392,353,315,415,180
6,California,183,217,234,254,263,277,272,236,276,258,295,352,169
26,Missouri,199,289,265,288,239,228,292,304,328,305,289,349,150
32,New Mexico,194,459,319,240,239,211,251,345,267,229,250,332,138
47,Virginia,226,264,281,291,324,289,273,300,296,301,312,358,132
34,North Carolina,205,293,214,215,179,211,218,252,244,353,284,336,131
5,Arkansas,366,312,375,380,355,306,392,374,342,448,510,488,122
23,Michigan,233,203,325,211,277,284,284,279,277,258,267,348,115
40,Rhode Island,89,160,205,222,330,197,126,223,168,69,298,194,105
11,Georgia,202,243,233,212,229,187,227,230,252,249,323,306,104
1,State,242,261,259,246,260,265,274,274,296,303,323,344,102
16,Iowa,113,241,157,137,132,229,184,170,214,320,177,201,88
17,Kansas,245,281,231,243,268,179,291,220,262,363,268,332,87
3,Alaska,175,280,128,242,193,174,157,190,286,228,206,260,85
49,West Virginia,500,388,356,394,447,450,456,409,473,441,490,583,83
4,Arizona,231,195,210,212,215,217,232,235,249,298,317,312,81
44,Texas,275,295,269,234,261,298,282,265,274,266,311,337,62
9,Delaware,234,216,182,361,229,149,206,267,264,221,163,287,53
18,Kentucky,336,446,380,290,429,423,329,363,502,354,583,381,45
36,Ohio,256,198,236,224,218,248,240,215,264,255,289,299,43
8,Connecticut,171,161,153,113,106,140,115,143,144,113,103,212,41
33,New York,259,221,243,220,212,213,266,235,223,290,289,295,36
39,Pennsylvania,324,298,327,293,316,313,314,295,340,354,383,358,34
7,Colorado,243,164,216,211,169,236,198,171,256,293,209,275,32
0,Federal,220,241,220,224,220,198,230,262,283,252,246,250,30
15,Indiana,234,265,340,253,270,210,232,215,320,278,264,252,18
48,Washington,190,204,255,206,123,195,220,221,244,163,226,207,17
14,Illinois,194,156,166,194,200,172,160,182,260,206,253,208,14
42,South Dakota,143,179,118,236,309,250,166,200,198,133,308,156,13
38,Oregon,219,229,248,281,291,184,205,214,252,322,171,231,12
28,Nebraska,179,134,245,260,365,233,319,249,331,174,308,187,8
21,Maryland,295,298,254,175,178,211,267,202,296,242,286,297,2
50,Wisconsin,231,197,189,113,214,205,192,257,201,285,183,221,-10
12,Hawaii,137,257,227,227,110,227,271,148,74,174,78,120,-17
20,Maine,358,98,193,154,253,101,145,318,228,212,170,336,-22
13,Idaho,323,256,181,180,174,117,139,307,249,222,196,273,-50
29,Nevada,274,272,278,336,280,294,274,347,355,301,349,217,-57
27,Montana,215,309,97,64,192,355,224,609,409,500,409,130,-85
51,Wyoming,336,528,402,96,139,183,175,507,292,468,331,245,-91
31,New Jersey,265,266,241,229,279,208,207,234,256,252,203,173,-92
46,Vermont,214,142,135,241,0,98,385,303,229,403,300,117,-97
24,Minnesota,203,188,126,170,204,149,213,146,115,189,63,64,-139
35,North Dakota,276,0,0,71,72,212,63,0,0,244,126,0,-276

In [152]:
death_rate_state_df["pct_chg"] = death_rate_state_df.apply(lambda x: ((x["2018"] - x["2001"])/x["2001"])*100, axis = 1)
death_rate_state_df

,Year,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,diff,pct_chg
0,Federal,220,241,220,224,220,198,230,262,283,252,246,250,30,13.636364
1,State,242,261,259,246,260,265,274,274,296,303,323,344,102,42.148760
2,Alabama,352,296,294,241,388,321,399,390,444,497,531,588,236,67.045455
3,Alaska,175,280,128,242,193,174,157,190,286,228,206,260,85,48.571429
4,Arizona,231,195,210,212,215,217,232,235,249,298,317,312,81,35.064935
5,Arkansas,366,312,375,380,355,306,392,374,342,448,510,488,122,33.333333
6,California,183,217,234,254,263,277,272,236,276,258,295,352,169,92.349727
7,Colorado,243,164,216,211,169,236,198,171,256,293,209,275,32,13.168724
8,Connecticut,171,161,153,113,106,140,115,143,144,113,103,212,41,23.976608
9,Delaware,234,216,182,361,229,149,206,267,264,221,163,287,53,22.649573
10,Florida,251,291,274,269,294,325,302,343,356,363,443,460,209,83.266932
11,Georgia,202,243,233,212,229,187,227,230,252,249,323,306,104,51.485149
12,Hawaii,137,257,227,227,110,227,271,148,74,174,78,120,-17,-12.408759
13,Idaho,323,256,181,180,174,117,139,307,249,222,196,273,-50,-15.479876
14,Illinois,194,156,166,194,200,172,160,182,260,206,253,208,14,7.216495
15,Indiana,234,265,340,253,270,210,232,215,320,278,264,252,18,7.692308
16,Iowa,113,241,157,137,132,229,184,170,214,320,177,201,88,77.876106
17,Kansas,245,281,231,243,268,179,291,220,262,363,268,332,87,35.510204
18,Kentucky,336,446,380,290,429,423,329,363,502,354,583,381,45,13.392857
19,Louisiana,361,561,543,526,573,624,628,631,613,817,759,766,405,112.188366
20,Maine,358,98,193,154,253,101,145,318,228,212,170,336,-22,-6.145251
21,Maryland,295,298,254,175,178,211,267,202,296,242,286,297,2,0.677966
22,Massachusetts,284,260,260,349,288,377,367,431,358,376,418,497,213,75.000000
23,Michigan,233,203,325,211,277,284,284,279,277,258,267,348,115,49.356223
24,Minnesota,203,188,126,170,204,149,213,146,115,189,63,64,-139,-68.472906
25,Mississippi,238,302,302,316,305,260,436,383,322,474,568,572,334,140.336134
26,Missouri,199,289,265,288,239,228,292,304,328,305,289,349,150,75.376884
27,Montana,215,309,97,64,192,355,224,609,409,500,409,130,-85,-39.534884
28,Nebraska,179,134,245,260,365,233,319,249,331,174,308,187,8,4.469274
29,Nevada,274,272,278,336,280,294,274,347,355,301,349,217,-57,-20.802920
30,New Hampshire,83,175,309,153,413,195,305,184,301,346,197,312,229,275.903614
31,New Jersey,265,266,241,229,279,208,207,234,256,252,203,173,-92,-34.716981
32,New Mexico,194,459,319,240,239,211,251,345,267,229,250,332,138,71.134021
33,New York,259,221,243,220,212,213,266,235,223,290,289,295,36,13.899614
34,North Carolina,205,293,214,215,179,211,218,252,244,353,284,336,131,63.902439
35,North Dakota,276,0,0,71,72,212,63,0,0,244,126,0,-276,-100.000000
36,Ohio,256,198,236,224,218,248,240,215,264,255,289,299,43,16.796875
37,Oklahoma,235,372,328,248,358,324,343,404,392,353,315,415,180,76.595745
38,Oregon,219,229,248,281,291,184,205,214,252,322,171,231,12,5.479452
39,Pennsylvania,324,298,327,293,316,313,314,295,340,354,383,358,34,10.493827
40,Rhode Island,89,160,205,222,330,197,126,223,168,69,298,194,105,117.977528
41,South Carolina,318,350,207,304,246,265,306,315,372,388,541,539,221,69.496855
42,South Dakota,143,179,118,236,309,250,166,200,198,133,308,156,13,9.090909
43,Tennessee,292,382,346,369,298,424,395,399,475,474,436,619,327,111.986301
44,Texas,275,295,269,234,261,298,282,265,274,266,311,337,62,22.545455
45,Utah,121,214,324,239,227,283,427,433,331,466,403,327,206,170.247934
46,Vermont,214,142,135,241,0,98,385,303,229,403,300,117,-97,-45.327103
47,Virginia,226,264,281,291,324,289,273,300,296,301,312,358,132,58.407080
48,Washington,190,204,255,206,123,195,220,221,244,163,226,207,17,8.947368
49,West Virginia,500,388,356,394,447,450,456,409,473,441,490,583,83,16.600000
50,Wisconsin,231,197,189,113,214,205,192,257,201,285,183,221,-10,-4.329004
51,Wyoming,336,528,402,96,139,183,175,507,292,468,331,245,-91,-27.083333

In [153]:
##Bama with a 67 percent increases in death rate.
death_rate_state_df = death_rate_state_df.round(decimals = 2)
death_rate_state_df

,Year,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,diff,pct_chg
0,Federal,220,241,220,224,220,198,230,262,283,252,246,250,30,13.64
1,State,242,261,259,246,260,265,274,274,296,303,323,344,102,42.15
2,Alabama,352,296,294,241,388,321,399,390,444,497,531,588,236,67.05
3,Alaska,175,280,128,242,193,174,157,190,286,228,206,260,85,48.57
4,Arizona,231,195,210,212,215,217,232,235,249,298,317,312,81,35.06
5,Arkansas,366,312,375,380,355,306,392,374,342,448,510,488,122,33.33
6,California,183,217,234,254,263,277,272,236,276,258,295,352,169,92.35
7,Colorado,243,164,216,211,169,236,198,171,256,293,209,275,32,13.17
8,Connecticut,171,161,153,113,106,140,115,143,144,113,103,212,41,23.98
9,Delaware,234,216,182,361,229,149,206,267,264,221,163,287,53,22.65
10,Florida,251,291,274,269,294,325,302,343,356,363,443,460,209,83.27
11,Georgia,202,243,233,212,229,187,227,230,252,249,323,306,104,51.49
12,Hawaii,137,257,227,227,110,227,271,148,74,174,78,120,-17,-12.41
13,Idaho,323,256,181,180,174,117,139,307,249,222,196,273,-50,-15.48
14,Illinois,194,156,166,194,200,172,160,182,260,206,253,208,14,7.22
15,Indiana,234,265,340,253,270,210,232,215,320,278,264,252,18,7.69
16,Iowa,113,241,157,137,132,229,184,170,214,320,177,201,88,77.88
17,Kansas,245,281,231,243,268,179,291,220,262,363,268,332,87,35.51
18,Kentucky,336,446,380,290,429,423,329,363,502,354,583,381,45,13.39
19,Louisiana,361,561,543,526,573,624,628,631,613,817,759,766,405,112.19
20,Maine,358,98,193,154,253,101,145,318,228,212,170,336,-22,-6.15
21,Maryland,295,298,254,175,178,211,267,202,296,242,286,297,2,0.68
22,Massachusetts,284,260,260,349,288,377,367,431,358,376,418,497,213,75.00
23,Michigan,233,203,325,211,277,284,284,279,277,258,267,348,115,49.36
24,Minnesota,203,188,126,170,204,149,213,146,115,189,63,64,-139,-68.47
25,Mississippi,238,302,302,316,305,260,436,383,322,474,568,572,334,140.34
26,Missouri,199,289,265,288,239,228,292,304,328,305,289,349,150,75.38
27,Montana,215,309,97,64,192,355,224,609,409,500,409,130,-85,-39.53
28,Nebraska,179,134,245,260,365,233,319,249,331,174,308,187,8,4.47
29,Nevada,274,272,278,336,280,294,274,347,355,301,349,217,-57,-20.80
30,New Hampshire,83,175,309,153,413,195,305,184,301,346,197,312,229,275.90
31,New Jersey,265,266,241,229,279,208,207,234,256,252,203,173,-92,-34.72
32,New Mexico,194,459,319,240,239,211,251,345,267,229,250,332,138,71.13
33,New York,259,221,243,220,212,213,266,235,223,290,289,295,36,13.90
34,North Carolina,205,293,214,215,179,211,218,252,244,353,284,336,131,63.90
35,North Dakota,276,0,0,71,72,212,63,0,0,244,126,0,-276,-100.00
36,Ohio,256,198,236,224,218,248,240,215,264,255,289,299,43,16.80
37,Oklahoma,235,372,328,248,358,324,343,404,392,353,315,415,180,76.60
38,Oregon,219,229,248,281,291,184,205,214,252,322,171,231,12,5.48
39,Pennsylvania,324,298,327,293,316,313,314,295,340,354,383,358,34,10.49
40,Rhode Island,89,160,205,222,330,197,126,223,168,69,298,194,105,117.98
41,South Carolina,318,350,207,304,246,265,306,315,372,388,541,539,221,69.50
42,South Dakota,143,179,118,236,309,250,166,200,198,133,308,156,13,9.09
43,Tennessee,292,382,346,369,298,424,395,399,475,474,436,619,327,111.99
44,Texas,275,295,269,234,261,298,282,265,274,266,311,337,62,22.55
45,Utah,121,214,324,239,227,283,427,433,331,466,403,327,206,170.25
46,Vermont,214,142,135,241,0,98,385,303,229,403,300,117,-97,-45.33
47,Virginia,226,264,281,291,324,289,273,300,296,301,312,358,132,58.41
48,Washington,190,204,255,206,123,195,220,221,244,163,226,207,17,8.95
49,West Virginia,500,388,356,394,447,450,456,409,473,441,490,583,83,16.60
50,Wisconsin,231,197,189,113,214,205,192,257,201,285,183,221,-10,-4.33
51,Wyoming,336,528,402,96,139,183,175,507,292,468,331,245,-91,-27.08

In [154]:
##New Hampshire with a whopping 276 percent increase. Utah at 170.
death_rate_state_df.sort_values(by="pct_chg", ascending = False)

,Year,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,diff,pct_chg
30,New Hampshire,83,175,309,153,413,195,305,184,301,346,197,312,229,275.90
45,Utah,121,214,324,239,227,283,427,433,331,466,403,327,206,170.25
25,Mississippi,238,302,302,316,305,260,436,383,322,474,568,572,334,140.34
40,Rhode Island,89,160,205,222,330,197,126,223,168,69,298,194,105,117.98
19,Louisiana,361,561,543,526,573,624,628,631,613,817,759,766,405,112.19
43,Tennessee,292,382,346,369,298,424,395,399,475,474,436,619,327,111.99
6,California,183,217,234,254,263,277,272,236,276,258,295,352,169,92.35
10,Florida,251,291,274,269,294,325,302,343,356,363,443,460,209,83.27
16,Iowa,113,241,157,137,132,229,184,170,214,320,177,201,88,77.88
37,Oklahoma,235,372,328,248,358,324,343,404,392,353,315,415,180,76.60
26,Missouri,199,289,265,288,239,228,292,304,328,305,289,349,150,75.38
22,Massachusetts,284,260,260,349,288,377,367,431,358,376,418,497,213,75.00
32,New Mexico,194,459,319,240,239,211,251,345,267,229,250,332,138,71.13
41,South Carolina,318,350,207,304,246,265,306,315,372,388,541,539,221,69.50
2,Alabama,352,296,294,241,388,321,399,390,444,497,531,588,236,67.05
34,North Carolina,205,293,214,215,179,211,218,252,244,353,284,336,131,63.90
47,Virginia,226,264,281,291,324,289,273,300,296,301,312,358,132,58.41
11,Georgia,202,243,233,212,229,187,227,230,252,249,323,306,104,51.49
23,Michigan,233,203,325,211,277,284,284,279,277,258,267,348,115,49.36
3,Alaska,175,280,128,242,193,174,157,190,286,228,206,260,85,48.57
1,State,242,261,259,246,260,265,274,274,296,303,323,344,102,42.15
17,Kansas,245,281,231,243,268,179,291,220,262,363,268,332,87,35.51
4,Arizona,231,195,210,212,215,217,232,235,249,298,317,312,81,35.06
5,Arkansas,366,312,375,380,355,306,392,374,342,448,510,488,122,33.33
8,Connecticut,171,161,153,113,106,140,115,143,144,113,103,212,41,23.98
9,Delaware,234,216,182,361,229,149,206,267,264,221,163,287,53,22.65
44,Texas,275,295,269,234,261,298,282,265,274,266,311,337,62,22.55
36,Ohio,256,198,236,224,218,248,240,215,264,255,289,299,43,16.80
49,West Virginia,500,388,356,394,447,450,456,409,473,441,490,583,83,16.60
33,New York,259,221,243,220,212,213,266,235,223,290,289,295,36,13.90
0,Federal,220,241,220,224,220,198,230,262,283,252,246,250,30,13.64
18,Kentucky,336,446,380,290,429,423,329,363,502,354,583,381,45,13.39
7,Colorado,243,164,216,211,169,236,198,171,256,293,209,275,32,13.17
39,Pennsylvania,324,298,327,293,316,313,314,295,340,354,383,358,34,10.49
42,South Dakota,143,179,118,236,309,250,166,200,198,133,308,156,13,9.09
48,Washington,190,204,255,206,123,195,220,221,244,163,226,207,17,8.95
15,Indiana,234,265,340,253,270,210,232,215,320,278,264,252,18,7.69
14,Illinois,194,156,166,194,200,172,160,182,260,206,253,208,14,7.22
38,Oregon,219,229,248,281,291,184,205,214,252,322,171,231,12,5.48
28,Nebraska,179,134,245,260,365,233,319,249,331,174,308,187,8,4.47
21,Maryland,295,298,254,175,178,211,267,202,296,242,286,297,2,0.68
50,Wisconsin,231,197,189,113,214,205,192,257,201,285,183,221,-10,-4.33
20,Maine,358,98,193,154,253,101,145,318,228,212,170,336,-22,-6.15
12,Hawaii,137,257,227,227,110,227,271,148,74,174,78,120,-17,-12.41
13,Idaho,323,256,181,180,174,117,139,307,249,222,196,273,-50,-15.48
29,Nevada,274,272,278,336,280,294,274,347,355,301,349,217,-57,-20.80
51,Wyoming,336,528,402,96,139,183,175,507,292,468,331,245,-91,-27.08
31,New Jersey,265,266,241,229,279,208,207,234,256,252,203,173,-92,-34.72
27,Montana,215,309,97,64,192,355,224,609,409,500,409,130,-85,-39.53
46,Vermont,214,142,135,241,0,98,385,303,229,403,300,117,-97,-45.33
24,Minnesota,203,188,126,170,204,149,213,146,115,189,63,64,-139,-68.47
35,North Dakota,276,0,0,71,72,212,63,0,0,244,126,0,-276,-100.00

In [155]:
raw_total_deaths_state_fed_df["diff"] = raw_total_deaths_state_fed_df.apply(lambda x: x["2018"] - x["2001"], axis = 1)
raw_total_deaths_state_fed_df

,Jurisdiction,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,diff
0,Federal,301,399,376,387,387,350,400,444,455,388,381,378,77
1,State,2869,3452,3417,3233,3351,3357,3478,3484,3682,3729,3943,4135,1266
2,Alabama,87,75,80,66,104,86,107,102,112,118,116,125,38
3,Alaska/c,8,14,7,13,12,11,8,12,15,10,9,11,3
4,Arizona,64,77,85,85,86,87,95,99,105,126,133,131,67
5,Arkansas,42,41,50,54,50,43,56,57,54,71,81,76,34
6,California,287,371,395,414,388,368,365,317,353,334,384,449,162
7,Colorado,42,38,49,48,37,48,40,35,51,57,41,55,13
8,Connecticut/d,30,32,29,21,19,24,20,24,23,17,14,28,-2
9,Delaware/d,16,15,12,23,15,10,14,18,17,14,10,16,0
10,Florida,182,291,278,275,297,324,305,346,354,356,428,440,258
11,Georgia,93,128,125,112,121,103,122,121,131,133,173,163,70
12,Hawaii/d,7,14,11,12,6,12,14,8,4,9,4,6,-1
13,Idaho,17,18,13,13,13,9,10,23,18,16,15,22,5
14,Illinois,86,71,75,94,97,85,78,88,120,90,104,83,-3
15,Indiana,46,70,91,69,74,59,66,70,85,70,68,67,21
16,Iowa,9,21,14,13,12,20,16,15,19,29,16,19,10
17,Kansas,21,24,20,22,25,17,28,21,25,35,26,33,12
18,Kentucky,36,68,57,42,60,55,40,44,60,42,70,50,14
19,Louisiana,71,117,108,100,108,116,118,118,113,123,115,114,43
20,Maine,6,2,4,3,5,2,3,7,5,5,4,8,2
21,Maryland,70,69,56,40,41,46,58,43,62,49,57,57,-13
22,Massachusetts,29,29,29,39,33,42,39,45,34,34,37,42,13
23,Michigan,114,99,148,93,119,124,124,121,118,106,106,135,21
24,Minnesota,13,17,12,16,19,14,20,14,11,18,6,6,-7
25,Mississippi,36,54,52,52,47,41,68,50,45,65,77,76,40
26,Missouri,57,87,81,88,74,71,92,97,106,99,94,106,49
27,Montana,6,9,3,2,6,11,7,19,13,16,13,5,-1
28,Nebraska,7,6,11,12,17,11,16,13,17,9,16,10,3
29,Nevada,27,35,35,41,34,37,35,44,47,42,47,29,2
30,New Hampshire,2,5,9,4,10,5,8,5,8,9,5,8,6
31,New Jersey,69,66,58,56,66,48,46,50,52,49,39,33,-36
32,New Mexico,11,29,21,16,16,14,17,24,19,16,18,22,11
33,New York,175,133,142,124,117,115,142,123,115,147,143,138,-37
34,North Carolina,66,117,86,87,71,79,81,94,90,127,104,118,52
35,North Dakota,3,0,0,1,1,3,1,0,0,4,2,0,-3
36,Ohio,115,101,120,116,111,126,124,111,138,133,149,151,36
37,Oklahoma,51,88,79,60,85,79,87,107,107,93,86,113,62
38,Oregon,24,31,34,39,40,26,30,31,37,47,25,34,10
39,Pennsylvania,122,145,165,141,157,157,157,145,166,171,181,166,44
40,Rhode Island/d,3,6,7,7,10,6,4,7,5,2,8,5,2
41,South Carolina,69,83,49,70,55,58,66,66,76,79,105,100,31
42,South Dakota,4,6,4,8,11,9,6,7,7,5,12,6,2
43,Tennessee,51,74,69,74,59,84,82,83,94,102,96,121,70
44,Texas,408,469,426,375,417,462,438,409,418,403,469,505,97
45,Utah,5,11,17,13,12,15,23,23,16,21,20,17,12
46,Vermont/d,3,3,3,5,0,2,8,6,4,7,4,2,-1
47,Virginia,71,86,87,93,99,86,82,90,90,90,93,106,35
48,Washington,29,35,44,35,21,33,39,38,42,28,40,36,7
49,West Virginia,17,19,18,20,23,24,26,24,28,26,29,34,17
50,Wisconsin,48,44,42,25,48,46,43,58,46,66,43,52,4
51,Wyoming,5,9,7,2,3,4,4,12,7,11,8,6,1

In [156]:
##Raw numbers have Florida with nearly 260 more deaths in 2018 than 2001. New Hampshire from 2 to 8, important context.
raw_total_deaths_state_fed_df.sort_values(by="diff", ascending = False)

,Jurisdiction,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,diff
1,State,2869,3452,3417,3233,3351,3357,3478,3484,3682,3729,3943,4135,1266
10,Florida,182,291,278,275,297,324,305,346,354,356,428,440,258
6,California,287,371,395,414,388,368,365,317,353,334,384,449,162
44,Texas,408,469,426,375,417,462,438,409,418,403,469,505,97
0,Federal,301,399,376,387,387,350,400,444,455,388,381,378,77
43,Tennessee,51,74,69,74,59,84,82,83,94,102,96,121,70
11,Georgia,93,128,125,112,121,103,122,121,131,133,173,163,70
4,Arizona,64,77,85,85,86,87,95,99,105,126,133,131,67
37,Oklahoma,51,88,79,60,85,79,87,107,107,93,86,113,62
34,North Carolina,66,117,86,87,71,79,81,94,90,127,104,118,52
26,Missouri,57,87,81,88,74,71,92,97,106,99,94,106,49
39,Pennsylvania,122,145,165,141,157,157,157,145,166,171,181,166,44
19,Louisiana,71,117,108,100,108,116,118,118,113,123,115,114,43
25,Mississippi,36,54,52,52,47,41,68,50,45,65,77,76,40
2,Alabama,87,75,80,66,104,86,107,102,112,118,116,125,38
36,Ohio,115,101,120,116,111,126,124,111,138,133,149,151,36
47,Virginia,71,86,87,93,99,86,82,90,90,90,93,106,35
5,Arkansas,42,41,50,54,50,43,56,57,54,71,81,76,34
41,South Carolina,69,83,49,70,55,58,66,66,76,79,105,100,31
23,Michigan,114,99,148,93,119,124,124,121,118,106,106,135,21
15,Indiana,46,70,91,69,74,59,66,70,85,70,68,67,21
49,West Virginia,17,19,18,20,23,24,26,24,28,26,29,34,17
18,Kentucky,36,68,57,42,60,55,40,44,60,42,70,50,14
22,Massachusetts,29,29,29,39,33,42,39,45,34,34,37,42,13
7,Colorado,42,38,49,48,37,48,40,35,51,57,41,55,13
17,Kansas,21,24,20,22,25,17,28,21,25,35,26,33,12
45,Utah,5,11,17,13,12,15,23,23,16,21,20,17,12
32,New Mexico,11,29,21,16,16,14,17,24,19,16,18,22,11
16,Iowa,9,21,14,13,12,20,16,15,19,29,16,19,10
38,Oregon,24,31,34,39,40,26,30,31,37,47,25,34,10
48,Washington,29,35,44,35,21,33,39,38,42,28,40,36,7
30,New Hampshire,2,5,9,4,10,5,8,5,8,9,5,8,6
13,Idaho,17,18,13,13,13,9,10,23,18,16,15,22,5
50,Wisconsin,48,44,42,25,48,46,43,58,46,66,43,52,4
28,Nebraska,7,6,11,12,17,11,16,13,17,9,16,10,3
3,Alaska/c,8,14,7,13,12,11,8,12,15,10,9,11,3
40,Rhode Island/d,3,6,7,7,10,6,4,7,5,2,8,5,2
42,South Dakota,4,6,4,8,11,9,6,7,7,5,12,6,2
29,Nevada,27,35,35,41,34,37,35,44,47,42,47,29,2
20,Maine,6,2,4,3,5,2,3,7,5,5,4,8,2
51,Wyoming,5,9,7,2,3,4,4,12,7,11,8,6,1
9,Delaware/d,16,15,12,23,15,10,14,18,17,14,10,16,0
12,Hawaii/d,7,14,11,12,6,12,14,8,4,9,4,6,-1
27,Montana,6,9,3,2,6,11,7,19,13,16,13,5,-1
46,Vermont/d,3,3,3,5,0,2,8,6,4,7,4,2,-1
8,Connecticut/d,30,32,29,21,19,24,20,24,23,17,14,28,-2
35,North Dakota,3,0,0,1,1,3,1,0,0,4,2,0,-3
14,Illinois,86,71,75,94,97,85,78,88,120,90,104,83,-3
24,Minnesota,13,17,12,16,19,14,20,14,11,18,6,6,-7
21,Maryland,70,69,56,40,41,46,58,43,62,49,57,57,-13
31,New Jersey,69,66,58,56,66,48,46,50,52,49,39,33,-36
33,New York,175,133,142,124,117,115,142,123,115,147,143,138,-37

In [157]:
raw_total_deaths_state_fed_df["pct_chg"] = raw_total_deaths_state_fed_df.apply(lambda x: ((x["2018"] - x["2001"])/x["2001"])*100, axis = 1)
raw_total_deaths_state_fed_df

,Jurisdiction,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,diff,pct_chg
0,Federal,301,399,376,387,387,350,400,444,455,388,381,378,77,25.581395
1,State,2869,3452,3417,3233,3351,3357,3478,3484,3682,3729,3943,4135,1266,44.126873
2,Alabama,87,75,80,66,104,86,107,102,112,118,116,125,38,43.678161
3,Alaska/c,8,14,7,13,12,11,8,12,15,10,9,11,3,37.500000
4,Arizona,64,77,85,85,86,87,95,99,105,126,133,131,67,104.687500
5,Arkansas,42,41,50,54,50,43,56,57,54,71,81,76,34,80.952381
6,California,287,371,395,414,388,368,365,317,353,334,384,449,162,56.445993
7,Colorado,42,38,49,48,37,48,40,35,51,57,41,55,13,30.952381
8,Connecticut/d,30,32,29,21,19,24,20,24,23,17,14,28,-2,-6.666667
9,Delaware/d,16,15,12,23,15,10,14,18,17,14,10,16,0,0.000000
10,Florida,182,291,278,275,297,324,305,346,354,356,428,440,258,141.758242
11,Georgia,93,128,125,112,121,103,122,121,131,133,173,163,70,75.268817
12,Hawaii/d,7,14,11,12,6,12,14,8,4,9,4,6,-1,-14.285714
13,Idaho,17,18,13,13,13,9,10,23,18,16,15,22,5,29.411765
14,Illinois,86,71,75,94,97,85,78,88,120,90,104,83,-3,-3.488372
15,Indiana,46,70,91,69,74,59,66,70,85,70,68,67,21,45.652174
16,Iowa,9,21,14,13,12,20,16,15,19,29,16,19,10,111.111111
17,Kansas,21,24,20,22,25,17,28,21,25,35,26,33,12,57.142857
18,Kentucky,36,68,57,42,60,55,40,44,60,42,70,50,14,38.888889
19,Louisiana,71,117,108,100,108,116,118,118,113,123,115,114,43,60.563380
20,Maine,6,2,4,3,5,2,3,7,5,5,4,8,2,33.333333
21,Maryland,70,69,56,40,41,46,58,43,62,49,57,57,-13,-18.571429
22,Massachusetts,29,29,29,39,33,42,39,45,34,34,37,42,13,44.827586
23,Michigan,114,99,148,93,119,124,124,121,118,106,106,135,21,18.421053
24,Minnesota,13,17,12,16,19,14,20,14,11,18,6,6,-7,-53.846154
25,Mississippi,36,54,52,52,47,41,68,50,45,65,77,76,40,111.111111
26,Missouri,57,87,81,88,74,71,92,97,106,99,94,106,49,85.964912
27,Montana,6,9,3,2,6,11,7,19,13,16,13,5,-1,-16.666667
28,Nebraska,7,6,11,12,17,11,16,13,17,9,16,10,3,42.857143
29,Nevada,27,35,35,41,34,37,35,44,47,42,47,29,2,7.407407
30,New Hampshire,2,5,9,4,10,5,8,5,8,9,5,8,6,300.000000
31,New Jersey,69,66,58,56,66,48,46,50,52,49,39,33,-36,-52.173913
32,New Mexico,11,29,21,16,16,14,17,24,19,16,18,22,11,100.000000
33,New York,175,133,142,124,117,115,142,123,115,147,143,138,-37,-21.142857
34,North Carolina,66,117,86,87,71,79,81,94,90,127,104,118,52,78.787879
35,North Dakota,3,0,0,1,1,3,1,0,0,4,2,0,-3,-100.000000
36,Ohio,115,101,120,116,111,126,124,111,138,133,149,151,36,31.304348
37,Oklahoma,51,88,79,60,85,79,87,107,107,93,86,113,62,121.568627
38,Oregon,24,31,34,39,40,26,30,31,37,47,25,34,10,41.666667
39,Pennsylvania,122,145,165,141,157,157,157,145,166,171,181,166,44,36.065574
40,Rhode Island/d,3,6,7,7,10,6,4,7,5,2,8,5,2,66.666667
41,South Carolina,69,83,49,70,55,58,66,66,76,79,105,100,31,44.927536
42,South Dakota,4,6,4,8,11,9,6,7,7,5,12,6,2,50.000000
43,Tennessee,51,74,69,74,59,84,82,83,94,102,96,121,70,137.254902
44,Texas,408,469,426,375,417,462,438,409,418,403,469,505,97,23.774510
45,Utah,5,11,17,13,12,15,23,23,16,21,20,17,12,240.000000
46,Vermont/d,3,3,3,5,0,2,8,6,4,7,4,2,-1,-33.333333
47,Virginia,71,86,87,93,99,86,82,90,90,90,93,106,35,49.295775
48,Washington,29,35,44,35,21,33,39,38,42,28,40,36,7,24.137931
49,West Virginia,17,19,18,20,23,24,26,24,28,26,29,34,17,100.000000
50,Wisconsin,48,44,42,25,48,46,43,58,46,66,43,52,4,8.333333
51,Wyoming,5,9,7,2,3,4,4,12,7,11,8,6,1,20.000000

In [158]:
##Utah 5 to 17. Helps to know the raw numbers. AZ 64 to 131, but a growing place.
raw_total_deaths_state_fed_df.sort_values(by="pct_chg", ascending = False)

,Jurisdiction,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,diff,pct_chg
30,New Hampshire,2,5,9,4,10,5,8,5,8,9,5,8,6,300.000000
45,Utah,5,11,17,13,12,15,23,23,16,21,20,17,12,240.000000
10,Florida,182,291,278,275,297,324,305,346,354,356,428,440,258,141.758242
43,Tennessee,51,74,69,74,59,84,82,83,94,102,96,121,70,137.254902
37,Oklahoma,51,88,79,60,85,79,87,107,107,93,86,113,62,121.568627
16,Iowa,9,21,14,13,12,20,16,15,19,29,16,19,10,111.111111
25,Mississippi,36,54,52,52,47,41,68,50,45,65,77,76,40,111.111111
4,Arizona,64,77,85,85,86,87,95,99,105,126,133,131,67,104.687500
32,New Mexico,11,29,21,16,16,14,17,24,19,16,18,22,11,100.000000
49,West Virginia,17,19,18,20,23,24,26,24,28,26,29,34,17,100.000000
26,Missouri,57,87,81,88,74,71,92,97,106,99,94,106,49,85.964912
5,Arkansas,42,41,50,54,50,43,56,57,54,71,81,76,34,80.952381
34,North Carolina,66,117,86,87,71,79,81,94,90,127,104,118,52,78.787879
11,Georgia,93,128,125,112,121,103,122,121,131,133,173,163,70,75.268817
40,Rhode Island/d,3,6,7,7,10,6,4,7,5,2,8,5,2,66.666667
19,Louisiana,71,117,108,100,108,116,118,118,113,123,115,114,43,60.563380
17,Kansas,21,24,20,22,25,17,28,21,25,35,26,33,12,57.142857
6,California,287,371,395,414,388,368,365,317,353,334,384,449,162,56.445993
42,South Dakota,4,6,4,8,11,9,6,7,7,5,12,6,2,50.000000
47,Virginia,71,86,87,93,99,86,82,90,90,90,93,106,35,49.295775
15,Indiana,46,70,91,69,74,59,66,70,85,70,68,67,21,45.652174
41,South Carolina,69,83,49,70,55,58,66,66,76,79,105,100,31,44.927536
22,Massachusetts,29,29,29,39,33,42,39,45,34,34,37,42,13,44.827586
1,State,2869,3452,3417,3233,3351,3357,3478,3484,3682,3729,3943,4135,1266,44.126873
2,Alabama,87,75,80,66,104,86,107,102,112,118,116,125,38,43.678161
28,Nebraska,7,6,11,12,17,11,16,13,17,9,16,10,3,42.857143
38,Oregon,24,31,34,39,40,26,30,31,37,47,25,34,10,41.666667
18,Kentucky,36,68,57,42,60,55,40,44,60,42,70,50,14,38.888889
3,Alaska/c,8,14,7,13,12,11,8,12,15,10,9,11,3,37.500000
39,Pennsylvania,122,145,165,141,157,157,157,145,166,171,181,166,44,36.065574
20,Maine,6,2,4,3,5,2,3,7,5,5,4,8,2,33.333333
36,Ohio,115,101,120,116,111,126,124,111,138,133,149,151,36,31.304348
7,Colorado,42,38,49,48,37,48,40,35,51,57,41,55,13,30.952381
13,Idaho,17,18,13,13,13,9,10,23,18,16,15,22,5,29.411765
0,Federal,301,399,376,387,387,350,400,444,455,388,381,378,77,25.581395
48,Washington,29,35,44,35,21,33,39,38,42,28,40,36,7,24.137931
44,Texas,408,469,426,375,417,462,438,409,418,403,469,505,97,23.774510
51,Wyoming,5,9,7,2,3,4,4,12,7,11,8,6,1,20.000000
23,Michigan,114,99,148,93,119,124,124,121,118,106,106,135,21,18.421053
50,Wisconsin,48,44,42,25,48,46,43,58,46,66,43,52,4,8.333333
29,Nevada,27,35,35,41,34,37,35,44,47,42,47,29,2,7.407407
9,Delaware/d,16,15,12,23,15,10,14,18,17,14,10,16,0,0.000000
14,Illinois,86,71,75,94,97,85,78,88,120,90,104,83,-3,-3.488372
8,Connecticut/d,30,32,29,21,19,24,20,24,23,17,14,28,-2,-6.666667
12,Hawaii/d,7,14,11,12,6,12,14,8,4,9,4,6,-1,-14.285714
27,Montana,6,9,3,2,6,11,7,19,13,16,13,5,-1,-16.666667
21,Maryland,70,69,56,40,41,46,58,43,62,49,57,57,-13,-18.571429
33,New York,175,133,142,124,117,115,142,123,115,147,143,138,-37,-21.142857
46,Vermont/d,3,3,3,5,0,2,8,6,4,7,4,2,-1,-33.333333
31,New Jersey,69,66,58,56,66,48,46,50,52,49,39,33,-36,-52.173913
24,Minnesota,13,17,12,16,19,14,20,14,11,18,6,6,-7,-53.846154
35,North Dakota,3,0,0,1,1,3,1,0,0,4,2,0,-3,-100.000000

In [159]:
raw_total_deaths_state_fed_df = raw_total_deaths_state_fed_df.round(decimals = 2)

In [160]:
raw_total_deaths_state_fed_df

,Jurisdiction,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,diff,pct_chg
0,Federal,301,399,376,387,387,350,400,444,455,388,381,378,77,25.58
1,State,2869,3452,3417,3233,3351,3357,3478,3484,3682,3729,3943,4135,1266,44.13
2,Alabama,87,75,80,66,104,86,107,102,112,118,116,125,38,43.68
3,Alaska/c,8,14,7,13,12,11,8,12,15,10,9,11,3,37.50
4,Arizona,64,77,85,85,86,87,95,99,105,126,133,131,67,104.69
5,Arkansas,42,41,50,54,50,43,56,57,54,71,81,76,34,80.95
6,California,287,371,395,414,388,368,365,317,353,334,384,449,162,56.45
7,Colorado,42,38,49,48,37,48,40,35,51,57,41,55,13,30.95
8,Connecticut/d,30,32,29,21,19,24,20,24,23,17,14,28,-2,-6.67
9,Delaware/d,16,15,12,23,15,10,14,18,17,14,10,16,0,0.00
10,Florida,182,291,278,275,297,324,305,346,354,356,428,440,258,141.76
11,Georgia,93,128,125,112,121,103,122,121,131,133,173,163,70,75.27
12,Hawaii/d,7,14,11,12,6,12,14,8,4,9,4,6,-1,-14.29
13,Idaho,17,18,13,13,13,9,10,23,18,16,15,22,5,29.41
14,Illinois,86,71,75,94,97,85,78,88,120,90,104,83,-3,-3.49
15,Indiana,46,70,91,69,74,59,66,70,85,70,68,67,21,45.65
16,Iowa,9,21,14,13,12,20,16,15,19,29,16,19,10,111.11
17,Kansas,21,24,20,22,25,17,28,21,25,35,26,33,12,57.14
18,Kentucky,36,68,57,42,60,55,40,44,60,42,70,50,14,38.89
19,Louisiana,71,117,108,100,108,116,118,118,113,123,115,114,43,60.56
20,Maine,6,2,4,3,5,2,3,7,5,5,4,8,2,33.33
21,Maryland,70,69,56,40,41,46,58,43,62,49,57,57,-13,-18.57
22,Massachusetts,29,29,29,39,33,42,39,45,34,34,37,42,13,44.83
23,Michigan,114,99,148,93,119,124,124,121,118,106,106,135,21,18.42
24,Minnesota,13,17,12,16,19,14,20,14,11,18,6,6,-7,-53.85
25,Mississippi,36,54,52,52,47,41,68,50,45,65,77,76,40,111.11
26,Missouri,57,87,81,88,74,71,92,97,106,99,94,106,49,85.96
27,Montana,6,9,3,2,6,11,7,19,13,16,13,5,-1,-16.67
28,Nebraska,7,6,11,12,17,11,16,13,17,9,16,10,3,42.86
29,Nevada,27,35,35,41,34,37,35,44,47,42,47,29,2,7.41
30,New Hampshire,2,5,9,4,10,5,8,5,8,9,5,8,6,300.00
31,New Jersey,69,66,58,56,66,48,46,50,52,49,39,33,-36,-52.17
32,New Mexico,11,29,21,16,16,14,17,24,19,16,18,22,11,100.00
33,New York,175,133,142,124,117,115,142,123,115,147,143,138,-37,-21.14
34,North Carolina,66,117,86,87,71,79,81,94,90,127,104,118,52,78.79
35,North Dakota,3,0,0,1,1,3,1,0,0,4,2,0,-3,-100.00
36,Ohio,115,101,120,116,111,126,124,111,138,133,149,151,36,31.30
37,Oklahoma,51,88,79,60,85,79,87,107,107,93,86,113,62,121.57
38,Oregon,24,31,34,39,40,26,30,31,37,47,25,34,10,41.67
39,Pennsylvania,122,145,165,141,157,157,157,145,166,171,181,166,44,36.07
40,Rhode Island/d,3,6,7,7,10,6,4,7,5,2,8,5,2,66.67
41,South Carolina,69,83,49,70,55,58,66,66,76,79,105,100,31,44.93
42,South Dakota,4,6,4,8,11,9,6,7,7,5,12,6,2,50.00
43,Tennessee,51,74,69,74,59,84,82,83,94,102,96,121,70,137.25
44,Texas,408,469,426,375,417,462,438,409,418,403,469,505,97,23.77
45,Utah,5,11,17,13,12,15,23,23,16,21,20,17,12,240.00
46,Vermont/d,3,3,3,5,0,2,8,6,4,7,4,2,-1,-33.33
47,Virginia,71,86,87,93,99,86,82,90,90,90,93,106,35,49.30
48,Washington,29,35,44,35,21,33,39,38,42,28,40,36,7,24.14
49,West Virginia,17,19,18,20,23,24,26,24,28,26,29,34,17,100.00
50,Wisconsin,48,44,42,25,48,46,43,58,46,66,43,52,4,8.33
51,Wyoming,5,9,7,2,3,4,4,12,7,11,8,6,1,20.00

In [161]:
raw_total_deaths_state_fed_df.sort_values(by="pct_chg", ascending = False)

,Jurisdiction,2001,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,diff,pct_chg
30,New Hampshire,2,5,9,4,10,5,8,5,8,9,5,8,6,300.00
45,Utah,5,11,17,13,12,15,23,23,16,21,20,17,12,240.00
10,Florida,182,291,278,275,297,324,305,346,354,356,428,440,258,141.76
43,Tennessee,51,74,69,74,59,84,82,83,94,102,96,121,70,137.25
37,Oklahoma,51,88,79,60,85,79,87,107,107,93,86,113,62,121.57
16,Iowa,9,21,14,13,12,20,16,15,19,29,16,19,10,111.11
25,Mississippi,36,54,52,52,47,41,68,50,45,65,77,76,40,111.11
4,Arizona,64,77,85,85,86,87,95,99,105,126,133,131,67,104.69
32,New Mexico,11,29,21,16,16,14,17,24,19,16,18,22,11,100.00
49,West Virginia,17,19,18,20,23,24,26,24,28,26,29,34,17,100.00
26,Missouri,57,87,81,88,74,71,92,97,106,99,94,106,49,85.96
5,Arkansas,42,41,50,54,50,43,56,57,54,71,81,76,34,80.95
34,North Carolina,66,117,86,87,71,79,81,94,90,127,104,118,52,78.79
11,Georgia,93,128,125,112,121,103,122,121,131,133,173,163,70,75.27
40,Rhode Island/d,3,6,7,7,10,6,4,7,5,2,8,5,2,66.67
19,Louisiana,71,117,108,100,108,116,118,118,113,123,115,114,43,60.56
17,Kansas,21,24,20,22,25,17,28,21,25,35,26,33,12,57.14
6,California,287,371,395,414,388,368,365,317,353,334,384,449,162,56.45
42,South Dakota,4,6,4,8,11,9,6,7,7,5,12,6,2,50.00
47,Virginia,71,86,87,93,99,86,82,90,90,90,93,106,35,49.30
15,Indiana,46,70,91,69,74,59,66,70,85,70,68,67,21,45.65
41,South Carolina,69,83,49,70,55,58,66,66,76,79,105,100,31,44.93
22,Massachusetts,29,29,29,39,33,42,39,45,34,34,37,42,13,44.83
1,State,2869,3452,3417,3233,3351,3357,3478,3484,3682,3729,3943,4135,1266,44.13
2,Alabama,87,75,80,66,104,86,107,102,112,118,116,125,38,43.68
28,Nebraska,7,6,11,12,17,11,16,13,17,9,16,10,3,42.86
38,Oregon,24,31,34,39,40,26,30,31,37,47,25,34,10,41.67
18,Kentucky,36,68,57,42,60,55,40,44,60,42,70,50,14,38.89
3,Alaska/c,8,14,7,13,12,11,8,12,15,10,9,11,3,37.50
39,Pennsylvania,122,145,165,141,157,157,157,145,166,171,181,166,44,36.07
20,Maine,6,2,4,3,5,2,3,7,5,5,4,8,2,33.33
36,Ohio,115,101,120,116,111,126,124,111,138,133,149,151,36,31.30
7,Colorado,42,38,49,48,37,48,40,35,51,57,41,55,13,30.95
13,Idaho,17,18,13,13,13,9,10,23,18,16,15,22,5,29.41
0,Federal,301,399,376,387,387,350,400,444,455,388,381,378,77,25.58
48,Washington,29,35,44,35,21,33,39,38,42,28,40,36,7,24.14
44,Texas,408,469,426,375,417,462,438,409,418,403,469,505,97,23.77
51,Wyoming,5,9,7,2,3,4,4,12,7,11,8,6,1,20.00
23,Michigan,114,99,148,93,119,124,124,121,118,106,106,135,21,18.42
50,Wisconsin,48,44,42,25,48,46,43,58,46,66,43,52,4,8.33
29,Nevada,27,35,35,41,34,37,35,44,47,42,47,29,2,7.41
9,Delaware/d,16,15,12,23,15,10,14,18,17,14,10,16,0,0.00
14,Illinois,86,71,75,94,97,85,78,88,120,90,104,83,-3,-3.49
8,Connecticut/d,30,32,29,21,19,24,20,24,23,17,14,28,-2,-6.67
12,Hawaii/d,7,14,11,12,6,12,14,8,4,9,4,6,-1,-14.29
27,Montana,6,9,3,2,6,11,7,19,13,16,13,5,-1,-16.67
21,Maryland,70,69,56,40,41,46,58,43,62,49,57,57,-13,-18.57
33,New York,175,133,142,124,117,115,142,123,115,147,143,138,-37,-21.14
46,Vermont/d,3,3,3,5,0,2,8,6,4,7,4,2,-1,-33.33
31,New Jersey,69,66,58,56,66,48,46,50,52,49,39,33,-36,-52.17
24,Minnesota,13,17,12,16,19,14,20,14,11,18,6,6,-7,-53.85
35,North Dakota,3,0,0,1,1,3,1,0,0,4,2,0,-3,-100.00

In [162]:
us_death_rates_df = pd.read_csv("US_Death_Rates.csv")

In [163]:
us_death_rates_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   State                            50 non-null     object
 1   State causes                     50 non-null     float64
 2   State heart disease              50 non-null     float64
 3   State cancer                     50 non-null     float64
 4   State liver disease              50 non-null     float64
 5   State respiratory disease        50 non-null     float64
 6   State suicide                    50 non-null     float64
 7   State drug/alcohol intoxication  50 non-null     float64
 8   State accident                   50 non-null     float64
 9   State homocide                   50 non-null     float64
dtypes: float64(9), object(1)
memory usage: 4.0+ KB

In [164]:
##Reading in death rates for states general populations
us_death_rates_df

,State,State causes,State heart disease,State cancer,State liver disease,State respiratory disease,State suicide,State drug/alcohol intoxication,State accident,State homocide
0,Alabama,1316.2,237.5,170.3,15.9,52.9,16.0,22.3,59.6,14.2
1,Alaska,707.1,139.8,142.3,22.4,31.0,27.5,22.0,65.5,7.3
2,Arizona,1020.7,144.8,132.0,16.8,36.6,17.6,35.8,69.1,7.5
3,Arkansas,1257.5,222.5,168.8,14.9,60.4,19.0,19.1,58.0,13.0
4,California,812.4,144.0,135.3,13.9,28.1,10.0,21.8,44.1,6.1
5,Colorado,807.9,128.1,128.2,17.7,39.3,21.5,24.9,60.5,5.8
6,Connecticut,1064.2,138.4,134.3,12.4,24.4,9.3,39.1,63.5,4.6
7,Delaware,1122.0,159.6,159.3,10.8,32.7,12.3,47.3,70.9,9.9
8,Florida,1102.8,143.1,141.3,13.0,33.4,13.2,35.0,67.7,7.8
9,Georgia,962.4,183.7,152.8,12.1,41.6,13.7,18.0,50.8,10.5
10,Hawaii,855.2,125.0,122.9,8.2,17.8,12.9,18.3,39.4,3.3
11,Idaho,897.8,151.9,150.1,15.5,39.4,23.2,15.9,50.8,2.5
12,Illinois,1053.9,171.4,153.6,11.4,34.0,10.5,28.1,53.4,11.2
13,Indiana,1157.6,183.9,166.1,14.8,53.7,15.0,36.7,66.9,9.7
14,Iowa,1137.4,172.9,155.4,11.4,39.4,18.0,14.3,45.7,3.6
15,Kansas,1100.3,167.0,156.8,14.1,43.9,18.4,17.4,53.4,7.0
16,Kentucky,1248.1,204.5,181.8,17.0,56.2,17.7,49.2,87.5,9.5
17,Louisiana,1221.7,221.5,168.9,10.8,41.6,13.7,42.7,79.4,19.9
18,Maine,1165.8,146.2,161.3,13.9,41.5,16.4,39.7,76.9,1.6
19,Maryland,992.0,168.3,150.1,9.5,27.7,9.2,44.6,44.4,11.4
20,Massachusetts,989.7,126.9,143.1,11.2,27.8,8.4,33.9,54.3,2.7
21,Michigan,1175.0,205.0,161.4,13.9,41.9,14.0,28.6,56.8,8.7
22,Minnesota,925.7,118.1,143.3,13.7,30.6,13.1,19.0,52.6,3.6
23,Mississippi,1354.7,245.6,179.9,15.7,59.2,13.9,21.1,73.0,20.5
24,Missouri,1201.1,196.7,165.2,12.3,47.0,18.2,32.1,68.4,14.0
25,Montana,1113.0,162.7,140.9,19.1,42.4,26.1,15.6,61.9,6.6
26,Nebraska,1009.0,143.8,150.8,13.4,43.4,14.9,11.3,42.3,4.1
27,Nevada,975.6,201.3,146.9,15.2,44.9,18.2,26.0,53.5,7.3
28,New Hampshire,1002.7,146.5,144.6,11.9,33.4,16.4,30.3,58.1,0.0
29,New Jersey,1080.8,166.3,140.9,9.1,25.0,7.1,32.1,50.3,4.3
30,New Mexico,1130.3,152.7,136.8,33.4,41.3,24.2,39.0,85.5,10.8
31,New York,1051.6,183.9,137.8,8.0,25.5,8.0,25.4,41.7,4.7
32,North Carolina,1032.5,156.2,154.3,12.9,38.5,13.2,30.9,67.1,8.6
33,North Dakota,1052.1,147.3,145.7,17.7,34.6,18.2,15.6,51.9,4.4
34,Ohio,1228.9,196.9,165.1,12.5,44.6,13.8,47.2,78.2,9.1
35,Oklahoma,1201.0,244.1,178.0,17.6,60.1,21.9,19.4,62.0,9.0
36,Oregon,948.2,134.0,150.9,15.8,34.6,18.3,18.7,52.0,3.8
37,Pennsylvania,1216.8,175.7,156.4,9.9,32.8,12.6,42.4,69.0,8.5
38,Rhode Island,1118.0,150.5,151.7,13.9,29.5,8.5,38.2,65.6,3.0
39,South Carolina,1173.3,170.9,157.5,15.6,43.6,16.3,34.9,77.8,12.7
40,South Dakota,1104.6,155.2,145.9,25.4,36.9,21.0,10.3,58.5,6.5
41,Tennessee,1222.7,212.0,168.2,16.2,51.2,17.2,45.6,86.5,11.5
42,Texas,852.6,173.9,143.5,15.8,36.2,13.3,14.1,44.2,7.6
43,Utah,661.5,155.6,120.8,10.3,32.7,20.8,20.5,49.4,2.9
44,Vermont,1036.2,167.1,156.2,11.3,37.4,18.1,32.9,67.1,0.0
45,Virginia,938.2,152.0,149.4,11.8,32.8,13.5,26.6,52.5,6.4
46,Washington,820.8,134.6,145.7,14.2,29.6,15.2,22.0,51.3,4.2
47,West Virginia,1462.7,197.8,178.5,16.1,59.5,19.4,81.4,122.2,7.0
48,Wisconsin,1075.1,162.2,151.8,12.2,35.6,14.5,27.7,71.5,6.1
49,Wyoming,1027.4,160.4,140.6,27.3,53.5,30.5,17.4,60.4,4.9

In [165]:
##Fixing spelling
us_death_rates_df = us_death_rates_df.rename(columns={"State homocide": "State homicide"})
us_death_rates_df

,State,State causes,State heart disease,State cancer,State liver disease,State respiratory disease,State suicide,State drug/alcohol intoxication,State accident,State homicide
0,Alabama,1316.2,237.5,170.3,15.9,52.9,16.0,22.3,59.6,14.2
1,Alaska,707.1,139.8,142.3,22.4,31.0,27.5,22.0,65.5,7.3
2,Arizona,1020.7,144.8,132.0,16.8,36.6,17.6,35.8,69.1,7.5
3,Arkansas,1257.5,222.5,168.8,14.9,60.4,19.0,19.1,58.0,13.0
4,California,812.4,144.0,135.3,13.9,28.1,10.0,21.8,44.1,6.1
5,Colorado,807.9,128.1,128.2,17.7,39.3,21.5,24.9,60.5,5.8
6,Connecticut,1064.2,138.4,134.3,12.4,24.4,9.3,39.1,63.5,4.6
7,Delaware,1122.0,159.6,159.3,10.8,32.7,12.3,47.3,70.9,9.9
8,Florida,1102.8,143.1,141.3,13.0,33.4,13.2,35.0,67.7,7.8
9,Georgia,962.4,183.7,152.8,12.1,41.6,13.7,18.0,50.8,10.5
10,Hawaii,855.2,125.0,122.9,8.2,17.8,12.9,18.3,39.4,3.3
11,Idaho,897.8,151.9,150.1,15.5,39.4,23.2,15.9,50.8,2.5
12,Illinois,1053.9,171.4,153.6,11.4,34.0,10.5,28.1,53.4,11.2
13,Indiana,1157.6,183.9,166.1,14.8,53.7,15.0,36.7,66.9,9.7
14,Iowa,1137.4,172.9,155.4,11.4,39.4,18.0,14.3,45.7,3.6
15,Kansas,1100.3,167.0,156.8,14.1,43.9,18.4,17.4,53.4,7.0
16,Kentucky,1248.1,204.5,181.8,17.0,56.2,17.7,49.2,87.5,9.5
17,Louisiana,1221.7,221.5,168.9,10.8,41.6,13.7,42.7,79.4,19.9
18,Maine,1165.8,146.2,161.3,13.9,41.5,16.4,39.7,76.9,1.6
19,Maryland,992.0,168.3,150.1,9.5,27.7,9.2,44.6,44.4,11.4
20,Massachusetts,989.7,126.9,143.1,11.2,27.8,8.4,33.9,54.3,2.7
21,Michigan,1175.0,205.0,161.4,13.9,41.9,14.0,28.6,56.8,8.7
22,Minnesota,925.7,118.1,143.3,13.7,30.6,13.1,19.0,52.6,3.6
23,Mississippi,1354.7,245.6,179.9,15.7,59.2,13.9,21.1,73.0,20.5
24,Missouri,1201.1,196.7,165.2,12.3,47.0,18.2,32.1,68.4,14.0
25,Montana,1113.0,162.7,140.9,19.1,42.4,26.1,15.6,61.9,6.6
26,Nebraska,1009.0,143.8,150.8,13.4,43.4,14.9,11.3,42.3,4.1
27,Nevada,975.6,201.3,146.9,15.2,44.9,18.2,26.0,53.5,7.3
28,New Hampshire,1002.7,146.5,144.6,11.9,33.4,16.4,30.3,58.1,0.0
29,New Jersey,1080.8,166.3,140.9,9.1,25.0,7.1,32.1,50.3,4.3
30,New Mexico,1130.3,152.7,136.8,33.4,41.3,24.2,39.0,85.5,10.8
31,New York,1051.6,183.9,137.8,8.0,25.5,8.0,25.4,41.7,4.7
32,North Carolina,1032.5,156.2,154.3,12.9,38.5,13.2,30.9,67.1,8.6
33,North Dakota,1052.1,147.3,145.7,17.7,34.6,18.2,15.6,51.9,4.4
34,Ohio,1228.9,196.9,165.1,12.5,44.6,13.8,47.2,78.2,9.1
35,Oklahoma,1201.0,244.1,178.0,17.6,60.1,21.9,19.4,62.0,9.0
36,Oregon,948.2,134.0,150.9,15.8,34.6,18.3,18.7,52.0,3.8
37,Pennsylvania,1216.8,175.7,156.4,9.9,32.8,12.6,42.4,69.0,8.5
38,Rhode Island,1118.0,150.5,151.7,13.9,29.5,8.5,38.2,65.6,3.0
39,South Carolina,1173.3,170.9,157.5,15.6,43.6,16.3,34.9,77.8,12.7
40,South Dakota,1104.6,155.2,145.9,25.4,36.9,21.0,10.3,58.5,6.5
41,Tennessee,1222.7,212.0,168.2,16.2,51.2,17.2,45.6,86.5,11.5
42,Texas,852.6,173.9,143.5,15.8,36.2,13.3,14.1,44.2,7.6
43,Utah,661.5,155.6,120.8,10.3,32.7,20.8,20.5,49.4,2.9
44,Vermont,1036.2,167.1,156.2,11.3,37.4,18.1,32.9,67.1,0.0
45,Virginia,938.2,152.0,149.4,11.8,32.8,13.5,26.6,52.5,6.4
46,Washington,820.8,134.6,145.7,14.2,29.6,15.2,22.0,51.3,4.2
47,West Virginia,1462.7,197.8,178.5,16.1,59.5,19.4,81.4,122.2,7.0
48,Wisconsin,1075.1,162.2,151.8,12.2,35.6,14.5,27.7,71.5,6.1
49,Wyoming,1027.4,160.4,140.6,27.3,53.5,30.5,17.4,60.4,4.9

In [166]:
rate_state_dc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Jurisdiction               50 non-null     object
 1   All causes                 50 non-null     int64
 2   Heart disease              50 non-null     int64
 3   Cancer                     50 non-null     int64
 4   Liver disease              50 non-null     int64
 5   AIDS-related               50 non-null     int64
 6   Respiratory                50 non-null     int64
 7   All other illnesses        50 non-null     int64
 8   Suicide                    50 non-null     int64
 9   Drug/alcohol intoxication  50 non-null     int64
 10  Accident                   50 non-null     int64
 11  Homicide                   50 non-null     int64
dtypes: int64(11), object(1)
memory usage: 4.8+ KB

In [167]:
##Combining death rates for prison pops and general pops. "State" is general population.
combined_df = pd.concat([rate_state_dc_df, us_death_rates_df], axis=1)

In [168]:
combined_df

,Jurisdiction,All causes,Heart disease,Cancer,Liver disease,AIDS-related,Respiratory,All other illnesses,Suicide,Drug/alcohol intoxication,...,State,State causes,State heart disease,State cancer,State liver disease,State respiratory disease,State suicide,State drug/alcohol intoxication,State accident,State homicide
0,Alabama,352,81,89,30,8,24,63,9,3,...,Alabama,1316.2,237.5,170.3,15.9,52.9,16.0,22.3,59.6,14.2
1,Alaska,194,46,31,19,1,4,26,37,11,...,Alaska,707.1,139.8,142.3,22.4,31.0,27.5,22.0,65.5,7.3
2,Arizona,237,56,62,30,5,13,30,17,11,...,Arizona,1020.7,144.8,132.0,16.8,36.6,17.6,35.8,69.1,7.5
3,Arkansas,363,122,97,26,10,18,37,21,17,...,Arkansas,1257.5,222.5,168.8,14.9,60.4,19.0,19.1,58.0,13.0
4,California,244,42,60,24,4,17,50,21,12,...,California,812.4,144.0,135.3,13.9,28.1,10.0,21.8,44.1,6.1
5,Colorado,217,42,44,35,0,16,39,20,9,...,Colorado,807.9,128.1,128.2,17.7,39.3,21.5,24.9,60.5,5.8
6,Connecticut,151,37,21,21,4,9,31,24,1,...,Connecticut,1064.2,138.4,134.3,12.4,24.4,9.3,39.1,63.5,4.6
7,Delaware,230,58,53,21,17,12,28,27,5,...,Delaware,1122.0,159.6,159.3,10.8,32.7,12.3,47.3,70.9,9.9
8,Florida,313,67,92,24,18,21,55,10,10,...,Florida,1102.8,143.1,141.3,13.0,33.4,13.2,35.0,67.7,7.8
9,Georgia,237,79,60,13,9,19,30,13,1,...,Georgia,962.4,183.7,152.8,12.1,41.6,13.7,18.0,50.8,10.5
10,Hawaii,169,31,44,18,4,7,24,29,4,...,Hawaii,855.2,125.0,122.9,8.2,17.8,12.9,18.3,39.4,3.3
11,Idaho,215,56,53,19,3,11,31,28,4,...,Idaho,897.8,151.9,150.1,15.5,39.4,23.2,15.9,50.8,2.5
12,Illinois,195,56,62,10,8,11,26,16,2,...,Illinois,1053.9,171.4,153.6,11.4,34.0,10.5,28.1,53.4,11.2
13,Indiana,255,68,69,22,5,17,37,17,9,...,Indiana,1157.6,183.9,166.1,14.8,53.7,15.0,36.7,66.9,9.7
14,Iowa,183,40,63,11,3,18,22,20,2,...,Iowa,1137.4,172.9,155.4,11.4,39.4,18.0,14.3,45.7,3.6
15,Kansas,264,73,76,30,1,18,39,16,4,...,Kansas,1100.3,167.0,156.8,14.1,43.9,18.4,17.4,53.4,7.0
16,Kentucky,373,125,118,27,13,19,55,9,1,...,Kentucky,1248.1,204.5,181.8,17.0,56.2,17.7,49.2,87.5,9.5
17,Louisiana,535,165,162,41,32,25,68,12,1,...,Louisiana,1221.7,221.5,168.9,10.8,41.6,13.7,42.7,79.4,19.9
18,Maine,198,62,48,16,3,16,21,11,5,...,Maine,1165.8,146.2,161.3,13.9,41.5,16.4,39.7,76.9,1.6
19,Maryland,260,65,55,21,27,11,29,20,16,...,Maryland,992.0,168.3,150.1,9.5,27.7,9.2,44.6,44.4,11.4
20,Massachusetts,336,92,92,34,5,15,49,31,5,...,Massachusetts,989.7,126.9,143.1,11.2,27.8,8.4,33.9,54.3,2.7
21,Michigan,265,79,90,21,5,15,27,16,4,...,Michigan,1175.0,205.0,161.4,13.9,41.9,14.0,28.6,56.8,8.7
22,Minnesota,148,30,44,20,1,6,27,16,3,...,Minnesota,925.7,118.1,143.3,13.7,30.6,13.1,19.0,52.6,3.6
23,Mississippi,359,131,90,17,9,18,49,17,1,...,Mississippi,1354.7,245.6,179.9,15.7,59.2,13.9,21.1,73.0,20.5
24,Missouri,266,73,81,29,5,15,39,13,4,...,Missouri,1201.1,196.7,165.2,12.3,47.0,18.2,32.1,68.4,14.0
25,Montana,292,56,80,45,4,18,45,33,5,...,Montana,1113.0,162.7,140.9,19.1,42.4,26.1,15.6,61.9,6.6
26,Nebraska,234,53,53,30,5,11,26,22,6,...,Nebraska,1009.0,143.8,150.8,13.4,43.4,14.9,11.3,42.3,4.1
27,Nevada,282,68,64,19,4,12,58,18,3,...,Nevada,975.6,201.3,146.9,15.2,44.9,18.2,26.0,53.5,7.3
28,New Hampshire,255,56,99,24,6,9,26,26,11,...,New Hampshire,1002.7,146.5,144.6,11.9,33.4,16.4,30.3,58.1,0.0
29,New Jersey,234,74,55,14,20,14,31,12,5,...,New Jersey,1080.8,166.3,140.9,9.1,25.0,7.1,32.1,50.3,4.3
30,New Mexico,268,60,69,48,3,14,32,24,6,...,New Mexico,1130.3,152.7,136.8,33.4,41.3,24.2,39.0,85.5,10.8
31,New York,250,66,72,19,21,11,22,22,5,...,New York,1051.6,183.9,137.8,8.0,25.5,8.0,25.4,41.7,4.7
32,North Carolina,242,66,79,20,11,16,32,10,1,...,North Carolina,1032.5,156.2,154.3,12.9,38.5,13.2,30.9,67.1,8.6
33,North Dakota,79,16,20,8,4,0,12,16,4,...,North Dakota,1052.1,147.3,145.7,17.7,34.6,18.2,15.6,51.9,4.4
34,Ohio,245,70,84,13,4,18,34,14,2,...,Ohio,1228.9,196.9,165.1,12.5,44.6,13.8,47.2,78.2,9.1
35,Oklahoma,336,88,85,38,7,19,45,20,9,...,Oklahoma,1201.0,244.1,178.0,17.6,60.1,21.9,19.4,62.0,9.0
36,Oregon,248,53,76,36,3,12,33,15,5,...,Oregon,948.2,134.0,150.9,15.8,34.6,18.3,18.7,52.0,3.8
37,Pennsylvania,330,94,95,29,5,21,60,18,3,...,Pennsylvania,1216.8,175.7,156.4,9.9,32.8,12.6,42.4,69.0,8.5
38,Rhode Island,192,46,36,5,9,9,15,45,9,...,Rhode Island,1118.0,150.5,151.7,13.9,29.5,8.5,38.2,65.6,3.0
39,South Carolina,315,119,68,21,9,13,49,17,3,...,South Carolina,1173.3,170.9,157.5,15.6,43.6,16.3,34.9,77.8,12.7
40,South Dakota,209,49,46,29,2,21,21,28,2,...,South Dakota,1104.6,155.2,145.9,25.4,36.9,21.0,10.3,58.5,6.5
41,Tennessee,408,124,112,42,12,20,55,19,8,...,Tennessee,1222.7,212.0,168.2,16.2,51.2,17.2,45.6,86.5,11.5
42,Texas,272,68,68,29,6,21,55,18,1,...,Texas,852.6,173.9,143.5,15.8,36.2,13.3,14.1,44.2,7.6
43,Utah,273,66,58,22,0,11,48,44,6,...,Utah,661.5,155.6,120.8,10.3,32.7,20.8,20.5,49.4,2.9
44,Vermont,205,50,39,33,9,3,33,30,9,...,Vermont,1036.2,167.1,156.2,11.3,37.4,18.1,32.9,67.1,0.0
45,Virginia,286,76,98,28,10,15,37,11,3,...,Virginia,938.2,152.0,149.4,11.8,32.8,13.5,26.6,52.5,6.4
46,Washington,209,49,60,23,3,18,32,14,3,...,Washington,820.8,134.6,145.7,14.2,29.6,15.2,22.0,51.3,4.2
47,West Virginia,412,156,110,28,7,19,65,11,3,...,West Virginia,1462.7,197.8,178.5,16.1,59.5,19.4,81.4,122.2,7.0
48,Wisconsin,200,56,66,12,3,16,21,21,2,...,Wisconsin,1075.1,162.2,151.8,12.2,35.6,14.5,27.7,71.5,6.1
49,Wyoming,283,103,46,38,3,22,41,22,5,...,Wyoming,1027.4,160.4,140.6,27.3,53.5,30.5,17.4,60.4,4.9

In [169]:
##Comparing prison and state suicide rates
suicide_combined_df = combined_df.filter(["Jurisdiction", "Suicide", "State suicide"], axis=1)
suicide_combined_df

      Jurisdiction  Suicide  State suicide
0          Alabama        9           16.0
1           Alaska       37           27.5
2          Arizona       17           17.6
3         Arkansas       21           19.0
4       California       21           10.0
5         Colorado       20           21.5
6      Connecticut       24            9.3
7         Delaware       27           12.3
8          Florida       10           13.2
9          Georgia       13           13.7
10          Hawaii       29           12.9
11           Idaho       28           23.2
12        Illinois       16           10.5
13         Indiana       17           15.0
14            Iowa       20           18.0
15          Kansas       16           18.4
16        Kentucky        9           17.7
17       Louisiana       12           13.7
18           Maine       11           16.4
19        Maryland       20            9.2
20   Massachusetts       31            8.4
21        Michigan       16           14.0
22       Minnesota       16           13.1
23     Mississippi       17           13.9
24        Missouri       13           18.2
25         Montana       33           26.1
26        Nebraska       22           14.9
27          Nevada       18           18.2
28   New Hampshire       26           16.4
29      New Jersey       12            7.1
30      New Mexico       24           24.2
31        New York       22            8.0
32  North Carolina       10           13.2
33    North Dakota       16           18.2
34            Ohio       14           13.8
35        Oklahoma       20           21.9
36          Oregon       15           18.3
37    Pennsylvania       18           12.6
38    Rhode Island       45            8.5
39  South Carolina       17           16.3
40    South Dakota       28           21.0
41       Tennessee       19           17.2
42           Texas       18           13.3
43            Utah       44           20.8
44         Vermont       30           18.1
45        Virginia       11           13.5
46      Washington       14           15.2
47   West Virginia       11           19.4
48       Wisconsin       21           14.5
49         Wyoming       22           30.5

In [170]:
##Adding difference column
suicide_combined_df["difference"] = suicide_combined_df["Suicide"] - suicide_combined_df["State suicide"]
suicide_combined_df

      Jurisdiction  Suicide  State suicide  difference
0          Alabama        9           16.0        -7.0
1           Alaska       37           27.5         9.5
2          Arizona       17           17.6        -0.6
3         Arkansas       21           19.0         2.0
4       California       21           10.0        11.0
5         Colorado       20           21.5        -1.5
6      Connecticut       24            9.3        14.7
7         Delaware       27           12.3        14.7
8          Florida       10           13.2        -3.2
9          Georgia       13           13.7        -0.7
10          Hawaii       29           12.9        16.1
11           Idaho       28           23.2         4.8
12        Illinois       16           10.5         5.5
13         Indiana       17           15.0         2.0
14            Iowa       20           18.0         2.0
15          Kansas       16           18.4        -2.4
16        Kentucky        9           17.7        -8.7
17       Louisiana       12           13.7        -1.7
18           Maine       11           16.4        -5.4
19        Maryland       20            9.2        10.8
20   Massachusetts       31            8.4        22.6
21        Michigan       16           14.0         2.0
22       Minnesota       16           13.1         2.9
23     Mississippi       17           13.9         3.1
24        Missouri       13           18.2        -5.2
25         Montana       33           26.1         6.9
26        Nebraska       22           14.9         7.1
27          Nevada       18           18.2        -0.2
28   New Hampshire       26           16.4         9.6
29      New Jersey       12            7.1         4.9
30      New Mexico       24           24.2        -0.2
31        New York       22            8.0        14.0
32  North Carolina       10           13.2        -3.2
33    North Dakota       16           18.2        -2.2
34            Ohio       14           13.8         0.2
35        Oklahoma       20           21.9        -1.9
36          Oregon       15           18.3        -3.3
37    Pennsylvania       18           12.6         5.4
38    Rhode Island       45            8.5        36.5
39  South Carolina       17           16.3         0.7
40    South Dakota       28           21.0         7.0
41       Tennessee       19           17.2         1.8
42           Texas       18           13.3         4.7
43            Utah       44           20.8        23.2
44         Vermont       30           18.1        11.9
45        Virginia       11           13.5        -2.5
46      Washington       14           15.2        -1.2
47   West Virginia       11           19.4        -8.4
48       Wisconsin       21           14.5         6.5
49         Wyoming       22           30.5        -8.5

In [171]:
##Most states with big disparities between prison suicide rates and general public rates are smaller 
## like Utah, Rhode Island, Delaware, etc. But New York and Mass have high prison suicide rates.
suicide_combined_df.sort_values(by=["difference"], ascending = False)

      Jurisdiction  Suicide  State suicide  difference
38    Rhode Island       45            8.5        36.5
43            Utah       44           20.8        23.2
20   Massachusetts       31            8.4        22.6
10          Hawaii       29           12.9        16.1
6      Connecticut       24            9.3        14.7
7         Delaware       27           12.3        14.7
31        New York       22            8.0        14.0
44         Vermont       30           18.1        11.9
4       California       21           10.0        11.0
19        Maryland       20            9.2        10.8
28   New Hampshire       26           16.4         9.6
1           Alaska       37           27.5         9.5
26        Nebraska       22           14.9         7.1
40    South Dakota       28           21.0         7.0
25         Montana       33           26.1         6.9
48       Wisconsin       21           14.5         6.5
12        Illinois       16           10.5         5.5
37    Pennsylvania       18           12.6         5.4
29      New Jersey       12            7.1         4.9
11           Idaho       28           23.2         4.8
42           Texas       18           13.3         4.7
23     Mississippi       17           13.9         3.1
22       Minnesota       16           13.1         2.9
14            Iowa       20           18.0         2.0
3         Arkansas       21           19.0         2.0
21        Michigan       16           14.0         2.0
13         Indiana       17           15.0         2.0
41       Tennessee       19           17.2         1.8
39  South Carolina       17           16.3         0.7
34            Ohio       14           13.8         0.2
30      New Mexico       24           24.2        -0.2
27          Nevada       18           18.2        -0.2
2          Arizona       17           17.6        -0.6
9          Georgia       13           13.7        -0.7
46      Washington       14           15.2        -1.2
5         Colorado       20           21.5        -1.5
17       Louisiana       12           13.7        -1.7
35        Oklahoma       20           21.9        -1.9
33    North Dakota       16           18.2        -2.2
15          Kansas       16           18.4        -2.4
45        Virginia       11           13.5        -2.5
32  North Carolina       10           13.2        -3.2
8          Florida       10           13.2        -3.2
36          Oregon       15           18.3        -3.3
24        Missouri       13           18.2        -5.2
18           Maine       11           16.4        -5.4
0          Alabama        9           16.0        -7.0
47   West Virginia       11           19.4        -8.4
49         Wyoming       22           30.5        -8.5
16        Kentucky        9           17.7        -8.7

In [172]:
suicide_combined_df["Suicide"].mean()

20.0

In [173]:
suicide_combined_df["State suicide"].mean()

16.077999999999996

In [174]:
suicide_combined_df.loc[31]
##NY's discrepancy is due more to a low suicide rate for the general public than a high suicide rate for prisoners
##The state is only a couple notches above the prison rate, but half the general public rate.

Jurisdiction     New York
Suicide                22
State suicide         8.0
difference           14.0
Name: 31, dtype: object

In [175]:
liver_combined_df = combined_df.filter(["Jurisdiction", "Liver disease", "State liver disease"], axis=1)
liver_combined_df

      Jurisdiction  Liver disease  State liver disease
0          Alabama             30                 15.9
1           Alaska             19                 22.4
2          Arizona             30                 16.8
3         Arkansas             26                 14.9
4       California             24                 13.9
5         Colorado             35                 17.7
6      Connecticut             21                 12.4
7         Delaware             21                 10.8
8          Florida             24                 13.0
9          Georgia             13                 12.1
10          Hawaii             18                  8.2
11           Idaho             19                 15.5
12        Illinois             10                 11.4
13         Indiana             22                 14.8
14            Iowa             11                 11.4
15          Kansas             30                 14.1
16        Kentucky             27                 17.0
17       Louisiana             41                 10.8
18           Maine             16                 13.9
19        Maryland             21                  9.5
20   Massachusetts             34                 11.2
21        Michigan             21                 13.9
22       Minnesota             20                 13.7
23     Mississippi             17                 15.7
24        Missouri             29                 12.3
25         Montana             45                 19.1
26        Nebraska             30                 13.4
27          Nevada             19                 15.2
28   New Hampshire             24                 11.9
29      New Jersey             14                  9.1
30      New Mexico             48                 33.4
31        New York             19                  8.0
32  North Carolina             20                 12.9
33    North Dakota              8                 17.7
34            Ohio             13                 12.5
35        Oklahoma             38                 17.6
36          Oregon             36                 15.8
37    Pennsylvania             29                  9.9
38    Rhode Island              5                 13.9
39  South Carolina             21                 15.6
40    South Dakota             29                 25.4
41       Tennessee             42                 16.2
42           Texas             29                 15.8
43            Utah             22                 10.3
44         Vermont             33                 11.3
45        Virginia             28                 11.8
46      Washington             23                 14.2
47   West Virginia             28                 16.1
48       Wisconsin             12                 12.2
49         Wyoming             38                 27.3

In [176]:
liver_combined_df["difference"] = liver_combined_df["Liver disease"] - liver_combined_df["State liver disease"]
liver_combined_df

      Jurisdiction  Liver disease  State liver disease  difference
0          Alabama             30                 15.9        14.1
1           Alaska             19                 22.4        -3.4
2          Arizona             30                 16.8        13.2
3         Arkansas             26                 14.9        11.1
4       California             24                 13.9        10.1
5         Colorado             35                 17.7        17.3
6      Connecticut             21                 12.4         8.6
7         Delaware             21                 10.8        10.2
8          Florida             24                 13.0        11.0
9          Georgia             13                 12.1         0.9
10          Hawaii             18                  8.2         9.8
11           Idaho             19                 15.5         3.5
12        Illinois             10                 11.4        -1.4
13         Indiana             22                 14.8         7.2
14            Iowa             11                 11.4        -0.4
15          Kansas             30                 14.1        15.9
16        Kentucky             27                 17.0        10.0
17       Louisiana             41                 10.8        30.2
18           Maine             16                 13.9         2.1
19        Maryland             21                  9.5        11.5
20   Massachusetts             34                 11.2        22.8
21        Michigan             21                 13.9         7.1
22       Minnesota             20                 13.7         6.3
23     Mississippi             17                 15.7         1.3
24        Missouri             29                 12.3        16.7
25         Montana             45                 19.1        25.9
26        Nebraska             30                 13.4        16.6
27          Nevada             19                 15.2         3.8
28   New Hampshire             24                 11.9        12.1
29      New Jersey             14                  9.1         4.9
30      New Mexico             48                 33.4        14.6
31        New York             19                  8.0        11.0
32  North Carolina             20                 12.9         7.1
33    North Dakota              8                 17.7        -9.7
34            Ohio             13                 12.5         0.5
35        Oklahoma             38                 17.6        20.4
36          Oregon             36                 15.8        20.2
37    Pennsylvania             29                  9.9        19.1
38    Rhode Island              5                 13.9        -8.9
39  South Carolina             21                 15.6         5.4
40    South Dakota             29                 25.4         3.6
41       Tennessee             42                 16.2        25.8
42           Texas             29                 15.8        13.2
43            Utah             22                 10.3        11.7
44         Vermont             33                 11.3        21.7
45        Virginia             28                 11.8        16.2
46      Washington             23                 14.2         8.8
47   West Virginia             28                 16.1        11.9
48       Wisconsin             12                 12.2        -0.2
49         Wyoming             38                 27.3        10.7

In [177]:
liver_combined_df["Liver disease"].mean()

24.64

In [178]:
liver_combined_df["State liver disease"].mean()

14.597999999999995

In [179]:
liver_combined_df["difference"].mean()

10.042

In [180]:
##Louisiana leads the way. Much higher liver disease in prison. Oregon has a big difference too.
liver_combined_df.sort_values(by=["difference"], ascending = False)

      Jurisdiction  Liver disease  State liver disease  difference
17       Louisiana             41                 10.8        30.2
25         Montana             45                 19.1        25.9
41       Tennessee             42                 16.2        25.8
20   Massachusetts             34                 11.2        22.8
44         Vermont             33                 11.3        21.7
35        Oklahoma             38                 17.6        20.4
36          Oregon             36                 15.8        20.2
37    Pennsylvania             29                  9.9        19.1
5         Colorado             35                 17.7        17.3
24        Missouri             29                 12.3        16.7
26        Nebraska             30                 13.4        16.6
45        Virginia             28                 11.8        16.2
15          Kansas             30                 14.1        15.9
30      New Mexico             48                 33.4        14.6
0          Alabama             30                 15.9        14.1
42           Texas             29                 15.8        13.2
2          Arizona             30                 16.8        13.2
28   New Hampshire             24                 11.9        12.1
47   West Virginia             28                 16.1        11.9
43            Utah             22                 10.3        11.7
19        Maryland             21                  9.5        11.5
3         Arkansas             26                 14.9        11.1
8          Florida             24                 13.0        11.0
31        New York             19                  8.0        11.0
49         Wyoming             38                 27.3        10.7
7         Delaware             21                 10.8        10.2
4       California             24                 13.9        10.1
16        Kentucky             27                 17.0        10.0
10          Hawaii             18                  8.2         9.8
46      Washington             23                 14.2         8.8
6      Connecticut             21                 12.4         8.6
13         Indiana             22                 14.8         7.2
32  North Carolina             20                 12.9         7.1
21        Michigan             21                 13.9         7.1
22       Minnesota             20                 13.7         6.3
39  South Carolina             21                 15.6         5.4
29      New Jersey             14                  9.1         4.9
27          Nevada             19                 15.2         3.8
40    South Dakota             29                 25.4         3.6
11           Idaho             19                 15.5         3.5
18           Maine             16                 13.9         2.1
23     Mississippi             17                 15.7         1.3
9          Georgia             13                 12.1         0.9
34            Ohio             13                 12.5         0.5
48       Wisconsin             12                 12.2        -0.2
14            Iowa             11                 11.4        -0.4
12        Illinois             10                 11.4        -1.4
1           Alaska             19                 22.4        -3.4
38    Rhode Island              5                 13.9        -8.9
33    North Dakota              8                 17.7        -9.7

In [181]:
homicide_combined_df = combined_df.filter(["Jurisdiction", "Homicide", "State homicide"], axis=1)
homicide_combined_df

      Jurisdiction  Homicide  State homicide
0          Alabama        10            14.2
1           Alaska         4             7.3
2          Arizona         8             7.5
3         Arkansas         6            13.0
4       California        10             6.1
5         Colorado         8             5.8
6      Connecticut         2             4.6
7         Delaware         2             9.9
8          Florida         8             7.8
9          Georgia         8            10.5
10          Hawaii         5             3.3
11           Idaho         3             2.5
12        Illinois         2            11.2
13         Indiana         6             9.7
14            Iowa         1             3.6
15          Kansas         2             7.0
16        Kentucky         3             9.5
17       Louisiana         3            19.9
18           Maine        13             1.6
19        Maryland        12            11.4
20   Massachusetts         2             2.7
21        Michigan         3             8.7
22       Minnesota         1             3.6
23     Mississippi        10            20.5
24        Missouri         4            14.0
25         Montana         4             6.6
26        Nebraska         7             4.1
27          Nevada         5             7.3
28   New Hampshire         0             0.0
29      New Jersey         3             4.3
30      New Mexico         9            10.8
31        New York         3             4.7
32  North Carolina         2             8.6
33    North Dakota         0             4.4
34            Ohio         3             9.1
35        Oklahoma        14             9.0
36          Oregon         4             3.8
37    Pennsylvania         2             8.5
38    Rhode Island         2             3.0
39  South Carolina        13            12.7
40    South Dakota         5             6.5
41       Tennessee         9            11.5
42           Texas         3             7.6
43            Utah         9             2.9
44         Vermont         0             0.0
45        Virginia         3             6.4
46      Washington         3             4.2
47   West Virginia         7             7.0
48       Wisconsin         0             6.1
49         Wyoming         0             4.9

In [182]:
homicide_combined_df["difference"] = homicide_combined_df["Homicide"] - homicide_combined_df["State homicide"]
homicide_combined_df

      Jurisdiction  Homicide  State homicide  difference
0          Alabama        10            14.2        -4.2
1           Alaska         4             7.3        -3.3
2          Arizona         8             7.5         0.5
3         Arkansas         6            13.0        -7.0
4       California        10             6.1         3.9
5         Colorado         8             5.8         2.2
6      Connecticut         2             4.6        -2.6
7         Delaware         2             9.9        -7.9
8          Florida         8             7.8         0.2
9          Georgia         8            10.5        -2.5
10          Hawaii         5             3.3         1.7
11           Idaho         3             2.5         0.5
12        Illinois         2            11.2        -9.2
13         Indiana         6             9.7        -3.7
14            Iowa         1             3.6        -2.6
15          Kansas         2             7.0        -5.0
16        Kentucky         3             9.5        -6.5
17       Louisiana         3            19.9       -16.9
18           Maine        13             1.6        11.4
19        Maryland        12            11.4         0.6
20   Massachusetts         2             2.7        -0.7
21        Michigan         3             8.7        -5.7
22       Minnesota         1             3.6        -2.6
23     Mississippi        10            20.5       -10.5
24        Missouri         4            14.0       -10.0
25         Montana         4             6.6        -2.6
26        Nebraska         7             4.1         2.9
27          Nevada         5             7.3        -2.3
28   New Hampshire         0             0.0         0.0
29      New Jersey         3             4.3        -1.3
30      New Mexico         9            10.8        -1.8
31        New York         3             4.7        -1.7
32  North Carolina         2             8.6        -6.6
33    North Dakota         0             4.4        -4.4
34            Ohio         3             9.1        -6.1
35        Oklahoma        14             9.0         5.0
36          Oregon         4             3.8         0.2
37    Pennsylvania         2             8.5        -6.5
38    Rhode Island         2             3.0        -1.0
39  South Carolina        13            12.7         0.3
40    South Dakota         5             6.5        -1.5
41       Tennessee         9            11.5        -2.5
42           Texas         3             7.6        -4.6
43            Utah         9             2.9         6.1
44         Vermont         0             0.0         0.0
45        Virginia         3             6.4        -3.4
46      Washington         3             4.2        -1.2
47   West Virginia         7             7.0         0.0
48       Wisconsin         0             6.1        -6.1
49         Wyoming         0             4.9        -4.9

In [183]:
##Comparing homocide rates in state prisons vs overall state homicide rates.
homicide_combined_df.sort_values(by=["difference"], ascending = False)

      Jurisdiction  Homicide  State homicide  difference
18           Maine        13             1.6        11.4
43            Utah         9             2.9         6.1
35        Oklahoma        14             9.0         5.0
4       California        10             6.1         3.9
26        Nebraska         7             4.1         2.9
5         Colorado         8             5.8         2.2
10          Hawaii         5             3.3         1.7
19        Maryland        12            11.4         0.6
11           Idaho         3             2.5         0.5
2          Arizona         8             7.5         0.5
39  South Carolina        13            12.7         0.3
36          Oregon         4             3.8         0.2
8          Florida         8             7.8         0.2
28   New Hampshire         0             0.0         0.0
44         Vermont         0             0.0         0.0
47   West Virginia         7             7.0         0.0
20   Massachusetts         2             2.7        -0.7
38    Rhode Island         2             3.0        -1.0
46      Washington         3             4.2        -1.2
29      New Jersey         3             4.3        -1.3
40    South Dakota         5             6.5        -1.5
31        New York         3             4.7        -1.7
30      New Mexico         9            10.8        -1.8
27          Nevada         5             7.3        -2.3
9          Georgia         8            10.5        -2.5
41       Tennessee         9            11.5        -2.5
25         Montana         4             6.6        -2.6
6      Connecticut         2             4.6        -2.6
22       Minnesota         1             3.6        -2.6
14            Iowa         1             3.6        -2.6
1           Alaska         4             7.3        -3.3
45        Virginia         3             6.4        -3.4
13         Indiana         6             9.7        -3.7
0          Alabama        10            14.2        -4.2
33    North Dakota         0             4.4        -4.4
42           Texas         3             7.6        -4.6
49         Wyoming         0             4.9        -4.9
15          Kansas         2             7.0        -5.0
21        Michigan         3             8.7        -5.7
34            Ohio         3             9.1        -6.1
48       Wisconsin         0             6.1        -6.1
37    Pennsylvania         2             8.5        -6.5
16        Kentucky         3             9.5        -6.5
32  North Carolina         2             8.6        -6.6
3         Arkansas         6            13.0        -7.0
7         Delaware         2             9.9        -7.9
12        Illinois         2            11.2        -9.2
24        Missouri         4            14.0       -10.0
23     Mississippi        10            20.5       -10.5
17       Louisiana         3            19.9       -16.9

In [184]:
drug_combined_df = combined_df.filter(["Jurisdiction", "Drug/alcohol intoxication", "State drug/alcohol intoxication"], axis=1)
drug_combined_df

      Jurisdiction  Drug/alcohol intoxication  State drug/alcohol intoxication
0          Alabama                          3                             22.3
1           Alaska                         11                             22.0
2          Arizona                         11                             35.8
3         Arkansas                         17                             19.1
4       California                         12                             21.8
5         Colorado                          9                             24.9
6      Connecticut                          1                             39.1
7         Delaware                          5                             47.3
8          Florida                         10                             35.0
9          Georgia                          1                             18.0
10          Hawaii                          4                             18.3
11           Idaho                          4                             15.9
12        Illinois                          2                             28.1
13         Indiana                          9                             36.7
14            Iowa                          2                             14.3
15          Kansas                          4                             17.4
16        Kentucky                          1                             49.2
17       Louisiana                          1                             42.7
18           Maine                          5                             39.7
19        Maryland                         16                             44.6
20   Massachusetts                          5                             33.9
21        Michigan                          4                             28.6
22       Minnesota                          3                             19.0
23     Mississippi                          1                             21.1
24        Missouri                          4                             32.1
25         Montana                          5                             15.6
26        Nebraska                          6                             11.3
27          Nevada                          3                             26.0
28   New Hampshire                         11                             30.3
29      New Jersey                          5                             32.1
30      New Mexico                          6                             39.0
31        New York                          5                             25.4
32  North Carolina                          1                             30.9
33    North Dakota                          4                             15.6
34            Ohio                          2                             47.2
35        Oklahoma                          9                             19.4
36          Oregon                          5                             18.7
37    Pennsylvania                          3                             42.4
38    Rhode Island                          9                             38.2
39  South Carolina                          3                             34.9
40    South Dakota                          2                             10.3
41       Tennessee                          8                             45.6
42           Texas                          1                             14.1
43            Utah                          6                             20.5
44         Vermont                          9                             32.9
45        Virginia                          3                             26.6
46      Washington                          3                             22.0
47   West Virginia                          3                             81.4
48       Wisconsin                          2                             27.7
49         Wyoming                          5                             17.4

In [185]:
drug_combined_df["difference"] = drug_combined_df["Drug/alcohol intoxication"] - drug_combined_df["State drug/alcohol intoxication"]
drug_combined_df

,Jurisdiction,Drug/alcohol intoxication,State drug/alcohol intoxication,difference
0,Alabama,3,22.3,-19.3
1,Alaska,11,22.0,-11.0
2,Arizona,11,35.8,-24.8
3,Arkansas,17,19.1,-2.1
4,California,12,21.8,-9.8
5,Colorado,9,24.9,-15.9
6,Connecticut,1,39.1,-38.1
7,Delaware,5,47.3,-42.3
8,Florida,10,35.0,-25.0
9,Georgia,1,18.0,-17.0
10,Hawaii,4,18.3,-14.3
11,Idaho,4,15.9,-11.9
12,Illinois,2,28.1,-26.1
13,Indiana,9,36.7,-27.7
14,Iowa,2,14.3,-12.3
15,Kansas,4,17.4,-13.4
16,Kentucky,1,49.2,-48.2
17,Louisiana,1,42.7,-41.7
18,Maine,5,39.7,-34.7
19,Maryland,16,44.6,-28.6
20,Massachusetts,5,33.9,-28.9
21,Michigan,4,28.6,-24.6
22,Minnesota,3,19.0,-16.0
23,Mississippi,1,21.1,-20.1
24,Missouri,4,32.1,-28.1
25,Montana,5,15.6,-10.6
26,Nebraska,6,11.3,-5.3
27,Nevada,3,26.0,-23.0
28,New Hampshire,11,30.3,-19.3
29,New Jersey,5,32.1,-27.1
30,New Mexico,6,39.0,-33.0
31,New York,5,25.4,-20.4
32,North Carolina,1,30.9,-29.9
33,North Dakota,4,15.6,-11.6
34,Ohio,2,47.2,-45.2
35,Oklahoma,9,19.4,-10.4
36,Oregon,5,18.7,-13.7
37,Pennsylvania,3,42.4,-39.4
38,Rhode Island,9,38.2,-29.2
39,South Carolina,3,34.9,-31.9
40,South Dakota,2,10.3,-8.3
41,Tennessee,8,45.6,-37.6
42,Texas,1,14.1,-13.1
43,Utah,6,20.5,-14.5
44,Vermont,9,32.9,-23.9
45,Virginia,3,26.6,-23.6
46,Washington,3,22.0,-19.0
47,West Virginia,3,81.4,-78.4
48,Wisconsin,2,27.7,-25.7
49,Wyoming,5,17.4,-12.4

In [186]:
##Arkansas has a high rate of drug/alcohol deaths, not far from the state's overall number.
##Maryland's is also high, but much lower than the state number.
drug_combined_df.sort_values(by=["difference"], ascending = False)

,Jurisdiction,Drug/alcohol intoxication,State drug/alcohol intoxication,difference
3,Arkansas,17,19.1,-2.1
26,Nebraska,6,11.3,-5.3
40,South Dakota,2,10.3,-8.3
4,California,12,21.8,-9.8
35,Oklahoma,9,19.4,-10.4
25,Montana,5,15.6,-10.6
1,Alaska,11,22.0,-11.0
33,North Dakota,4,15.6,-11.6
11,Idaho,4,15.9,-11.9
14,Iowa,2,14.3,-12.3
49,Wyoming,5,17.4,-12.4
42,Texas,1,14.1,-13.1
15,Kansas,4,17.4,-13.4
36,Oregon,5,18.7,-13.7
10,Hawaii,4,18.3,-14.3
43,Utah,6,20.5,-14.5
5,Colorado,9,24.9,-15.9
22,Minnesota,3,19.0,-16.0
9,Georgia,1,18.0,-17.0
46,Washington,3,22.0,-19.0
28,New Hampshire,11,30.3,-19.3
0,Alabama,3,22.3,-19.3
23,Mississippi,1,21.1,-20.1
31,New York,5,25.4,-20.4
27,Nevada,3,26.0,-23.0
45,Virginia,3,26.6,-23.6
44,Vermont,9,32.9,-23.9
21,Michigan,4,28.6,-24.6
2,Arizona,11,35.8,-24.8
8,Florida,10,35.0,-25.0
48,Wisconsin,2,27.7,-25.7
12,Illinois,2,28.1,-26.1
29,New Jersey,5,32.1,-27.1
13,Indiana,9,36.7,-27.7
24,Missouri,4,32.1,-28.1
19,Maryland,16,44.6,-28.6
20,Massachusetts,5,33.9,-28.9
38,Rhode Island,9,38.2,-29.2
32,North Carolina,1,30.9,-29.9
39,South Carolina,3,34.9,-31.9
30,New Mexico,6,39.0,-33.0
18,Maine,5,39.7,-34.7
41,Tennessee,8,45.6,-37.6
6,Connecticut,1,39.1,-38.1
37,Pennsylvania,3,42.4,-39.4
17,Louisiana,1,42.7,-41.7
7,Delaware,5,47.3,-42.3
34,Ohio,2,47.2,-45.2
16,Kentucky,1,49.2,-48.2
47,West Virginia,3,81.4,-78.4